// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const linksByIDs = `-- name: LinksByIDs :many
SELECT id, mode, from_node_id, to_node_id
FROM world.network_links
WHERE id = ANY($1::uuid[])
`

type LinksByIDsRow struct {
	ID         uuid.UUID
	Mode       WorldLinkMode
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
}

// LinksByIDs devuelve la topología (modo, extremos) de un conjunto de enlaces
// para validar la contigüidad y el multimodalismo de una ruta. NO preserva el
// orden de entrada: la capa de servicio reordena por la secuencia pedida y
// detecta los ids inexistentes (una ruta con un enlace que no existe es 422).
func (q *Queries) LinksByIDs(ctx context.Context, linkIds []uuid.UUID) ([]LinksByIDsRow, error) {
	rows, err := q.db.Query(ctx, linksByIDs, linkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinksByIDsRow
	for rows.Next() {
		var i LinksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.FromNodeID,
			&i.ToNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGraphEdges = `-- name: LoadGraphEdges :many

SELECT l.id, l.mode, l.from_node_id, l.to_node_id,
       l.length_m, l.base_speed_kmh, l.capacity_per_hour,
       COALESCE(AVG(s.congestion_ema), 1.0)::float8 AS congestion_ema,
       COALESCE(AVG(r.customs_rate_bp), 0)::float8   AS customs_rate_bp
FROM world.network_links l
LEFT JOIN world.link_segments s ON s.link_id = l.id
LEFT JOIN world.regions r       ON r.id = s.region_id
WHERE ($1::text[] IS NULL
       OR l.mode::text = ANY($1::text[]))
GROUP BY l.id, l.mode, l.from_node_id, l.to_node_id,
         l.length_m, l.base_speed_kmh, l.capacity_per_hour
`

type LoadGraphEdgesRow struct {
	ID              uuid.UUID
	Mode            WorldLinkMode
	FromNodeID      uuid.UUID
	ToNodeID        uuid.UUID
	LengthM         int32
	BaseSpeedKmh    int32
	CapacityPerHour int32
	CongestionEma   float64
	CustomsRateBp   float64
}

// =============================================================================
// Imperio Industrial — queries del pathfinding del Logistics Service (GDD 7.4).
//
// El route-plan (POST /logistics/route-plans) es una operación de SOLO cálculo
// (no persiste nada): carga el grafo de enlaces ponderado por la congestión
// suavizada (EMA) que publican los shards y corre Dijkstra sobre nodos. A la
// escala de la Fase 1 (una región, pocos nodos) cargar el grafo entero de la
// región es correcto y barato; la jerarquía HPA* del GDD 7.4 queda para cuando
// la medición del grafo mundial lo exija (la interface Planner ya lo enmarca).
//
// El coste monetario aproximado (optimize=cost) combina combustible (∝ km) y
// aduanas/peajes según customs_rate_bp de la región de cada segmento: por eso
// se agrega la congestión y las aduanas por enlace desde sus segmentos.
// =============================================================================
// LoadGraphEdges devuelve TODOS los enlaces (opcionalmente filtrados por modos)
// con la congestión EMA media y la tasa de aduanas media de sus segmentos. Un
// enlace sin segmentos (no debería ocurrir en un mundo bien sembrado) cae a
// congestión fluida (1.0) y aduanas 0 — defensivo. Los pesos exactos (ETA en
// sim-segundos y coste) los deriva el planner en Go a partir de estos campos.
func (q *Queries) LoadGraphEdges(ctx context.Context, modes []string) ([]LoadGraphEdgesRow, error) {
	rows, err := q.db.Query(ctx, loadGraphEdges, modes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadGraphEdgesRow
	for rows.Next() {
		var i LoadGraphEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.LengthM,
			&i.BaseSpeedKmh,
			&i.CapacityPerHour,
			&i.CongestionEma,
			&i.CustomsRateBp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTerminalNodes = `-- name: LoadTerminalNodes :many
SELECT id, node_id, transshipment_per_hour
FROM world.terminals
`

type LoadTerminalNodesRow struct {
	ID                   uuid.UUID
	NodeID               uuid.UUID
	TransshipmentPerHour int32
}

// LoadTerminalNodes devuelve TODAS las terminales intermodales del mundo (node_id
// → id, capacidad de transbordo por hora). El pathfinding las carga una vez por
// consulta para (a) permitir un cambio de modo SOLO en un nodo con terminal (GDD
// 7.3: sin terminal, el transbordo no es transitable) y (b) sumar el tiempo de
// transbordo a la ETA del tramo donde cambia el modo. Las terminales son escasas
// (una por junction intermodal), así que cargarlas enteras es barato.
func (q *Queries) LoadTerminalNodes(ctx context.Context) ([]LoadTerminalNodesRow, error) {
	rows, err := q.db.Query(ctx, loadTerminalNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadTerminalNodesRow
	for rows.Next() {
		var i LoadTerminalNodesRow
		if err := rows.Scan(&i.ID, &i.NodeID, &i.TransshipmentPerHour); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminalsAtNodes = `-- name: TerminalsAtNodes :many
SELECT id, node_id
FROM world.terminals
WHERE node_id = ANY($1::uuid[])
`

type TerminalsAtNodesRow struct {
	ID     uuid.UUID
	NodeID uuid.UUID
}

// TerminalsAtNodes devuelve las terminales intermodales presentes en un conjunto
// de nodos (transbordo en un cambio de modo, GDD 7.3). Lo usan tanto el
// route-plan (anotar transshipment_terminal_id en el tramo donde cambia el modo)
// como la creación de rutas (validar que un salto multimodal ocurre en un nodo
// con terminal).
func (q *Queries) TerminalsAtNodes(ctx context.Context, nodeIds []uuid.UUID) ([]TerminalsAtNodesRow, error) {
	rows, err := q.db.Query(ctx, terminalsAtNodes, nodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TerminalsAtNodesRow
	for rows.Next() {
		var i TerminalsAtNodesRow
		if err := rows.Scan(&i.ID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
