// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type WorldLinkMode string

const (
	WorldLinkModeRoad WorldLinkMode = "road"
	WorldLinkModeRail WorldLinkMode = "rail"
	WorldLinkModeSea  WorldLinkMode = "sea"
)

func (e *WorldLinkMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldLinkMode(s)
	case string:
		*e = WorldLinkMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldLinkMode: %T", src)
	}
	return nil
}

type NullWorldLinkMode struct {
	WorldLinkMode WorldLinkMode
	Valid         bool // Valid is true if WorldLinkMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldLinkMode) Scan(value interface{}) error {
	if value == nil {
		ns.WorldLinkMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldLinkMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldLinkMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldLinkMode), nil
}

type WorldNodeKind string

const (
	WorldNodeKindMine               WorldNodeKind = "mine"
	WorldNodeKindFactory            WorldNodeKind = "factory"
	WorldNodeKindWarehouse          WorldNodeKind = "warehouse"
	WorldNodeKindPort               WorldNodeKind = "port"
	WorldNodeKindStation            WorldNodeKind = "station"
	WorldNodeKindDistributionCenter WorldNodeKind = "distribution_center"
	WorldNodeKindJunction           WorldNodeKind = "junction"
	WorldNodeKindCityGate           WorldNodeKind = "city_gate"
)

func (e *WorldNodeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldNodeKind(s)
	case string:
		*e = WorldNodeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldNodeKind: %T", src)
	}
	return nil
}

type NullWorldNodeKind struct {
	WorldNodeKind WorldNodeKind
	Valid         bool // Valid is true if WorldNodeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldNodeKind) Scan(value interface{}) error {
	if value == nil {
		ns.WorldNodeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldNodeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldNodeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldNodeKind), nil
}

type WorldRouteKind string

const (
	WorldRouteKindFixedLine WorldRouteKind = "fixed_line"
	WorldRouteKindOnDemand  WorldRouteKind = "on_demand"
)

func (e *WorldRouteKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldRouteKind(s)
	case string:
		*e = WorldRouteKind(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldRouteKind: %T", src)
	}
	return nil
}

type NullWorldRouteKind struct {
	WorldRouteKind WorldRouteKind
	Valid          bool // Valid is true if WorldRouteKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldRouteKind) Scan(value interface{}) error {
	if value == nil {
		ns.WorldRouteKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldRouteKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldRouteKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldRouteKind), nil
}

type WorldRoute struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	Name           string
	Kind           WorldRouteKind
	Active         bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WorldRouteLeg struct {
	RouteID  uuid.UUID
	LegIndex int32
	LinkID   uuid.UUID
}
