// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listLinkSegmentsByLinks = `-- name: ListLinkSegmentsByLinks :many
SELECT id, link_id, region_id, seq, length_m,
       congestion_ema::float8 AS congestion_ema, updated_at_sim
FROM world.link_segments
WHERE link_id = ANY($1::uuid[])
ORDER BY link_id, seq
`

type ListLinkSegmentsByLinksRow struct {
	ID            uuid.UUID
	LinkID        uuid.UUID
	RegionID      uuid.UUID
	Seq           int32
	LengthM       int32
	CongestionEma float64
	UpdatedAtSim  int64
}

// ListLinkSegmentsByLinks devuelve los segmentos (con su congestión EMA) de un
// conjunto de enlaces, en orden estable por enlace y secuencia. congestion_ema
// es NUMERIC → float8 (número del contrato, no dinero).
func (q *Queries) ListLinkSegmentsByLinks(ctx context.Context, linkIds []uuid.UUID) ([]ListLinkSegmentsByLinksRow, error) {
	rows, err := q.db.Query(ctx, listLinkSegmentsByLinks, linkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkSegmentsByLinksRow
	for rows.Next() {
		var i ListLinkSegmentsByLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.RegionID,
			&i.Seq,
			&i.LengthM,
			&i.CongestionEma,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkLinks = `-- name: ListNetworkLinks :many

SELECT l.id, l.mode, l.from_node_id, l.to_node_id,
       ST_AsGeoJSON(l.path)::text AS path,
       l.length_m, l.capacity_per_hour, l.base_speed_kmh
FROM world.network_links l
WHERE ($1::uuid IS NULL OR EXISTS (
        SELECT 1 FROM world.link_segments s
        WHERE s.link_id = l.id AND s.region_id = $1::uuid))
  AND ($2::world.link_mode IS NULL OR l.mode = $2::world.link_mode)
  AND ($3::uuid IS NULL OR l.from_node_id = $3::uuid)
  AND ($4::uuid IS NULL OR l.id > $4::uuid)
ORDER BY l.id
LIMIT $5
`

type ListNetworkLinksParams struct {
	RegionID   *uuid.UUID
	Mode       NullWorldLinkMode
	FromNodeID *uuid.UUID
	AfterID    *uuid.UUID
	PageLimit  int32
}

type ListNetworkLinksRow struct {
	ID              uuid.UUID
	Mode            WorldLinkMode
	FromNodeID      uuid.UUID
	ToNodeID        uuid.UUID
	Path            string
	LengthM         int32
	CapacityPerHour int32
	BaseSpeedKmh    int32
}

// ─── Enlaces del grafo ────────────────────────────────────────────────────────
// ListNetworkLinks devuelve los enlaces de uso común con filtros opcionales por
// región (de ALGUNO de sus segmentos), modo y nodo de origen, y paginación
// keyset por id. path sale como GeoJSON plano; los segmentos se resuelven aparte
// (ListLinkSegmentsByLinks) por los ids de la página, para no duplicar filas de
// enlace en el JOIN.
func (q *Queries) ListNetworkLinks(ctx context.Context, arg ListNetworkLinksParams) ([]ListNetworkLinksRow, error) {
	rows, err := q.db.Query(ctx, listNetworkLinks,
		arg.RegionID,
		arg.Mode,
		arg.FromNodeID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNetworkLinksRow
	for rows.Next() {
		var i ListNetworkLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.Path,
			&i.LengthM,
			&i.CapacityPerHour,
			&i.BaseSpeedKmh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkNodes = `-- name: ListNetworkNodes :many


SELECT n.id, n.kind, n.region_id, n.building_id, n.city_id,
       ST_AsGeoJSON(n.location)::text AS location,
       t.id AS terminal_id
FROM world.network_nodes n
LEFT JOIN world.terminals t ON t.node_id = n.id
WHERE ($1::uuid IS NULL OR n.region_id = $1::uuid)
  AND ($2::world.node_kind IS NULL OR n.kind = $2::world.node_kind)
  AND ($3::uuid IS NULL OR n.id > $3::uuid)
ORDER BY n.id
LIMIT $4
`

type ListNetworkNodesParams struct {
	RegionID  *uuid.UUID
	Kind      NullWorldNodeKind
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListNetworkNodesRow struct {
	ID         uuid.UUID
	Kind       WorldNodeKind
	RegionID   uuid.UUID
	BuildingID *uuid.UUID
	CityID     *uuid.UUID
	Location   string
	TerminalID *uuid.UUID
}

// =============================================================================
// Imperio Industrial — queries sqlc del bounded context logistics (ADR-020).
// Lectura del grafo logístico (contrato logistics/network/*): nodos, enlaces de
// uso común y sus segmentos con la congestión suavizada (EMA) que publican los
// shards. Es lectura pública observable por cualquier corporación (sin filtro
// de propiedad): el grafo es información del mundo, no de un titular.
//
// Geometrías (location/path): SRID 0 planar, metros de mundo (ADR-019). Se
// proyectan con ST_AsGeoJSON(...)::text — objetos GeoJSON con coordenadas planas
// [x_m, y_m] que los handlers embeben tal cual en GeoPoint/GeoLineString (jamás
// lon/lat). congestion_ema es NUMERIC → float8 (número del contrato, no dinero).
//
// Paginación keyset por id (UUIDv7 ≈ orden de creación) con page_limit; la capa
// de servicio pide page_limit+1 para detectar la página siguiente.
//
// La frontera de bounded context es de código Go, no de esquema: estas queries
// leen world.* (el paquete Go internal/logistics NUNCA importa internal/world).
// =============================================================================
// ─── Nodos del grafo ──────────────────────────────────────────────────────────
// ListNetworkNodes devuelve los nodos con filtros opcionales por región y clase,
// y paginación keyset por id. location sale como GeoJSON plano (SRID 0).
// terminal_id (v1.7.0) identifica la terminal intermodal del nodo, si la tiene:
// es la única vía del contrato para descubrir terminales desde el grafo.
func (q *Queries) ListNetworkNodes(ctx context.Context, arg ListNetworkNodesParams) ([]ListNetworkNodesRow, error) {
	rows, err := q.db.Query(ctx, listNetworkNodes,
		arg.RegionID,
		arg.Kind,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNetworkNodesRow
	for rows.Next() {
		var i ListNetworkNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RegionID,
			&i.BuildingID,
			&i.CityID,
			&i.Location,
			&i.TerminalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const networkNodeExists = `-- name: NetworkNodeExists :one
SELECT EXISTS (SELECT 1 FROM world.network_nodes WHERE id = $1)
`

// NetworkNodeExists comprueba la existencia de un nodo del grafo (validación de
// origen/destino del route-plan y de los legs de una ruta).
func (q *Queries) NetworkNodeExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, networkNodeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
