// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM world.routes WHERE id = $1
`

// DeleteRoute elimina la ruta; sus legs caen en cascada (ON DELETE CASCADE). Los
// vehículos asignados los deja sin ruta el motor de tránsito de world al no
// encontrarla — aquí solo se borra la definición.
func (q *Queries) DeleteRoute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const deleteRouteLegs = `-- name: DeleteRouteLegs :exec
DELETE FROM world.route_legs WHERE route_id = $1
`

// DeleteRouteLegs borra todos los legs de una ruta (paso previo al reemplazo de
// la secuencia en un patch de legs).
func (q *Queries) DeleteRouteLegs(ctx context.Context, routeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRouteLegs, routeID)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, owner_account_id, name, kind, active, created_at, updated_at
FROM world.routes
WHERE id = $1
`

// GetRoute devuelve una ruta por id (la autorización por titular la aplica la
// capa de servicio: 403 si es ajena).
func (q *Queries) GetRoute(ctx context.Context, id uuid.UUID) (WorldRoute, error) {
	row := q.db.QueryRow(ctx, getRoute, id)
	var i WorldRoute
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Name,
		&i.Kind,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRouteForUpdate = `-- name: GetRouteForUpdate :one
SELECT id, owner_account_id, name, kind, active, created_at, updated_at
FROM world.routes
WHERE id = $1
FOR UPDATE
`

// GetRouteForUpdate bloquea la fila (SELECT FOR UPDATE) para patch/delete: la
// validación de titular y el reemplazo de legs se deciden bajo lock.
func (q *Queries) GetRouteForUpdate(ctx context.Context, id uuid.UUID) (WorldRoute, error) {
	row := q.db.QueryRow(ctx, getRouteForUpdate, id)
	var i WorldRoute
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Name,
		&i.Kind,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :one

INSERT INTO world.routes (id, owner_account_id, name, kind)
VALUES ($1, $2, $3, $4::world.route_kind)
RETURNING id, owner_account_id, name, kind, active, created_at, updated_at
`

type InsertRouteParams struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	Name           string
	Kind           WorldRouteKind
}

// ─── Escritura ────────────────────────────────────────────────────────────────
// InsertRoute crea la definición de ruta (activa por defecto). Los legs se
// insertan aparte, en la MISMA transacción, tras validar su contigüidad.
func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (WorldRoute, error) {
	row := q.db.QueryRow(ctx, insertRoute,
		arg.ID,
		arg.OwnerAccountID,
		arg.Name,
		arg.Kind,
	)
	var i WorldRoute
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Name,
		&i.Kind,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRouteLeg = `-- name: InsertRouteLeg :exec
INSERT INTO world.route_legs (route_id, leg_index, link_id)
VALUES ($1, $2, $3)
`

type InsertRouteLegParams struct {
	RouteID  uuid.UUID
	LegIndex int32
	LinkID   uuid.UUID
}

// InsertRouteLeg añade un tramo (enlace) a una ruta en su posición ordenada.
func (q *Queries) InsertRouteLeg(ctx context.Context, arg InsertRouteLegParams) error {
	_, err := q.db.Exec(ctx, insertRouteLeg, arg.RouteID, arg.LegIndex, arg.LinkID)
	return err
}

const listRouteLegsByRoutes = `-- name: ListRouteLegsByRoutes :many
SELECT route_id, leg_index, link_id
FROM world.route_legs
WHERE route_id = ANY($1::uuid[])
ORDER BY route_id, leg_index
`

// ListRouteLegsByRoutes devuelve los legs (enlaces ordenados) de un conjunto de
// rutas, en orden estable por ruta y posición.
func (q *Queries) ListRouteLegsByRoutes(ctx context.Context, routeIds []uuid.UUID) ([]WorldRouteLeg, error) {
	rows, err := q.db.Query(ctx, listRouteLegsByRoutes, routeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldRouteLeg
	for rows.Next() {
		var i WorldRouteLeg
		if err := rows.Scan(&i.RouteID, &i.LegIndex, &i.LinkID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many


SELECT id, owner_account_id, name, kind, active, created_at, updated_at
FROM world.routes
WHERE owner_account_id = $1
  AND ($2::world.route_kind IS NULL OR kind = $2::world.route_kind)
  AND ($3::boolean IS NULL OR active = $3::boolean)
  AND ($4::uuid IS NULL OR id > $4::uuid)
ORDER BY id
LIMIT $5
`

type ListRoutesParams struct {
	OwnerAccountID uuid.UUID
	Kind           NullWorldRouteKind
	Active         pgtype.Bool
	AfterID        *uuid.UUID
	PageLimit      int32
}

// =============================================================================
// Imperio Industrial — queries de rutas propietarias del Logistics Service.
//
// Las rutas (world.routes + world.route_legs, GDD 7.2) son la definición de una
// línea fija u orden bajo demanda como secuencia CONTIGUA de enlaces. Son el
// ÚNICO estado que escribe el Logistics Service: PLANIFICACIÓN, no tránsito
// (ADR-006). El motor de tránsito de internal/world consume estas rutas al
// despachar vehículos; ambos contextos NO se importan (frontera de código Go).
//
// La autorización es por propiedad (owner_account_id): un listado/detalle/patch/
// delete sobre una ruta ajena es 403. El borrado de una ruta cae en cascada
// sobre sus legs (ON DELETE CASCADE del esquema 0003).
// =============================================================================
// ─── Lectura ──────────────────────────────────────────────────────────────────
// ListRoutes devuelve las rutas de un titular (SOLO propias) con filtros
// opcionales por tipo y estado activo, y paginación keyset por id. Los legs se
// resuelven aparte (ListRouteLegsByRoutes) por los ids de la página.
func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]WorldRoute, error) {
	rows, err := q.db.Query(ctx, listRoutes,
		arg.OwnerAccountID,
		arg.Kind,
		arg.Active,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldRoute
	for rows.Next() {
		var i WorldRoute
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.Name,
			&i.Kind,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE world.routes
   SET name   = COALESCE($1, name),
       active = COALESCE($2, active),
       updated_at = now()
 WHERE id = $3
RETURNING id, owner_account_id, name, kind, active, created_at, updated_at
`

type UpdateRouteParams struct {
	Name   *string
	Active pgtype.Bool
	ID     uuid.UUID
}

// UpdateRoute aplica un patch parcial de name/active (COALESCE conserva lo no
// enviado) y toca updated_at. El reemplazo de legs, si lo hay, va aparte en la
// misma transacción (DeleteRouteLegs + InsertRouteLeg).
func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (WorldRoute, error) {
	row := q.db.QueryRow(ctx, updateRoute, arg.Name, arg.Active, arg.ID)
	var i WorldRoute
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Name,
		&i.Kind,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
