// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buildings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const buildingFootprintOverlaps = `-- name: BuildingFootprintOverlaps :one
SELECT EXISTS (
    SELECT 1 FROM world.buildings
    WHERE ST_Intersects(footprint, ST_SetSRID(ST_GeomFromGeoJSON($1::text), 0))
)::boolean AS overlaps
`

// BuildingFootprintOverlaps comprueba la regla (c): el footprint NO se solapa
// (ST_Intersects) con el de ningún edificio existente.
func (q *Queries) BuildingFootprintOverlaps(ctx context.Context, footprintGeojson string) (bool, error) {
	row := q.db.QueryRow(ctx, buildingFootprintOverlaps, footprintGeojson)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const footprintWithinParcel = `-- name: FootprintWithinParcel :one
SELECT ST_Within(ST_SetSRID(ST_GeomFromGeoJSON($1::text), 0), parcel)::boolean AS within
FROM world.land_concessions
WHERE id = $2
`

type FootprintWithinParcelParams struct {
	FootprintGeojson string
	ID               uuid.UUID
}

// FootprintWithinParcel comprueba la regla (b): el footprint cae DENTRO de la
// parcela de la concesión (ST_Within).
func (q *Queries) FootprintWithinParcel(ctx context.Context, arg FootprintWithinParcelParams) (bool, error) {
	row := q.db.QueryRow(ctx, footprintWithinParcel, arg.FootprintGeojson, arg.ID)
	var within bool
	err := row.Scan(&within)
	return within, err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, owner_account_id, region_id, concession_id, building_type_id,
       ST_AsGeoJSON(footprint)::text AS footprint,
       level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
FROM world.buildings
WHERE id = $1
`

type GetBuildingRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// GetBuilding devuelve un edificio por id (la autorización por dueño la aplica
// la capa de servicio).
func (q *Queries) GetBuilding(ctx context.Context, id uuid.UUID) (GetBuildingRow, error) {
	row := q.db.QueryRow(ctx, getBuilding, id)
	var i GetBuildingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
		&i.Footprint,
		&i.Level,
		&i.Status,
		&i.ActiveRecipeID,
		&i.ConditionPct,
		&i.FuelStock,
		&i.CreatedAt,
		&i.UpdatedAtSim,
	)
	return i, err
}

const getBuildingForUpdate = `-- name: GetBuildingForUpdate :one
SELECT id, owner_account_id, region_id, concession_id, building_type_id,
       ST_AsGeoJSON(footprint)::text AS footprint,
       level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
FROM world.buildings
WHERE id = $1
FOR UPDATE
`

type GetBuildingForUpdateRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// GetBuildingForUpdate bloquea la fila (SELECT FOR UPDATE) para configuración y
// mejora: las validaciones y el cobro se deciden bajo lock.
func (q *Queries) GetBuildingForUpdate(ctx context.Context, id uuid.UUID) (GetBuildingForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBuildingForUpdate, id)
	var i GetBuildingForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
		&i.Footprint,
		&i.Level,
		&i.Status,
		&i.ActiveRecipeID,
		&i.ConditionPct,
		&i.FuelStock,
		&i.CreatedAt,
		&i.UpdatedAtSim,
	)
	return i, err
}

const getBuildingType = `-- name: GetBuildingType :one

SELECT id, code, name, footprint_cells, max_level, base_storage,
       placement_rules, level_curve, build_cost, maintenance_cost
FROM world.building_types
WHERE id = $1
`

type GetBuildingTypeRow struct {
	ID              uuid.UUID
	Code            string
	Name            string
	FootprintCells  int32
	MaxLevel        int32
	BaseStorage     int64
	PlacementRules  []byte
	LevelCurve      []byte
	BuildCost       int64
	MaintenanceCost int64
}

// ─── Tipos y recetas (validación) ─────────────────────────────────────────────
// GetBuildingType devuelve el tipo de edificio (coste, reglas de emplazamiento,
// curva de niveles y nivel máximo) para construir/mejorar; ErrNoRows si no
// existe.
func (q *Queries) GetBuildingType(ctx context.Context, id uuid.UUID) (GetBuildingTypeRow, error) {
	row := q.db.QueryRow(ctx, getBuildingType, id)
	var i GetBuildingTypeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.FootprintCells,
		&i.MaxLevel,
		&i.BaseStorage,
		&i.PlacementRules,
		&i.LevelCurve,
		&i.BuildCost,
		&i.MaintenanceCost,
	)
	return i, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, building_type_id, code, name, batch_sim_seconds,
       min_city_level, changeover_seconds
FROM world.recipes
WHERE id = $1
`

type GetRecipeRow struct {
	ID                uuid.UUID
	BuildingTypeID    uuid.UUID
	Code              string
	Name              string
	BatchSimSeconds   int64
	MinCityLevel      int32
	ChangeoverSeconds int64
}

// GetRecipe devuelve una receta (para validar que pertenece al tipo del
// edificio y su min_city_level); ErrNoRows si no existe.
func (q *Queries) GetRecipe(ctx context.Context, id uuid.UUID) (GetRecipeRow, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i GetRecipeRow
	err := row.Scan(
		&i.ID,
		&i.BuildingTypeID,
		&i.Code,
		&i.Name,
		&i.BatchSimSeconds,
		&i.MinCityLevel,
		&i.ChangeoverSeconds,
	)
	return i, err
}

const insertBuilding = `-- name: InsertBuilding :one

INSERT INTO world.buildings (
    id, owner_account_id, region_id, concession_id, building_type_id,
    footprint, level, status, condition_pct, fuel_stock, updated_at_sim)
VALUES (
    $1, $2, $3,
    $4, $5,
    ST_SetSRID(ST_GeomFromGeoJSON($6::text), 0),
    1, 'under_construction', 100, 0, $7)
RETURNING id, owner_account_id, region_id, concession_id, building_type_id,
          ST_AsGeoJSON(footprint)::text AS footprint,
          level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
`

type InsertBuildingParams struct {
	ID               uuid.UUID
	OwnerAccountID   uuid.UUID
	RegionID         uuid.UUID
	ConcessionID     uuid.UUID
	BuildingTypeID   uuid.UUID
	FootprintGeojson string
	UpdatedAtSim     int64
}

type InsertBuildingRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// ─── Construcción ─────────────────────────────────────────────────────────────
// InsertBuilding crea el edificio under_construction (level 1, condition 100,
// sin combustible ni receta). El coste ya se asentó al sink en la misma tx.
// updated_at_sim es la marca de creación que el motor usa para completar la
// construcción tras II_BUILD_SIM_SECONDS.
func (q *Queries) InsertBuilding(ctx context.Context, arg InsertBuildingParams) (InsertBuildingRow, error) {
	row := q.db.QueryRow(ctx, insertBuilding,
		arg.ID,
		arg.OwnerAccountID,
		arg.RegionID,
		arg.ConcessionID,
		arg.BuildingTypeID,
		arg.FootprintGeojson,
		arg.UpdatedAtSim,
	)
	var i InsertBuildingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
		&i.Footprint,
		&i.Level,
		&i.Status,
		&i.ActiveRecipeID,
		&i.ConditionPct,
		&i.FuelStock,
		&i.CreatedAt,
		&i.UpdatedAtSim,
	)
	return i, err
}

const insertNetworkNode = `-- name: InsertNetworkNode :one
INSERT INTO world.network_nodes (id, kind, region_id, building_id, location)
VALUES (
    $1, $2::world.node_kind, $3, $4,
    ST_Centroid(ST_SetSRID(ST_GeomFromGeoJSON($5::text), 0)))
RETURNING id
`

type InsertNetworkNodeParams struct {
	ID               uuid.UUID
	Kind             WorldNodeKind
	RegionID         uuid.UUID
	BuildingID       *uuid.UUID
	FootprintGeojson string
}

// InsertNetworkNode crea el nodo del grafo logístico ligado al edificio, en el
// centroide del footprint. kind lo deriva la aplicación (mina→mine, resto→
// factory).
func (q *Queries) InsertNetworkNode(ctx context.Context, arg InsertNetworkNodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertNetworkNode,
		arg.ID,
		arg.Kind,
		arg.RegionID,
		arg.BuildingID,
		arg.FootprintGeojson,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRoadSpurLink = `-- name: InsertRoadSpurLink :one
INSERT INTO world.network_links
       (id, mode, from_node_id, to_node_id, path, length_m, capacity_per_hour, base_speed_kmh)
SELECT $1, 'road'::world.link_mode, f.id, t.id,
       ST_MakeLine(f.location, t.location),
       GREATEST(1, round(ST_Distance(f.location, t.location)))::int,
       $2::int, $3::int
FROM world.network_nodes f, world.network_nodes t
WHERE f.id = $4 AND t.id = $5
RETURNING id, length_m
`

type InsertRoadSpurLinkParams struct {
	ID              uuid.UUID
	CapacityPerHour int32
	BaseSpeedKmh    int32
	FromNodeID      uuid.UUID
	ToNodeID        uuid.UUID
}

type InsertRoadSpurLinkRow struct {
	ID      uuid.UUID
	LengthM int32
}

// InsertRoadSpurLink crea UN enlace road dirigido from→to con el trazado recto
// entre las ubicaciones de ambos nodos y su longitud euclídea (metros de mundo,
// SRID 0 planar, ADR-019). El grafo es dirigido: el ramal bidireccional son dos
// llamadas, una por sentido.
func (q *Queries) InsertRoadSpurLink(ctx context.Context, arg InsertRoadSpurLinkParams) (InsertRoadSpurLinkRow, error) {
	row := q.db.QueryRow(ctx, insertRoadSpurLink,
		arg.ID,
		arg.CapacityPerHour,
		arg.BaseSpeedKmh,
		arg.FromNodeID,
		arg.ToNodeID,
	)
	var i InsertRoadSpurLinkRow
	err := row.Scan(&i.ID, &i.LengthM)
	return i, err
}

const insertRoadSpurSegment = `-- name: InsertRoadSpurSegment :exec
INSERT INTO world.link_segments (id, link_id, region_id, seq, portion, length_m, congestion_ema)
SELECT $1, l.id, $2, 1, l.path, l.length_m, 1.0
FROM world.network_links l
WHERE l.id = $3
`

type InsertRoadSpurSegmentParams struct {
	ID       uuid.UUID
	RegionID uuid.UUID
	LinkID   uuid.UUID
}

// InsertRoadSpurSegment crea el ÚNICO segmento (seq 1) del ramal, con la
// geometría y longitud del propio enlace y congestión fluida (EMA 1.0). El ramal
// es intra-región: un solo segmento, el de la región del edificio.
func (q *Queries) InsertRoadSpurSegment(ctx context.Context, arg InsertRoadSpurSegmentParams) error {
	_, err := q.db.Exec(ctx, insertRoadSpurSegment, arg.ID, arg.RegionID, arg.LinkID)
	return err
}

const listBuildingInventory = `-- name: ListBuildingInventory :many

SELECT building_id, product_id, quantity, updated_at_sim
FROM world.building_inventories
WHERE building_id = $1
ORDER BY product_id
`

// ─── Inventario físico ────────────────────────────────────────────────────────
// ListBuildingInventory devuelve el inventario FÍSICO del edificio por producto
// (vista física; la partición libre/reservado vive en el ledger).
func (q *Queries) ListBuildingInventory(ctx context.Context, buildingID uuid.UUID) ([]WorldBuildingInventory, error) {
	rows, err := q.db.Query(ctx, listBuildingInventory, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldBuildingInventory
	for rows.Next() {
		var i WorldBuildingInventory
		if err := rows.Scan(
			&i.BuildingID,
			&i.ProductID,
			&i.Quantity,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildings = `-- name: ListBuildings :many


SELECT id, owner_account_id, region_id, concession_id, building_type_id,
       ST_AsGeoJSON(footprint)::text AS footprint,
       level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
FROM world.buildings
WHERE owner_account_id = $1
  AND ($2::uuid IS NULL OR region_id = $2::uuid)
  AND ($3::world.building_status IS NULL OR status = $3::world.building_status)
  AND ($4::uuid IS NULL OR building_type_id = $4::uuid)
  AND ($5::uuid IS NULL OR id > $5::uuid)
ORDER BY id
LIMIT $6
`

type ListBuildingsParams struct {
	OwnerAccountID uuid.UUID
	RegionID       *uuid.UUID
	Status         NullWorldBuildingStatus
	BuildingTypeID *uuid.UUID
	AfterID        *uuid.UUID
	PageLimit      int32
}

type ListBuildingsRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// =============================================================================
// Imperio Industrial — queries sqlc del subpaquete world/buildings (ADR-020).
// Construcción y configuración de instalaciones (GDD 6/11): alta de edificio
// (under_construction) con su nodo del grafo logístico, validación de
// emplazamiento server-side, cambio de receta / mantenimiento, mejora de nivel
// e inventario físico. Es el lado de ESCRITURA del contexto world para los
// edificios: cada operación que mueve valor (build_cost, upgrade_cost) corre en
// una transacción SERIALIZABLE con outbox.Emit en la misma tx y asienta como
// SINK en ledger.* vía las queries de soporte de land.sql (COMPARTIDAS: la
// frontera entre subpaquetes es de código Go, no de fichero SQL).
//
// Geometrías (footprint/parcel): SRID 0 planar, metros de mundo (ADR-019). La
// ENTRADA (footprint) llega como GeoJSON y se proyecta con
// ST_SetSRID(ST_GeomFromGeoJSON(...), 0); la SALIDA con ST_AsGeoJSON(...)::text.
// El nodo se ubica en el centroide del footprint (ST_Centroid).
// =============================================================================
// ─── Edificios: lectura ───────────────────────────────────────────────────────
// ListBuildings devuelve los edificios de un dueño (SOLO propios) con filtros
// opcionales por región, estado y tipo, y paginación keyset por id.
func (q *Queries) ListBuildings(ctx context.Context, arg ListBuildingsParams) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings,
		arg.OwnerAccountID,
		arg.RegionID,
		arg.Status,
		arg.BuildingTypeID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingsRow
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.RegionID,
			&i.ConcessionID,
			&i.BuildingTypeID,
			&i.Footprint,
			&i.Level,
			&i.Status,
			&i.ActiveRecipeID,
			&i.ConditionPct,
			&i.FuelStock,
			&i.CreatedAt,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConcessionForBuilding = `-- name: LockConcessionForBuilding :one

SELECT id, region_id, holder_account_id, status
FROM world.land_concessions
WHERE id = $1
FOR UPDATE
`

type LockConcessionForBuildingRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Status          WorldConcessionStatus
}

// ─── Emplazamiento (validación server-side, PLACEMENT_INVALID) ────────────────
// LockConcessionForBuilding bloquea la concesión de destino y devuelve su
// región, titular y estado (reglas (a) propiedad + status active). ErrNoRows si
// la concesión no existe.
func (q *Queries) LockConcessionForBuilding(ctx context.Context, id uuid.UUID) (LockConcessionForBuildingRow, error) {
	row := q.db.QueryRow(ctx, lockConcessionForBuilding, id)
	var i LockConcessionForBuildingRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Status,
	)
	return i, err
}

const nearestCityLevelInRegion = `-- name: NearestCityLevelInRegion :one

SELECT c.level
FROM world.cities c
WHERE c.region_id = $1
ORDER BY c.location <-> (SELECT ST_Centroid(b.footprint) FROM world.buildings b WHERE b.id = $2)
LIMIT 1
`

type NearestCityLevelInRegionParams struct {
	RegionID   uuid.UUID
	BuildingID uuid.UUID
}

// ─── Configuración y mejora ───────────────────────────────────────────────────
// NearestCityLevelInRegion devuelve el nivel de la ciudad más cercana al
// edificio dentro de su región (cualificación laboral de la receta, GDD 5.7);
// ErrNoRows si la región no tiene ciudades.
func (q *Queries) NearestCityLevelInRegion(ctx context.Context, arg NearestCityLevelInRegionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nearestCityLevelInRegion, arg.RegionID, arg.BuildingID)
	var level int32
	err := row.Scan(&level)
	return level, err
}

const nearestRoadNodeInRegion = `-- name: NearestRoadNodeInRegion :one
SELECT n.id
FROM world.network_nodes n
WHERE n.region_id = $1
  AND n.id <> $2
  AND EXISTS (
      SELECT 1 FROM world.network_links l
       WHERE l.mode = 'road' AND (l.from_node_id = n.id OR l.to_node_id = n.id))
ORDER BY n.location <-> (SELECT location FROM world.network_nodes WHERE id = $2)
LIMIT 1
`

type NearestRoadNodeInRegionParams struct {
	RegionID uuid.UUID
	NodeID   uuid.UUID
}

// NearestRoadNodeInRegion devuelve el nodo de la MISMA región ya incidente a
// algún enlace road más cercano al nodo dado: el punto de enganche del ramal de
// última milla del edificio nuevo (GDD 7.2, red vial como infraestructura del
// mundo). ErrNoRows si la región todavía no tiene red vial.
func (q *Queries) NearestRoadNodeInRegion(ctx context.Context, arg NearestRoadNodeInRegionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, nearestRoadNodeInRegion, arg.RegionID, arg.NodeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const nodeKindPresentInRegion = `-- name: NodeKindPresentInRegion :one
SELECT EXISTS (
    SELECT 1 FROM world.network_nodes
    WHERE region_id = $1
      AND kind = $2::world.node_kind
)::boolean AS present
`

type NodeKindPresentInRegionParams struct {
	RegionID uuid.UUID
	NodeKind WorldNodeKind
}

// NodeKindPresentInRegion comprueba la regla placement_rules.requires_node_kind:
// existe un nodo del grafo logístico de ese kind en la región de la concesión.
func (q *Queries) NodeKindPresentInRegion(ctx context.Context, arg NodeKindPresentInRegionParams) (bool, error) {
	row := q.db.QueryRow(ctx, nodeKindPresentInRegion, arg.RegionID, arg.NodeKind)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const resourceNearby = `-- name: ResourceNearby :one
SELECT EXISTS (
    SELECT 1
    FROM world.resource_deposits d
    JOIN world.products p ON p.id = d.product_id
    WHERE p.code = $1
      AND d.remaining_amount > 0
      AND ST_DWithin(
            d.location,
            ST_Centroid(ST_SetSRID(ST_GeomFromGeoJSON($2::text), 0)),
            $3::float8)
)::boolean AS present
`

type ResourceNearbyParams struct {
	ProductCode      string
	FootprintGeojson string
	MaxDistanceM     float64
}

// ResourceNearby comprueba la regla placement_rules.near_resource: existe un
// yacimiento del producto (por code) con remaining > 0 dentro del radio
// (ST_DWithin) desde el centroide del footprint.
func (q *Queries) ResourceNearby(ctx context.Context, arg ResourceNearbyParams) (bool, error) {
	row := q.db.QueryRow(ctx, resourceNearby, arg.ProductCode, arg.FootprintGeojson, arg.MaxDistanceM)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const setBuildingLevel = `-- name: SetBuildingLevel :one
UPDATE world.buildings
   SET level = $1, updated_at_sim = $2
 WHERE id = $3
RETURNING id, owner_account_id, region_id, concession_id, building_type_id,
          ST_AsGeoJSON(footprint)::text AS footprint,
          level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
`

type SetBuildingLevelParams struct {
	Level        int32
	UpdatedAtSim int64
	ID           uuid.UUID
}

type SetBuildingLevelRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// SetBuildingLevel sube el nivel del edificio (mejora). El coste ya se asentó al
// sink en la misma tx.
func (q *Queries) SetBuildingLevel(ctx context.Context, arg SetBuildingLevelParams) (SetBuildingLevelRow, error) {
	row := q.db.QueryRow(ctx, setBuildingLevel, arg.Level, arg.UpdatedAtSim, arg.ID)
	var i SetBuildingLevelRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
		&i.Footprint,
		&i.Level,
		&i.Status,
		&i.ActiveRecipeID,
		&i.ConditionPct,
		&i.FuelStock,
		&i.CreatedAt,
		&i.UpdatedAtSim,
	)
	return i, err
}

const setBuildingRecipe = `-- name: SetBuildingRecipe :one
UPDATE world.buildings
   SET active_recipe_id = $1, updated_at_sim = $2
 WHERE id = $3
RETURNING id, owner_account_id, region_id, concession_id, building_type_id,
          ST_AsGeoJSON(footprint)::text AS footprint,
          level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
`

type SetBuildingRecipeParams struct {
	ActiveRecipeID *uuid.UUID
	UpdatedAtSim   int64
	ID             uuid.UUID
}

type SetBuildingRecipeRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// SetBuildingRecipe fija (o detiene, con NULL) la receta activa del edificio.
func (q *Queries) SetBuildingRecipe(ctx context.Context, arg SetBuildingRecipeParams) (SetBuildingRecipeRow, error) {
	row := q.db.QueryRow(ctx, setBuildingRecipe, arg.ActiveRecipeID, arg.UpdatedAtSim, arg.ID)
	var i SetBuildingRecipeRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
		&i.Footprint,
		&i.Level,
		&i.Status,
		&i.ActiveRecipeID,
		&i.ConditionPct,
		&i.FuelStock,
		&i.CreatedAt,
		&i.UpdatedAtSim,
	)
	return i, err
}

const setBuildingStatus = `-- name: SetBuildingStatus :one
UPDATE world.buildings
   SET status = $1::world.building_status, updated_at_sim = $2
 WHERE id = $3
RETURNING id, owner_account_id, region_id, concession_id, building_type_id,
          ST_AsGeoJSON(footprint)::text AS footprint,
          level, status, active_recipe_id, condition_pct, fuel_stock, created_at, updated_at_sim
`

type SetBuildingStatusParams struct {
	Status       WorldBuildingStatus
	UpdatedAtSim int64
	ID           uuid.UUID
}

type SetBuildingStatusRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
	Footprint      string
	Level          int32
	Status         WorldBuildingStatus
	ActiveRecipeID *uuid.UUID
	ConditionPct   int32
	FuelStock      int64
	CreatedAt      time.Time
	UpdatedAtSim   int64
}

// SetBuildingStatus cambia el estado del edificio (p. ej. in_maintenance).
func (q *Queries) SetBuildingStatus(ctx context.Context, arg SetBuildingStatusParams) (SetBuildingStatusRow, error) {
	row := q.db.QueryRow(ctx, setBuildingStatus, arg.Status, arg.UpdatedAtSim, arg.ID)
	var i SetBuildingStatusRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
		&i.Footprint,
		&i.Level,
		&i.Status,
		&i.ActiveRecipeID,
		&i.ConditionPct,
		&i.FuelStock,
		&i.CreatedAt,
		&i.UpdatedAtSim,
	)
	return i, err
}
