// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cityExists = `-- name: CityExists :one
SELECT EXISTS (SELECT 1 FROM world.cities WHERE id = $1)
`

// CityExists indica si una ciudad existe (para distinguir 404 de "sin demanda"
// en el endpoint de curva de demanda).
func (q *Queries) CityExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, cityExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCity = `-- name: GetCity :one
SELECT id, region_id, account_id, name,
       ST_AsGeoJSON(location)::text AS location,
       level, population, supply_index::float8 AS supply_index,
       influence_radius_m, base_salary
FROM world.cities
WHERE id = $1
`

type GetCityRow struct {
	ID               uuid.UUID
	RegionID         uuid.UUID
	AccountID        uuid.UUID
	Name             string
	Location         string
	Level            int32
	Population       int64
	SupplyIndex      float64
	InfluenceRadiusM int32
	BaseSalary       int64
}

// GetCity devuelve una ciudad por id.
func (q *Queries) GetCity(ctx context.Context, id uuid.UUID) (GetCityRow, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i GetCityRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.AccountID,
		&i.Name,
		&i.Location,
		&i.Level,
		&i.Population,
		&i.SupplyIndex,
		&i.InfluenceRadiusM,
		&i.BaseSalary,
	)
	return i, err
}

const getRegion = `-- name: GetRegion :one
SELECT id, name, grid_x, grid_y,
       ST_AsGeoJSON(bounds)::text AS bounds,
       biome, tax_rate_bp, customs_rate_bp, canon_base, opened_at_sim
FROM world.regions
WHERE id = $1
`

type GetRegionRow struct {
	ID            uuid.UUID
	Name          string
	GridX         int32
	GridY         int32
	Bounds        string
	Biome         WorldBiome
	TaxRateBp     int32
	CustomsRateBp int32
	CanonBase     int64
	OpenedAtSim   int64
}

// GetRegion devuelve una región por id.
func (q *Queries) GetRegion(ctx context.Context, id uuid.UUID) (GetRegionRow, error) {
	row := q.db.QueryRow(ctx, getRegion, id)
	var i GetRegionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GridX,
		&i.GridY,
		&i.Bounds,
		&i.Biome,
		&i.TaxRateBp,
		&i.CustomsRateBp,
		&i.CanonBase,
		&i.OpenedAtSim,
	)
	return i, err
}

const listBuildingTypes = `-- name: ListBuildingTypes :many

SELECT id, code, name, footprint_cells, max_level, base_storage,
       placement_rules, level_curve, build_cost, maintenance_cost
FROM world.building_types
WHERE ($1::uuid IS NULL OR id > $1::uuid)
ORDER BY id
LIMIT $2
`

type ListBuildingTypesParams struct {
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListBuildingTypesRow struct {
	ID              uuid.UUID
	Code            string
	Name            string
	FootprintCells  int32
	MaxLevel        int32
	BaseStorage     int64
	PlacementRules  []byte
	LevelCurve      []byte
	BuildCost       int64
	MaintenanceCost int64
}

// ─── Tipos de edificio ───────────────────────────────────────────────────────
// ListBuildingTypes devuelve el catálogo de tipos de edificio con sus reglas de
// emplazamiento y curva de niveles (JSONB → bytes crudos que el handler embebe).
func (q *Queries) ListBuildingTypes(ctx context.Context, arg ListBuildingTypesParams) ([]ListBuildingTypesRow, error) {
	rows, err := q.db.Query(ctx, listBuildingTypes, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingTypesRow
	for rows.Next() {
		var i ListBuildingTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.FootprintCells,
			&i.MaxLevel,
			&i.BaseStorage,
			&i.PlacementRules,
			&i.LevelCurve,
			&i.BuildCost,
			&i.MaintenanceCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many

SELECT id, region_id, account_id, name,
       ST_AsGeoJSON(location)::text AS location,
       level, population, supply_index::float8 AS supply_index,
       influence_radius_m, base_salary
FROM world.cities
WHERE ($1::uuid IS NULL OR region_id = $1::uuid)
  AND ($2::int IS NULL OR level >= $2::int)
  AND ($3::uuid IS NULL OR id > $3::uuid)
ORDER BY id
LIMIT $4
`

type ListCitiesParams struct {
	RegionID  *uuid.UUID
	MinLevel  *int32
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListCitiesRow struct {
	ID               uuid.UUID
	RegionID         uuid.UUID
	AccountID        uuid.UUID
	Name             string
	Location         string
	Level            int32
	Population       int64
	SupplyIndex      float64
	InfluenceRadiusM int32
	BaseSalary       int64
}

// ─── Ciudades ────────────────────────────────────────────────────────────────
// ListCities devuelve las ciudades con filtros opcionales por región y nivel
// mínimo, y paginación keyset por id. supply_index es NUMERIC → float8 (número
// del contrato, no dinero). location sale como GeoJSON plano.
func (q *Queries) ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities,
		arg.RegionID,
		arg.MinLevel,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCitiesRow
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.AccountID,
			&i.Name,
			&i.Location,
			&i.Level,
			&i.Population,
			&i.SupplyIndex,
			&i.InfluenceRadiusM,
			&i.BaseSalary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCityDemand = `-- name: ListCityDemand :many
SELECT city_id, product_id, d0_per_sim_day,
       saturation_factor::float8 AS saturation_factor,
       current_price, unlocked_at_level, updated_at_sim
FROM world.city_demand
WHERE city_id = $1
  AND ($2::uuid IS NULL OR product_id = $2::uuid)
ORDER BY product_id
`

type ListCityDemandParams struct {
	CityID    uuid.UUID
	ProductID *uuid.UUID
}

type ListCityDemandRow struct {
	CityID           uuid.UUID
	ProductID        uuid.UUID
	D0PerSimDay      int64
	SaturationFactor float64
	CurrentPrice     int64
	UnlockedAtLevel  int32
	UpdatedAtSim     int64
}

// ListCityDemand devuelve la curva de demanda vigente de una ciudad, con filtro
// opcional por producto, ordenada por producto. saturation_factor es NUMERIC →
// float8 (número del contrato). Sin paginación: el contrato no la define aquí.
func (q *Queries) ListCityDemand(ctx context.Context, arg ListCityDemandParams) ([]ListCityDemandRow, error) {
	rows, err := q.db.Query(ctx, listCityDemand, arg.CityID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCityDemandRow
	for rows.Next() {
		var i ListCityDemandRow
		if err := rows.Scan(
			&i.CityID,
			&i.ProductID,
			&i.D0PerSimDay,
			&i.SaturationFactor,
			&i.CurrentPrice,
			&i.UnlockedAtLevel,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many

SELECT id, code, name, class, unit_volume, base_price, price_floor, price_ceiling, is_fuel
FROM world.products
WHERE ($1::world.product_class IS NULL OR class = $1::world.product_class)
  AND ($2::boolean IS NULL OR is_fuel = $2::boolean)
  AND ($3::uuid IS NULL OR id > $3::uuid)
ORDER BY id
LIMIT $4
`

type ListProductsParams struct {
	Class     NullWorldProductClass
	IsFuel    pgtype.Bool
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListProductsRow struct {
	ID           uuid.UUID
	Code         string
	Name         string
	Class        WorldProductClass
	UnitVolume   int32
	BasePrice    int64
	PriceFloor   int64
	PriceCeiling int64
	IsFuel       bool
}

// ─── Productos ───────────────────────────────────────────────────────────────
// ListProducts devuelve el catálogo de productos con filtros opcionales por
// clase y por si es combustible, y paginación keyset por id.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Class,
		arg.IsFuel,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Class,
			&i.UnitVolume,
			&i.BasePrice,
			&i.PriceFloor,
			&i.PriceCeiling,
			&i.IsFuel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT recipe_id, product_id, role, quantity
FROM world.recipe_ingredients
WHERE recipe_id = ANY($1::uuid[])
ORDER BY recipe_id, role, product_id
`

// ListRecipeIngredients devuelve los ingredientes (insumos y productos) de un
// conjunto de recetas, en orden estable por receta, rol y producto.
func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeIds []uuid.UUID) ([]WorldRecipeIngredient, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldRecipeIngredient
	for rows.Next() {
		var i WorldRecipeIngredient
		if err := rows.Scan(
			&i.RecipeID,
			&i.ProductID,
			&i.Role,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many

SELECT r.id, r.building_type_id, r.code, r.name, r.batch_sim_seconds,
       r.fuel_product_id, r.fuel_per_batch, r.workers_required,
       r.min_city_level, r.changeover_seconds
FROM world.recipes r
WHERE ($1::uuid IS NULL OR r.building_type_id = $1::uuid)
  AND ($2::uuid IS NULL OR EXISTS (
        SELECT 1 FROM world.recipe_ingredients ri
        WHERE ri.recipe_id = r.id AND ri.product_id = $2::uuid))
  AND ($3::uuid IS NULL OR r.id > $3::uuid)
ORDER BY r.id
LIMIT $4
`

type ListRecipesParams struct {
	BuildingTypeID *uuid.UUID
	ProductID      *uuid.UUID
	AfterID        *uuid.UUID
	PageLimit      int32
}

type ListRecipesRow struct {
	ID                uuid.UUID
	BuildingTypeID    uuid.UUID
	Code              string
	Name              string
	BatchSimSeconds   int64
	FuelProductID     *uuid.UUID
	FuelPerBatch      int64
	WorkersRequired   int32
	MinCityLevel      int32
	ChangeoverSeconds int64
}

// ─── Recetas ─────────────────────────────────────────────────────────────────
// ListRecipes devuelve las recetas con filtros opcionales por tipo de edificio
// y por producto que aparezca en sus ingredientes (cualquier rol). Los
// ingredientes se resuelven aparte (ListRecipeIngredients) por los ids de la
// página, para no duplicar filas de receta en el JOIN.
func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]ListRecipesRow, error) {
	rows, err := q.db.Query(ctx, listRecipes,
		arg.BuildingTypeID,
		arg.ProductID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesRow
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildingTypeID,
			&i.Code,
			&i.Name,
			&i.BatchSimSeconds,
			&i.FuelProductID,
			&i.FuelPerBatch,
			&i.WorkersRequired,
			&i.MinCityLevel,
			&i.ChangeoverSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many


SELECT id, name, grid_x, grid_y,
       ST_AsGeoJSON(bounds)::text AS bounds,
       biome, tax_rate_bp, customs_rate_bp, canon_base, opened_at_sim
FROM world.regions
WHERE ($1::world.biome IS NULL OR biome = $1::world.biome)
  AND ($2::uuid IS NULL OR id > $2::uuid)
ORDER BY id
LIMIT $3
`

type ListRegionsParams struct {
	Biome     NullWorldBiome
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListRegionsRow struct {
	ID            uuid.UUID
	Name          string
	GridX         int32
	GridY         int32
	Bounds        string
	Biome         WorldBiome
	TaxRateBp     int32
	CustomsRateBp int32
	CanonBase     int64
	OpenedAtSim   int64
}

// =============================================================================
// Imperio Industrial — queries sqlc del subpaquete world/catalog (ADR-020).
// Lectura del mundo estático y de catálogos (contrato world/*): regiones,
// productos, tipos de edificio, recetas, yacimientos, ciudades y demanda. Es
// lectura pura y observable por cualquier corporación (sin filtro de propiedad).
//
// Geometrías (bounds/location/parcel): SRID 0 planar, metros de mundo
// (ADR-019). Se proyectan con ST_AsGeoJSON(...)::text — un objeto GeoJSON con
// coordenadas planas [x_m, y_m] que los handlers embeben tal cual en el schema
// GeoPolygon/GeoPoint del contrato (jamás lon/lat). Los NUMERIC del dominio de
// oferta (supply_index, saturation_factor) se proyectan a float8: son
// `type: number` del contrato, no dinero (dinero/stock siguen siendo int64).
//
// Paginación keyset por id (UUIDv7 ≈ orden de creación) con page_limit; la
// capa de servicio pide page_limit+1 para detectar la página siguiente.
// =============================================================================
// ─── Regiones ────────────────────────────────────────────────────────────────
// ListRegions devuelve las macro-regiones con filtro opcional por bioma y
// paginación keyset por id. bounds sale como GeoJSON plano (SRID 0).
func (q *Queries) ListRegions(ctx context.Context, arg ListRegionsParams) ([]ListRegionsRow, error) {
	rows, err := q.db.Query(ctx, listRegions, arg.Biome, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegionsRow
	for rows.Next() {
		var i ListRegionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GridX,
			&i.GridY,
			&i.Bounds,
			&i.Biome,
			&i.TaxRateBp,
			&i.CustomsRateBp,
			&i.CanonBase,
			&i.OpenedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceDeposits = `-- name: ListResourceDeposits :many

SELECT id, region_id, product_id,
       ST_AsGeoJSON(location)::text AS location,
       initial_amount, remaining_amount, renewable, regen_per_sim_day
FROM world.resource_deposits
WHERE ($1::uuid IS NULL OR region_id = $1::uuid)
  AND ($2::uuid IS NULL OR product_id = $2::uuid)
  AND (NOT $3::boolean OR remaining_amount > 0)
  AND ($4::uuid IS NULL OR id > $4::uuid)
ORDER BY id
LIMIT $5
`

type ListResourceDepositsParams struct {
	RegionID      *uuid.UUID
	ProductID     *uuid.UUID
	OnlyAvailable bool
	AfterID       *uuid.UUID
	PageLimit     int32
}

type ListResourceDepositsRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	ProductID       uuid.UUID
	Location        string
	InitialAmount   int64
	RemainingAmount int64
	Renewable       bool
	RegenPerSimDay  int64
}

// ─── Yacimientos ─────────────────────────────────────────────────────────────
// ListResourceDeposits devuelve los yacimientos con filtros opcionales por
// región y producto; only_available (default true en el contrato) recorta a los
// que aún tienen cantidad restante. location sale como GeoJSON plano.
func (q *Queries) ListResourceDeposits(ctx context.Context, arg ListResourceDepositsParams) ([]ListResourceDepositsRow, error) {
	rows, err := q.db.Query(ctx, listResourceDeposits,
		arg.RegionID,
		arg.ProductID,
		arg.OnlyAvailable,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceDepositsRow
	for rows.Next() {
		var i ListResourceDepositsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.ProductID,
			&i.Location,
			&i.InitialAmount,
			&i.RemainingAmount,
			&i.Renewable,
			&i.RegenPerSimDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
