// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enforcement.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const extendConcession = `-- name: ExtendConcession :exec
UPDATE world.land_concessions
   SET expires_at_sim = expires_at_sim + $1::bigint,
       status = 'active',
       grace_until_sim = NULL,
       updated_at = now()
 WHERE id = $2
`

type ExtendConcessionParams struct {
	ExtendSimSeconds int64
	ID               uuid.UUID
}

// ExtendConcession renueva: extiende el vencimiento un periodo, deja la concesión
// 'active' y limpia el marcador de gracia (canon vigente ya cobrado al sink).
func (q *Queries) ExtendConcession(ctx context.Context, arg ExtendConcessionParams) error {
	_, err := q.db.Exec(ctx, extendConcession, arg.ExtendSimSeconds, arg.ID)
	return err
}

const getBuildingNodeID = `-- name: GetBuildingNodeID :one
SELECT id
FROM world.network_nodes
WHERE building_id = $1
ORDER BY id
LIMIT 1
`

// GetBuildingNodeID devuelve el nodo logístico del edificio (origin_node_id de la
// retirada in situ). pgx.ErrNoRows si el edificio no tiene nodo.
func (q *Queries) GetBuildingNodeID(ctx context.Context, buildingID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBuildingNodeID, buildingID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listBuildingStockFree = `-- name: ListBuildingStockFree :many
SELECT product_id, warehouse_building_id, balance
FROM ledger.accounts
WHERE kind = 'stock_free'
  AND warehouse_building_id = $1
  AND balance > 0
ORDER BY product_id
`

type ListBuildingStockFreeRow struct {
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
	Balance             int64
}

// ListBuildingStockFree lista el stock LIBRE del edificio en el momento del
// embargo (cuentas stock_free del ledger por almacén). Es el stock que la
// liquidación del sistema publicará por CCRI (el embargo NO lo mueve aquí).
func (q *Queries) ListBuildingStockFree(ctx context.Context, warehouseBuildingID *uuid.UUID) ([]ListBuildingStockFreeRow, error) {
	rows, err := q.db.Query(ctx, listBuildingStockFree, warehouseBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingStockFreeRow
	for rows.Next() {
		var i ListBuildingStockFreeRow
		if err := rows.Scan(&i.ProductID, &i.WarehouseBuildingID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildingsDueMaintenance = `-- name: ListBuildingsDueMaintenance :many


SELECT id
FROM world.buildings
WHERE status IN ('operational', 'damaged')
  AND maintenance_paid_until_sim <= $1
ORDER BY id
LIMIT $2
`

type ListBuildingsDueMaintenanceParams struct {
	PaidBefore int64
	PageLimit  int32
}

// =============================================================================
// Imperio Industrial — queries sqlc del subpaquete world/enforcement (ADR-020).
// Incremento 6a: CASCADA DE INSOLVENCIA (GDD 5.9, 11.2). Motor de mantenimiento,
// canon, degradación y embargo. Es el lado de CONSECUENCIA FÍSICA del contexto
// world: cobra mantenimiento/canon (cash → sink, "cobra SOLO lo disponible",
// jamás deja la caja negativa), degrada y abandona edificios, y embarga (congela
// el edificio + revierte el suelo) publicando su stock por evento.
//
// La frontera de módulo es de código Go, no de esquema: estas queries leen y
// escriben world.* (buildings, vehicles, land_concessions, production_batches,
// network_nodes) y asientan en ledger.* como SINK (transacción maintenance/canon),
// exactamente como land/production. Los helpers de ledger (GetCashAccount,
// GetSinkAccount, InsertLedgerTransaction, InsertLedgerEntry) ya viven en
// land.sql/production.sql: se REUTILIZAN desde el paquete sqlcgen compartido.
//
// Cada barrido bloquea su entidad con FOR UPDATE SKIP LOCKED y decide en Go
// (varias instancias del motor pueden correr en paralelo sin pisarse).
// =============================================================================
// ═════════════════════════════════════════════════════════════════════════════
// (1) Mantenimiento de edificios (GDD 11.2: degradación por impago)
// ═════════════════════════════════════════════════════════════════════════════
// ListBuildingsDueMaintenance lista los edificios operativos/dañados con al menos
// un día-sim de mantenimiento vencido (paid_before = simNow - SimDay). El importe
// exacto y la degradación se deciden en Go tras bloquear cada edificio.
func (q *Queries) ListBuildingsDueMaintenance(ctx context.Context, arg ListBuildingsDueMaintenanceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBuildingsDueMaintenance, arg.PaidBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildingsOnConcessionForSeize = `-- name: ListBuildingsOnConcessionForSeize :many
SELECT id, owner_account_id, region_id, status
FROM world.buildings
WHERE concession_id = $1 AND status <> 'seized'
ORDER BY id
FOR UPDATE
`

type ListBuildingsOnConcessionForSeizeRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	Status         WorldBuildingStatus
}

// ListBuildingsOnConcessionForSeize bloquea (FOR UPDATE) los edificios aún no
// embargados sobre una concesión (los que el embargo debe congelar in situ).
func (q *Queries) ListBuildingsOnConcessionForSeize(ctx context.Context, concessionID uuid.UUID) ([]ListBuildingsOnConcessionForSeizeRow, error) {
	rows, err := q.db.Query(ctx, listBuildingsOnConcessionForSeize, concessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingsOnConcessionForSeizeRow
	for rows.Next() {
		var i ListBuildingsOnConcessionForSeizeRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.RegionID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConcessionsDueCanon = `-- name: ListConcessionsDueCanon :many

SELECT id
FROM world.land_concessions
WHERE status = 'active' AND expires_at_sim < $1
ORDER BY id
LIMIT $2
`

type ListConcessionsDueCanonParams struct {
	SimNow    int64
	PageLimit int32
}

// ═════════════════════════════════════════════════════════════════════════════
// (2) Canon de concesión (GDD 11.1/11.2: active → delinquent → grace → reverted)
// ═════════════════════════════════════════════════════════════════════════════
// ListConcessionsDueCanon lista las concesiones activas con el periodo vencido
// (candidatas a renovación/impago). Reutiliza ix_concessions_expiry.
func (q *Queries) ListConcessionsDueCanon(ctx context.Context, arg ListConcessionsDueCanonParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConcessionsDueCanon, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConcessionsInGrace = `-- name: ListConcessionsInGrace :many

SELECT id
FROM world.land_concessions
WHERE status = 'grace'
ORDER BY id
LIMIT $1
`

// ═════════════════════════════════════════════════════════════════════════════
// (3) Embargo / reclamo (GDD 11.2: congela el edificio + revierte el suelo)
// ═════════════════════════════════════════════════════════════════════════════
// ListConcessionsInGrace lista las concesiones marcadas para embargo (rama canon).
func (q *Queries) ListConcessionsInGrace(ctx context.Context, pageLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConcessionsInGrace, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConcessionsToEmbargoByAbandon = `-- name: ListConcessionsToEmbargoByAbandon :many
SELECT DISTINCT b.concession_id
FROM world.buildings b
JOIN world.land_concessions c ON c.id = b.concession_id
WHERE b.status = 'abandoned'
  AND b.maintenance_paid_until_sim <= $1
  AND c.status <> 'reverted'
ORDER BY b.concession_id
LIMIT $2
`

type ListConcessionsToEmbargoByAbandonParams struct {
	GraceBefore int64
	PageLimit   int32
}

// ListConcessionsToEmbargoByAbandon lista las concesiones (aún no revertidas) con
// algún edificio ABANDONADO cuyo periodo de gracia ya venció (rama mantenimiento;
// grace_before = simNow - II_SEIZE_GRACE_SIM_SECONDS). El marcador
// maintenance_paid_until_sim de un edificio abandonado es el instante del abandono.
func (q *Queries) ListConcessionsToEmbargoByAbandon(ctx context.Context, arg ListConcessionsToEmbargoByAbandonParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConcessionsToEmbargoByAbandon, arg.GraceBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var concession_id uuid.UUID
		if err := rows.Scan(&concession_id); err != nil {
			return nil, err
		}
		items = append(items, concession_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelinquentDueGrace = `-- name: ListDelinquentDueGrace :many
SELECT id
FROM world.land_concessions
WHERE status = 'delinquent'
  AND grace_until_sim IS NOT NULL
  AND grace_until_sim < $1
ORDER BY id
LIMIT $2
`

type ListDelinquentDueGraceParams struct {
	SimNow    *int64
	PageLimit int32
}

// ListDelinquentDueGrace lista las concesiones morosas cuyo periodo de gracia ya
// venció (delinquent → grace).
func (q *Queries) ListDelinquentDueGrace(ctx context.Context, arg ListDelinquentDueGraceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDelinquentDueGrace, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesDueMaintenance = `-- name: ListVehiclesDueMaintenance :many

SELECT id
FROM world.vehicles
WHERE maintenance_paid_until_sim <= $1
ORDER BY id
LIMIT $2
`

type ListVehiclesDueMaintenanceParams struct {
	PaidBefore int64
	PageLimit  int32
}

// ═════════════════════════════════════════════════════════════════════════════
// (1b) Mantenimiento de flota (opex; sin condición: solo drena caja)
// ═════════════════════════════════════════════════════════════════════════════
// ListVehiclesDueMaintenance lista los vehículos con al menos un día-sim de opex
// vencido (todos los estados: el opex se cobra se mueva o no el vehículo).
func (q *Queries) ListVehiclesDueMaintenance(ctx context.Context, arg ListVehiclesDueMaintenanceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listVehiclesDueMaintenance, arg.PaidBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuildingForMaintenance = `-- name: LockBuildingForMaintenance :one
SELECT b.id, b.owner_account_id, b.region_id, b.concession_id, b.status,
       b.condition_pct, b.maintenance_paid_until_sim, bt.maintenance_cost
FROM world.buildings b
JOIN world.building_types bt ON bt.id = b.building_type_id
WHERE b.id = $1
  AND b.status IN ('operational', 'damaged')
  AND b.maintenance_paid_until_sim <= $2
FOR UPDATE OF b SKIP LOCKED
`

type LockBuildingForMaintenanceParams struct {
	ID         uuid.UUID
	PaidBefore int64
}

type LockBuildingForMaintenanceRow struct {
	ID                      uuid.UUID
	OwnerAccountID          uuid.UUID
	RegionID                uuid.UUID
	ConcessionID            uuid.UUID
	Status                  WorldBuildingStatus
	ConditionPct            int32
	MaintenancePaidUntilSim int64
	MaintenanceCost         int64
}

// LockBuildingForMaintenance bloquea un edificio vencido (FOR UPDATE OF b SKIP
// LOCKED) con el coste de mantenimiento de su tipo. pgx.ErrNoRows si otra
// instancia lo tomó o ya no aplica.
func (q *Queries) LockBuildingForMaintenance(ctx context.Context, arg LockBuildingForMaintenanceParams) (LockBuildingForMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, lockBuildingForMaintenance, arg.ID, arg.PaidBefore)
	var i LockBuildingForMaintenanceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.Status,
		&i.ConditionPct,
		&i.MaintenancePaidUntilSim,
		&i.MaintenanceCost,
	)
	return i, err
}

const lockConcessionForCanon = `-- name: LockConcessionForCanon :one
SELECT id, region_id, holder_account_id, canon_amount, period_sim_days,
       expires_at_sim, status, grace_until_sim
FROM world.land_concessions
WHERE id = $1 AND status = 'active' AND expires_at_sim < $2
FOR UPDATE SKIP LOCKED
`

type LockConcessionForCanonParams struct {
	ID     uuid.UUID
	SimNow int64
}

type LockConcessionForCanonRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GraceUntilSim   *int64
}

// LockConcessionForCanon bloquea una concesión activa vencida con lo necesario
// para cobrar el canon y extender el periodo.
func (q *Queries) LockConcessionForCanon(ctx context.Context, arg LockConcessionForCanonParams) (LockConcessionForCanonRow, error) {
	row := q.db.QueryRow(ctx, lockConcessionForCanon, arg.ID, arg.SimNow)
	var i LockConcessionForCanonRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.CanonAmount,
		&i.PeriodSimDays,
		&i.ExpiresAtSim,
		&i.Status,
		&i.GraceUntilSim,
	)
	return i, err
}

const lockConcessionForEmbargo = `-- name: LockConcessionForEmbargo :one
SELECT id, region_id, holder_account_id, status
FROM world.land_concessions
WHERE id = $1 AND status <> 'reverted'
FOR UPDATE SKIP LOCKED
`

type LockConcessionForEmbargoRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Status          WorldConcessionStatus
}

// LockConcessionForEmbargo bloquea la concesión a embargar (idempotente: filtra
// las ya revertidas). pgx.ErrNoRows si ya está reverted o la tomó otra instancia.
func (q *Queries) LockConcessionForEmbargo(ctx context.Context, id uuid.UUID) (LockConcessionForEmbargoRow, error) {
	row := q.db.QueryRow(ctx, lockConcessionForEmbargo, id)
	var i LockConcessionForEmbargoRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Status,
	)
	return i, err
}

const lockConcessionForGrace = `-- name: LockConcessionForGrace :one
SELECT id
FROM world.land_concessions
WHERE id = $1 AND status = 'delinquent'
  AND grace_until_sim IS NOT NULL
  AND grace_until_sim < $2
FOR UPDATE SKIP LOCKED
`

type LockConcessionForGraceParams struct {
	ID     uuid.UUID
	SimNow *int64
}

// LockConcessionForGrace bloquea una concesión morosa con la gracia vencida.
func (q *Queries) LockConcessionForGrace(ctx context.Context, arg LockConcessionForGraceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockConcessionForGrace, arg.ID, arg.SimNow)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockVehicleForMaintenance = `-- name: LockVehicleForMaintenance :one
SELECT v.id, v.owner_account_id, v.maintenance_paid_until_sim, vt.operating_cost_per_day
FROM world.vehicles v
JOIN world.vehicle_types vt ON vt.id = v.vehicle_type_id
WHERE v.id = $1
  AND v.maintenance_paid_until_sim <= $2
FOR UPDATE OF v SKIP LOCKED
`

type LockVehicleForMaintenanceParams struct {
	ID         uuid.UUID
	PaidBefore int64
}

type LockVehicleForMaintenanceRow struct {
	ID                      uuid.UUID
	OwnerAccountID          uuid.UUID
	MaintenancePaidUntilSim int64
	OperatingCostPerDay     int64
}

// LockVehicleForMaintenance bloquea un vehículo vencido con su opex por día.
func (q *Queries) LockVehicleForMaintenance(ctx context.Context, arg LockVehicleForMaintenanceParams) (LockVehicleForMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, lockVehicleForMaintenance, arg.ID, arg.PaidBefore)
	var i LockVehicleForMaintenanceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.MaintenancePaidUntilSim,
		&i.OperatingCostPerDay,
	)
	return i, err
}

const markConcessionDelinquent = `-- name: MarkConcessionDelinquent :exec
UPDATE world.land_concessions
   SET status = 'delinquent',
       grace_until_sim = COALESCE(grace_until_sim, $1),
       updated_at = now()
 WHERE id = $2
`

type MarkConcessionDelinquentParams struct {
	GraceUntilSim *int64
	ID            uuid.UUID
}

// MarkConcessionDelinquent marca la concesión morosa (canon impagado) y fija el
// vencimiento del periodo de gracia si no lo tenía ya (COALESCE preserva la
// fecha de gracia original en reintentos).
func (q *Queries) MarkConcessionDelinquent(ctx context.Context, arg MarkConcessionDelinquentParams) error {
	_, err := q.db.Exec(ctx, markConcessionDelinquent, arg.GraceUntilSim, arg.ID)
	return err
}

const markConcessionGrace = `-- name: MarkConcessionGrace :exec
UPDATE world.land_concessions
   SET status = 'grace', updated_at = now()
 WHERE id = $1
`

// MarkConcessionGrace marca la concesión para embargo (grace); el barrido de
// embargo la procesa a reverted.
func (q *Queries) MarkConcessionGrace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markConcessionGrace, id)
	return err
}

const pauseRunningBatchesForBuilding = `-- name: PauseRunningBatchesForBuilding :exec
UPDATE world.production_batches
   SET status = 'paused_no_workers',
       started_at_sim = NULL,
       updated_at_sim = $1
 WHERE building_id = $2 AND status = 'running'
`

type PauseRunningBatchesForBuildingParams struct {
	UpdatedAtSim int64
	BuildingID   uuid.UUID
}

// PauseRunningBatchesForBuilding para la producción de un edificio embargado/
// abandonado: los lotes en curso pasan a paused_no_workers (reutiliza el estado
// del enum: sin dueño operativo no hay trabajadores). Suelta el reloj del lote.
func (q *Queries) PauseRunningBatchesForBuilding(ctx context.Context, arg PauseRunningBatchesForBuildingParams) error {
	_, err := q.db.Exec(ctx, pauseRunningBatchesForBuilding, arg.UpdatedAtSim, arg.BuildingID)
	return err
}

const revertConcession = `-- name: RevertConcession :exec
UPDATE world.land_concessions
   SET status = 'reverted', updated_at = now()
 WHERE id = $1
`

// RevertConcession revierte el suelo al sistema (la parcela queda libre: el POST
// concessions solo valida solape contra concesiones activas, así que otro jugador
// puede volver a pedirla).
func (q *Queries) RevertConcession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revertConcession, id)
	return err
}

const seizeBuilding = `-- name: SeizeBuilding :exec
UPDATE world.buildings
   SET status = 'seized', updated_at_sim = $1
 WHERE id = $2
`

type SeizeBuildingParams struct {
	UpdatedAtSim int64
	ID           uuid.UUID
}

// SeizeBuilding congela el edificio (seized: incomandable, no produce). El
// registro permanece; su reclamo físico completo es refinamiento Fase 2.
func (q *Queries) SeizeBuilding(ctx context.Context, arg SeizeBuildingParams) error {
	_, err := q.db.Exec(ctx, seizeBuilding, arg.UpdatedAtSim, arg.ID)
	return err
}

const setVehicleMaintenancePaid = `-- name: SetVehicleMaintenancePaid :exec
UPDATE world.vehicles
   SET maintenance_paid_until_sim = $1,
       updated_at_sim = $2
 WHERE id = $3
`

type SetVehicleMaintenancePaidParams struct {
	MaintenancePaidUntilSim int64
	UpdatedAtSim            int64
	ID                      uuid.UUID
}

// SetVehicleMaintenancePaid avanza el marcador de liquidación del opex del
// vehículo (los días que no pudo pagar se condonan: sin deuda, GDD 5.9).
func (q *Queries) SetVehicleMaintenancePaid(ctx context.Context, arg SetVehicleMaintenancePaidParams) error {
	_, err := q.db.Exec(ctx, setVehicleMaintenancePaid, arg.MaintenancePaidUntilSim, arg.UpdatedAtSim, arg.ID)
	return err
}

const updateBuildingMaintenance = `-- name: UpdateBuildingMaintenance :exec
UPDATE world.buildings
   SET maintenance_paid_until_sim = $1,
       condition_pct = $2,
       status = $3::world.building_status,
       updated_at_sim = $4
 WHERE id = $5
`

type UpdateBuildingMaintenanceParams struct {
	MaintenancePaidUntilSim int64
	ConditionPct            int32
	Status                  WorldBuildingStatus
	UpdatedAtSim            int64
	ID                      uuid.UUID
}

// UpdateBuildingMaintenance asienta el resultado del barrido: avanza el marcador
// de liquidación, fija la condición (recuperación o degradación) y el estado
// (operational/damaged/abandoned).
func (q *Queries) UpdateBuildingMaintenance(ctx context.Context, arg UpdateBuildingMaintenanceParams) error {
	_, err := q.db.Exec(ctx, updateBuildingMaintenance,
		arg.MaintenancePaidUntilSim,
		arg.ConditionPct,
		arg.Status,
		arg.UpdatedAtSim,
		arg.ID,
	)
	return err
}
