// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fleet.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countRouteLegsWrongMode = `-- name: CountRouteLegsWrongMode :one
SELECT COUNT(*)::bigint AS wrong
FROM world.route_legs rl
JOIN world.network_links l ON l.id = rl.link_id
WHERE rl.route_id = $1
  AND l.mode <> $2::world.link_mode
`

type CountRouteLegsWrongModeParams struct {
	RouteID uuid.UUID
	Mode    WorldLinkMode
}

// CountRouteLegsWrongMode cuenta los tramos de una ruta cuyo enlace NO es del modo
// dado. El despacho de la Fase 2 es POR TRAMO DE UN SOLO MODO (transbordo explícito
// en terminal, GDD 7.3): un vehículo solo puede recorrer enlaces de SU modo, así
// que una ruta con algún tramo de otro modo (0 = todos coinciden) no es despachable
// por ese vehículo. Un tren no circula por road, ni un camión por rail/sea.
func (q *Queries) CountRouteLegsWrongMode(ctx context.Context, arg CountRouteLegsWrongModeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRouteLegsWrongMode, arg.RouteID, arg.Mode)
	var wrong int64
	err := row.Scan(&wrong)
	return wrong, err
}

const dispatchShipment = `-- name: DispatchShipment :exec
UPDATE world.shipments
   SET vehicle_id = $1, at_node_id = NULL,
       status = 'in_transit', updated_at_sim = $2
 WHERE id = $3
`

type DispatchShipmentParams struct {
	VehicleID *uuid.UUID
	SimNow    int64
	ID        uuid.UUID
}

// DispatchShipment pone un cargamento a bordo del vehículo y en tránsito (deja el
// almacén: at_node_id = NULL).
func (q *Queries) DispatchShipment(ctx context.Context, arg DispatchShipmentParams) error {
	_, err := q.db.Exec(ctx, dispatchShipment, arg.VehicleID, arg.SimNow, arg.ID)
	return err
}

const dispatchVehicle = `-- name: DispatchVehicle :exec
UPDATE world.vehicles
   SET status = 'in_transit', route_id = $1, route_leg_index = 0,
       on_segment_id = $2, at_node_id = NULL,
       segment_entered_sim = $3, advance_fn = $4,
       updated_at_sim = $3
 WHERE id = $5
`

type DispatchVehicleParams struct {
	RouteID     *uuid.UUID
	OnSegmentID *uuid.UUID
	SimNow      *int64
	AdvanceFn   []byte
	ID          uuid.UUID
}

// DispatchVehicle arranca un vehículo idle: lo pone in_transit sobre el primer
// segmento del primer leg de la ruta, con advance_fn poblado y el reloj del
// segmento arrancado.
func (q *Queries) DispatchVehicle(ctx context.Context, arg DispatchVehicleParams) error {
	_, err := q.db.Exec(ctx, dispatchVehicle,
		arg.RouteID,
		arg.OnSegmentID,
		arg.SimNow,
		arg.AdvanceFn,
		arg.ID,
	)
	return err
}

const getNode = `-- name: GetNode :one

SELECT id, region_id, building_id FROM world.network_nodes WHERE id = $1
`

type GetNodeRow struct {
	ID         uuid.UUID
	RegionID   uuid.UUID
	BuildingID *uuid.UUID
}

// ─── Nodos y productos (validación de compra y despacho) ──────────────────────
// GetNode devuelve id, región y edificio de un nodo (existencia + almacén del
// destino/origen). building_id NULL si el nodo no es una instalación.
func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (GetNodeRow, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i GetNodeRow
	err := row.Scan(&i.ID, &i.RegionID, &i.BuildingID)
	return i, err
}

const getProductUnitVolume = `-- name: GetProductUnitVolume :one
SELECT unit_volume FROM world.products WHERE id = $1
`

// GetProductUnitVolume devuelve el volumen logístico por unidad de un producto
// (comprobación de capacidad de carga del vehículo).
func (q *Queries) GetProductUnitVolume(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProductUnitVolume, id)
	var unit_volume int32
	err := row.Scan(&unit_volume)
	return unit_volume, err
}

const getRouteEndpoints = `-- name: GetRouteEndpoints :one
SELECT
  (SELECT l.from_node_id FROM world.route_legs rl JOIN world.network_links l ON l.id = rl.link_id
     WHERE rl.route_id = $1 ORDER BY rl.leg_index ASC LIMIT 1) AS first_from_node,
  (SELECT l.to_node_id FROM world.route_legs rl JOIN world.network_links l ON l.id = rl.link_id
     WHERE rl.route_id = $1 ORDER BY rl.leg_index DESC LIMIT 1) AS last_to_node,
  (SELECT COALESCE(SUM(l.length_m), 0)::bigint FROM world.route_legs rl JOIN world.network_links l ON l.id = rl.link_id
     WHERE rl.route_id = $1) AS total_length_m,
  (SELECT COUNT(*)::bigint FROM world.route_legs rl WHERE rl.route_id = $1) AS leg_count
`

type GetRouteEndpointsRow struct {
	FirstFromNode uuid.UUID
	LastToNode    uuid.UUID
	TotalLengthM  int64
	LegCount      int64
}

// GetRouteEndpoints devuelve el nodo de origen del primer leg, el nodo destino
// del último leg, la distancia total (SUM de longitudes de enlace) y el número de
// legs de una ruta. Sirve para validar que la ruta empieza en el nodo del
// cargamento y termina en el destino del contrato, y para la comprobación de
// combustible.
func (q *Queries) GetRouteEndpoints(ctx context.Context, routeID uuid.UUID) (GetRouteEndpointsRow, error) {
	row := q.db.QueryRow(ctx, getRouteEndpoints, routeID)
	var i GetRouteEndpointsRow
	err := row.Scan(
		&i.FirstFromNode,
		&i.LastToNode,
		&i.TotalLengthM,
		&i.LegCount,
	)
	return i, err
}

const getRouteFirstSegment = `-- name: GetRouteFirstSegment :one
SELECT s.id AS segment_id, s.length_m,
       s.congestion_ema::float8 AS congestion_ema,
       l.base_speed_kmh, l.from_node_id, l.to_node_id
FROM world.route_legs rl
JOIN world.network_links l ON l.id = rl.link_id
JOIN world.link_segments s ON s.link_id = l.id
WHERE rl.route_id = $1
ORDER BY rl.leg_index ASC, s.seq ASC
LIMIT 1
`

type GetRouteFirstSegmentRow struct {
	SegmentID     uuid.UUID
	LengthM       int32
	CongestionEma float64
	BaseSpeedKmh  int32
	FromNodeID    uuid.UUID
	ToNodeID      uuid.UUID
}

// GetRouteFirstSegment devuelve el PRIMER segmento del PRIMER leg de una ruta
// (menor leg_index, menor seq) con los parámetros para poblar advance_fn al
// despachar (longitud, congestión EMA snapshot, velocidad base del enlace).
func (q *Queries) GetRouteFirstSegment(ctx context.Context, routeID uuid.UUID) (GetRouteFirstSegmentRow, error) {
	row := q.db.QueryRow(ctx, getRouteFirstSegment, routeID)
	var i GetRouteFirstSegmentRow
	err := row.Scan(
		&i.SegmentID,
		&i.LengthM,
		&i.CongestionEma,
		&i.BaseSpeedKmh,
		&i.FromNodeID,
		&i.ToNodeID,
	)
	return i, err
}

const getRouteOwnerActive = `-- name: GetRouteOwnerActive :one

SELECT owner_account_id, active FROM world.routes WHERE id = $1
`

type GetRouteOwnerActiveRow struct {
	OwnerAccountID uuid.UUID
	Active         bool
}

// ─── Rutas (validación del despacho; lectura, no escritura: eso es logistics) ──
// GetRouteOwnerActive devuelve el titular y si está activa una ruta (validación
// de propiedad del despacho). pgx.ErrNoRows si no existe.
func (q *Queries) GetRouteOwnerActive(ctx context.Context, id uuid.UUID) (GetRouteOwnerActiveRow, error) {
	row := q.db.QueryRow(ctx, getRouteOwnerActive, id)
	var i GetRouteOwnerActiveRow
	err := row.Scan(&i.OwnerAccountID, &i.Active)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, owner_account_id, product_id, quantity, contract_id, freight_contract_id,
       vehicle_id, at_node_id, status, updated_at_sim
FROM world.shipments
WHERE id = $1
`

type GetShipmentRow struct {
	ID                uuid.UUID
	OwnerAccountID    uuid.UUID
	ProductID         uuid.UUID
	Quantity          int64
	ContractID        *uuid.UUID
	FreightContractID *uuid.UUID
	VehicleID         *uuid.UUID
	AtNodeID          *uuid.UUID
	Status            WorldShipmentStatus
	UpdatedAtSim      int64
}

// GetShipment devuelve un cargamento por id (la propiedad la aplica el servicio).
func (q *Queries) GetShipment(ctx context.Context, id uuid.UUID) (GetShipmentRow, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i GetShipmentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.Quantity,
		&i.ContractID,
		&i.FreightContractID,
		&i.VehicleID,
		&i.AtNodeID,
		&i.Status,
		&i.UpdatedAtSim,
	)
	return i, err
}

const getTerminalByNode = `-- name: GetTerminalByNode :one
SELECT id, node_id, owner_account_id, transshipment_per_hour, queue_length
FROM world.terminals
WHERE node_id = $1
`

type GetTerminalByNodeRow struct {
	ID                   uuid.UUID
	NodeID               uuid.UUID
	OwnerAccountID       uuid.UUID
	TransshipmentPerHour int32
	QueueLength          int32
}

// GetTerminalByNode devuelve la terminal intermodal de un nodo (si existe): su id,
// dueño y capacidad de transbordo por hora. La usan el despacho (puerta de tiempo
// de transbordo de un cargamento at_terminal) y el motor de tránsito (decidir si
// una llegada intermedia es un transbordo). pgx.ErrNoRows si el nodo no la tiene.
func (q *Queries) GetTerminalByNode(ctx context.Context, nodeID uuid.UUID) (GetTerminalByNodeRow, error) {
	row := q.db.QueryRow(ctx, getTerminalByNode, nodeID)
	var i GetTerminalByNodeRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OwnerAccountID,
		&i.TransshipmentPerHour,
		&i.QueueLength,
	)
	return i, err
}

const getVehicle = `-- name: GetVehicle :one
SELECT
    v.id, v.vehicle_type_id, v.owner_account_id, v.status, v.wear_pct, v.fuel,
    v.route_id, v.route_leg_index, v.at_node_id, v.on_segment_id,
    v.repair_until_sim, v.updated_at_sim,
    CASE WHEN v.on_segment_id IS NOT NULL THEN
        LEAST(100.0, GREATEST(0.0,
            ($1::bigint - v.segment_entered_sim)::float8
            / NULLIF(world.segment_travel_seconds(v.advance_fn), 0)::float8 * 100.0))
    END AS segment_progress_pct,
    CASE
        WHEN v.at_node_id IS NOT NULL THEN ST_AsGeoJSON(n.location)::text
        WHEN v.on_segment_id IS NOT NULL THEN ST_AsGeoJSON(ST_LineInterpolatePoint(
            s.portion,
            CASE WHEN COALESCE((v.advance_fn->>'dir')::int, 1) = -1
                 THEN 1.0 - LEAST(1.0, GREATEST(0.0,
                        ($1::bigint - v.segment_entered_sim)::float8
                        / NULLIF(world.segment_travel_seconds(v.advance_fn), 0)::float8))
                 ELSE        LEAST(1.0, GREATEST(0.0,
                        ($1::bigint - v.segment_entered_sim)::float8
                        / NULLIF(world.segment_travel_seconds(v.advance_fn), 0)::float8))
            END))::text
    END AS location
FROM world.vehicles v
LEFT JOIN world.network_nodes n ON n.id = v.at_node_id
LEFT JOIN world.link_segments s ON s.id = v.on_segment_id
WHERE v.id = $2
`

type GetVehicleParams struct {
	SimNow int64
	ID     uuid.UUID
}

type GetVehicleRow struct {
	ID                 uuid.UUID
	VehicleTypeID      uuid.UUID
	OwnerAccountID     uuid.UUID
	Status             WorldVehicleStatus
	WearPct            int32
	Fuel               int64
	RouteID            *uuid.UUID
	RouteLegIndex      *int32
	AtNodeID           *uuid.UUID
	OnSegmentID        *uuid.UUID
	RepairUntilSim     *int64
	UpdatedAtSim       int64
	SegmentProgressPct interface{}
	Location           interface{}
}

// GetVehicle devuelve un vehículo por id con su posición derivada (la propiedad
// la aplica el servicio: 403 si es ajeno). pgx.ErrNoRows si no existe.
func (q *Queries) GetVehicle(ctx context.Context, arg GetVehicleParams) (GetVehicleRow, error) {
	row := q.db.QueryRow(ctx, getVehicle, arg.SimNow, arg.ID)
	var i GetVehicleRow
	err := row.Scan(
		&i.ID,
		&i.VehicleTypeID,
		&i.OwnerAccountID,
		&i.Status,
		&i.WearPct,
		&i.Fuel,
		&i.RouteID,
		&i.RouteLegIndex,
		&i.AtNodeID,
		&i.OnSegmentID,
		&i.RepairUntilSim,
		&i.UpdatedAtSim,
		&i.SegmentProgressPct,
		&i.Location,
	)
	return i, err
}

const getVehicleType = `-- name: GetVehicleType :one
SELECT id, code, name, mode, cargo_capacity, speed_kmh, fuel_product_id,
       fuel_per_100km, autonomy_km, purchase_price, operating_cost_per_day
FROM world.vehicle_types
WHERE id = $1
`

type GetVehicleTypeRow struct {
	ID                  uuid.UUID
	Code                string
	Name                string
	Mode                WorldLinkMode
	CargoCapacity       int64
	SpeedKmh            int32
	FuelProductID       uuid.UUID
	FuelPer100km        int64
	AutonomyKm          int32
	PurchasePrice       int64
	OperatingCostPerDay int64
}

// GetVehicleType devuelve un tipo por id (compra: precio, autonomía, capacidad,
// combustible y modo). pgx.ErrNoRows si no existe.
func (q *Queries) GetVehicleType(ctx context.Context, id uuid.UUID) (GetVehicleTypeRow, error) {
	row := q.db.QueryRow(ctx, getVehicleType, id)
	var i GetVehicleTypeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Mode,
		&i.CargoCapacity,
		&i.SpeedKmh,
		&i.FuelProductID,
		&i.FuelPer100km,
		&i.AutonomyKm,
		&i.PurchasePrice,
		&i.OperatingCostPerDay,
	)
	return i, err
}

const insertShipmentInWarehouse = `-- name: InsertShipmentInWarehouse :one

INSERT INTO world.shipments
    (id, owner_account_id, product_id, quantity, contract_id, at_node_id, destination_node_id, deadline_sim, status, updated_at_sim)
VALUES
    ($1, $2, $3, $4,
     $5, $6, $7, $8,
     'in_warehouse', $9)
RETURNING id
`

type InsertShipmentInWarehouseParams struct {
	ID                uuid.UUID
	OwnerAccountID    uuid.UUID
	ProductID         uuid.UUID
	Quantity          int64
	ContractID        *uuid.UUID
	AtNodeID          *uuid.UUID
	DestinationNodeID *uuid.UUID
	DeadlineSim       *int64
	SimNow            int64
}

// ─── Consumidor shipment_creator (contract.confirmed → cargamento) ────────────
// InsertShipmentInWarehouse crea el cargamento in_warehouse en el nodo de origen
// del contrato, etiquetado por contract_id y con el destino/plazo del contrato
// persistidos localmente (0009) para el despacho y la confirmación de entrega.
func (q *Queries) InsertShipmentInWarehouse(ctx context.Context, arg InsertShipmentInWarehouseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertShipmentInWarehouse,
		arg.ID,
		arg.OwnerAccountID,
		arg.ProductID,
		arg.Quantity,
		arg.ContractID,
		arg.AtNodeID,
		arg.DestinationNodeID,
		arg.DeadlineSim,
		arg.SimNow,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVehicle = `-- name: InsertVehicle :one

INSERT INTO world.vehicles (id, vehicle_type_id, owner_account_id, status, wear_pct, fuel, at_node_id, updated_at_sim)
VALUES ($1, $2, $3, 'idle', 0, $4, $5, $6)
RETURNING id
`

type InsertVehicleParams struct {
	ID             uuid.UUID
	VehicleTypeID  uuid.UUID
	OwnerAccountID uuid.UUID
	Fuel           int64
	AtNodeID       *uuid.UUID
	SimNow         int64
}

// ─── Compra y comando ─────────────────────────────────────────────────────────
// InsertVehicle da de alta un vehículo idle en el nodo de entrega con el tanque
// lleno (equivalente a autonomy_km) y sin desgaste. La posición la deriva la
// lectura posterior (GetVehicle).
func (q *Queries) InsertVehicle(ctx context.Context, arg InsertVehicleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertVehicle,
		arg.ID,
		arg.VehicleTypeID,
		arg.OwnerAccountID,
		arg.Fuel,
		arg.AtNodeID,
		arg.SimNow,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listShipments = `-- name: ListShipments :many

SELECT id, owner_account_id, product_id, quantity, contract_id, freight_contract_id,
       vehicle_id, at_node_id, status, updated_at_sim
FROM world.shipments
WHERE owner_account_id = $1
  AND ($2::world.shipment_status IS NULL OR status = $2::world.shipment_status)
  AND ($3::uuid IS NULL OR contract_id = $3::uuid)
  AND ($4::uuid IS NULL OR vehicle_id = $4::uuid)
  AND ($5::uuid IS NULL OR id > $5::uuid)
ORDER BY id
LIMIT $6
`

type ListShipmentsParams struct {
	OwnerAccountID uuid.UUID
	Status         NullWorldShipmentStatus
	ContractID     *uuid.UUID
	VehicleID      *uuid.UUID
	AfterID        *uuid.UUID
	PageLimit      int32
}

type ListShipmentsRow struct {
	ID                uuid.UUID
	OwnerAccountID    uuid.UUID
	ProductID         uuid.UUID
	Quantity          int64
	ContractID        *uuid.UUID
	FreightContractID *uuid.UUID
	VehicleID         *uuid.UUID
	AtNodeID          *uuid.UUID
	Status            WorldShipmentStatus
	UpdatedAtSim      int64
}

// ─── Cargamentos propios ──────────────────────────────────────────────────────
// ListShipments devuelve los cargamentos de un titular (SOLO propios) con filtros
// por estado/contrato/vehículo y keyset por id.
func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]ListShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listShipments,
		arg.OwnerAccountID,
		arg.Status,
		arg.ContractID,
		arg.VehicleID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShipmentsRow
	for rows.Next() {
		var i ListShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.ProductID,
			&i.Quantity,
			&i.ContractID,
			&i.FreightContractID,
			&i.VehicleID,
			&i.AtNodeID,
			&i.Status,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleTypes = `-- name: ListVehicleTypes :many


SELECT id, code, name, mode, cargo_capacity, speed_kmh, fuel_product_id,
       fuel_per_100km, autonomy_km, purchase_price, operating_cost_per_day
FROM world.vehicle_types
WHERE ($1::world.link_mode IS NULL OR mode = $1::world.link_mode)
  AND ($2::uuid IS NULL OR id > $2::uuid)
ORDER BY id
LIMIT $3
`

type ListVehicleTypesParams struct {
	Mode      NullWorldLinkMode
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListVehicleTypesRow struct {
	ID                  uuid.UUID
	Code                string
	Name                string
	Mode                WorldLinkMode
	CargoCapacity       int64
	SpeedKmh            int32
	FuelProductID       uuid.UUID
	FuelPer100km        int64
	AutonomyKm          int32
	PurchasePrice       int64
	OperatingCostPerDay int64
}

// =============================================================================
// Imperio Industrial — queries sqlc de FLOTA y CARGAMENTOS (Incremento 3, Fase 1
// terrestre). Superficie de los handlers world/* del contrato v1.3.0
// (internal/world/fleet): catálogo de vehículos, flota propia con posición
// ANALÍTICA derivada bajo demanda (GDD 1.1/7.3), compra, comando y despacho de
// cargamentos. Las queries del MOTOR de tránsito (barridos, congestión, entrega)
// viven en transit.sql; las reutilizadas (ledger/inventario) en land.sql y
// production.sql (paquete sqlc compartido del contexto world).
//
// Geometrías (location/portion): SRID 0 planar, metros de mundo (ADR-019). Se
// proyectan con ST_AsGeoJSON(...)::text. congestion_ema es NUMERIC → float8.
// Dinero/stock (money_amount/stock_qty) son enteros de 64 bits (nunca float).
// =============================================================================
// ─── Catálogo de tipos de vehículo ────────────────────────────────────────────
// ListVehicleTypes devuelve el catálogo con filtro opcional por modo y keyset
// por id (GET /world/vehicle-types). Lectura pública del mundo (sin propiedad).
func (q *Queries) ListVehicleTypes(ctx context.Context, arg ListVehicleTypesParams) ([]ListVehicleTypesRow, error) {
	rows, err := q.db.Query(ctx, listVehicleTypes, arg.Mode, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleTypesRow
	for rows.Next() {
		var i ListVehicleTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Mode,
			&i.CargoCapacity,
			&i.SpeedKmh,
			&i.FuelProductID,
			&i.FuelPer100km,
			&i.AutonomyKm,
			&i.PurchasePrice,
			&i.OperatingCostPerDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many

SELECT
    v.id, v.vehicle_type_id, v.owner_account_id, v.status, v.wear_pct, v.fuel,
    v.route_id, v.route_leg_index, v.at_node_id, v.on_segment_id,
    v.repair_until_sim, v.updated_at_sim,
    CASE WHEN v.on_segment_id IS NOT NULL THEN
        LEAST(100.0, GREATEST(0.0,
            ($1::bigint - v.segment_entered_sim)::float8
            / NULLIF(world.segment_travel_seconds(v.advance_fn), 0)::float8 * 100.0))
    END AS segment_progress_pct,
    CASE
        WHEN v.at_node_id IS NOT NULL THEN ST_AsGeoJSON(n.location)::text
        WHEN v.on_segment_id IS NOT NULL THEN ST_AsGeoJSON(ST_LineInterpolatePoint(
            s.portion,
            CASE WHEN COALESCE((v.advance_fn->>'dir')::int, 1) = -1
                 THEN 1.0 - LEAST(1.0, GREATEST(0.0,
                        ($1::bigint - v.segment_entered_sim)::float8
                        / NULLIF(world.segment_travel_seconds(v.advance_fn), 0)::float8))
                 ELSE        LEAST(1.0, GREATEST(0.0,
                        ($1::bigint - v.segment_entered_sim)::float8
                        / NULLIF(world.segment_travel_seconds(v.advance_fn), 0)::float8))
            END))::text
    END AS location
FROM world.vehicles v
LEFT JOIN world.network_nodes n ON n.id = v.at_node_id
LEFT JOIN world.link_segments s ON s.id = v.on_segment_id
WHERE v.owner_account_id = $2
  AND ($3::world.vehicle_status IS NULL OR v.status = $3::world.vehicle_status)
  AND ($4::uuid IS NULL OR v.route_id = $4::uuid)
  AND ($5::uuid IS NULL OR v.id > $5::uuid)
ORDER BY v.id
LIMIT $6
`

type ListVehiclesParams struct {
	SimNow         int64
	OwnerAccountID uuid.UUID
	Status         NullWorldVehicleStatus
	RouteID        *uuid.UUID
	AfterID        *uuid.UUID
	PageLimit      int32
}

type ListVehiclesRow struct {
	ID                 uuid.UUID
	VehicleTypeID      uuid.UUID
	OwnerAccountID     uuid.UUID
	Status             WorldVehicleStatus
	WearPct            int32
	Fuel               int64
	RouteID            *uuid.UUID
	RouteLegIndex      *int32
	AtNodeID           *uuid.UUID
	OnSegmentID        *uuid.UUID
	RepairUntilSim     *int64
	UpdatedAtSim       int64
	SegmentProgressPct interface{}
	Location           interface{}
}

// ─── Flota propia con posición ANALÍTICA ──────────────────────────────────────
// ListVehicles devuelve los vehículos de un titular (SOLO propios) con filtros
// por estado/ruta, keyset por id, y la POSICIÓN derivada al observarla (GDD 1.1):
// si on_segment, segment_progress_pct = avance en [0,100] y location interpolada
// a lo largo de la porción del segmento (ST_LineInterpolatePoint); si at_node, la
// location del nodo. El tiempo de viaje sale de la función canónica
// world.segment_travel_seconds (misma fórmula que el motor).
func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]ListVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listVehicles,
		arg.SimNow,
		arg.OwnerAccountID,
		arg.Status,
		arg.RouteID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleTypeID,
			&i.OwnerAccountID,
			&i.Status,
			&i.WearPct,
			&i.Fuel,
			&i.RouteID,
			&i.RouteLegIndex,
			&i.AtNodeID,
			&i.OnSegmentID,
			&i.RepairUntilSim,
			&i.UpdatedAtSim,
			&i.SegmentProgressPct,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockShipmentForDispatch = `-- name: LockShipmentForDispatch :one
SELECT id, owner_account_id, product_id, quantity, contract_id, freight_contract_id,
       vehicle_id, at_node_id, destination_node_id, deadline_sim, status, updated_at_sim
FROM world.shipments
WHERE id = $1
FOR UPDATE
`

type LockShipmentForDispatchRow struct {
	ID                uuid.UUID
	OwnerAccountID    uuid.UUID
	ProductID         uuid.UUID
	Quantity          int64
	ContractID        *uuid.UUID
	FreightContractID *uuid.UUID
	VehicleID         *uuid.UUID
	AtNodeID          *uuid.UUID
	DestinationNodeID *uuid.UUID
	DeadlineSim       *int64
	Status            WorldShipmentStatus
	UpdatedAtSim      int64
}

// LockShipmentForDispatch bloquea un cargamento (FOR UPDATE) para despacharlo:
// añade el destino del contrato y el plazo (columnas de 0009). Sirve tanto al
// despacho del primer tramo (in_warehouse) como al de un tramo posterior de una
// ruta multimodal (at_terminal tras un transbordo). pgx.ErrNoRows si no existe.
func (q *Queries) LockShipmentForDispatch(ctx context.Context, id uuid.UUID) (LockShipmentForDispatchRow, error) {
	row := q.db.QueryRow(ctx, lockShipmentForDispatch, id)
	var i LockShipmentForDispatchRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.Quantity,
		&i.ContractID,
		&i.FreightContractID,
		&i.VehicleID,
		&i.AtNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.UpdatedAtSim,
	)
	return i, err
}

const lockVehicle = `-- name: LockVehicle :one
SELECT id, vehicle_type_id, owner_account_id, status, wear_pct, fuel,
       route_id, route_leg_index, at_node_id, on_segment_id, repair_until_sim, updated_at_sim
FROM world.vehicles
WHERE id = $1
FOR UPDATE
`

type LockVehicleRow struct {
	ID             uuid.UUID
	VehicleTypeID  uuid.UUID
	OwnerAccountID uuid.UUID
	Status         WorldVehicleStatus
	WearPct        int32
	Fuel           int64
	RouteID        *uuid.UUID
	RouteLegIndex  *int32
	AtNodeID       *uuid.UUID
	OnSegmentID    *uuid.UUID
	RepairUntilSim *int64
	UpdatedAtSim   int64
}

// LockVehicle bloquea un vehículo (FOR UPDATE) para PATCH o despacho: decide bajo
// lock la propiedad, el estado (idle/sealed) y la ubicación. pgx.ErrNoRows si no
// existe.
func (q *Queries) LockVehicle(ctx context.Context, id uuid.UUID) (LockVehicleRow, error) {
	row := q.db.QueryRow(ctx, lockVehicle, id)
	var i LockVehicleRow
	err := row.Scan(
		&i.ID,
		&i.VehicleTypeID,
		&i.OwnerAccountID,
		&i.Status,
		&i.WearPct,
		&i.Fuel,
		&i.RouteID,
		&i.RouteLegIndex,
		&i.AtNodeID,
		&i.OnSegmentID,
		&i.RepairUntilSim,
		&i.UpdatedAtSim,
	)
	return i, err
}

const nodeHasModeLink = `-- name: NodeHasModeLink :one
SELECT EXISTS (
    SELECT 1 FROM world.network_links
    WHERE mode = $1::world.link_mode
      AND (from_node_id = $2 OR to_node_id = $2)
)::boolean AS accessible
`

type NodeHasModeLinkParams struct {
	Mode   WorldLinkMode
	NodeID uuid.UUID
}

// NodeHasModeLink indica si un nodo está conectado a ALGÚN enlace de un modo
// (accesibilidad del nodo de entrega para el modo del vehículo).
func (q *Queries) NodeHasModeLink(ctx context.Context, arg NodeHasModeLinkParams) (bool, error) {
	row := q.db.QueryRow(ctx, nodeHasModeLink, arg.Mode, arg.NodeID)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const setVehicleMaintenance = `-- name: SetVehicleMaintenance :exec
UPDATE world.vehicles
   SET status = 'in_maintenance', wear_pct = 0,
       repair_until_sim = $1, updated_at_sim = $2
 WHERE id = $3
`

type SetVehicleMaintenanceParams struct {
	RepairUntilSim *int64
	SimNow         int64
	ID             uuid.UUID
}

// SetVehicleMaintenance programa mantenimiento: reduce el desgaste a 0 y deja el
// vehículo in_maintenance hasta repair_until_sim (el barrido lo devuelve a idle).
func (q *Queries) SetVehicleMaintenance(ctx context.Context, arg SetVehicleMaintenanceParams) error {
	_, err := q.db.Exec(ctx, setVehicleMaintenance, arg.RepairUntilSim, arg.SimNow, arg.ID)
	return err
}

const setVehicleRoute = `-- name: SetVehicleRoute :exec
UPDATE world.vehicles
   SET route_id = $1, updated_at_sim = $2
 WHERE id = $3
`

type SetVehicleRouteParams struct {
	RouteID *uuid.UUID
	SimNow  int64
	ID      uuid.UUID
}

// SetVehicleRoute asigna (o retira, con NULL) la ruta de un vehículo.
func (q *Queries) SetVehicleRoute(ctx context.Context, arg SetVehicleRouteParams) error {
	_, err := q.db.Exec(ctx, setVehicleRoute, arg.RouteID, arg.SimNow, arg.ID)
	return err
}

const shipmentExistsForContract = `-- name: ShipmentExistsForContract :one
SELECT EXISTS (SELECT 1 FROM world.shipments WHERE contract_id = $1)::boolean AS present
`

// ShipmentExistsForContract indica si ya hay un cargamento para un contrato
// (guarda de idempotencia del consumidor ante reprocesos, defensiva).
func (q *Queries) ShipmentExistsForContract(ctx context.Context, contractID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, shipmentExistsForContract, contractID)
	var present bool
	err := row.Scan(&present)
	return present, err
}
