// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: land.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const accountExists = `-- name: AccountExists :one
SELECT EXISTS (SELECT 1 FROM auth.accounts WHERE id = $1)::boolean AS present
`

// AccountExists comprueba la existencia de una cuenta de auth (destinatario de
// un traspaso de concesión).
func (q *Queries) AccountExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, accountExists, id)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const concessionParcelOverlaps = `-- name: ConcessionParcelOverlaps :one
SELECT EXISTS (
    SELECT 1 FROM world.land_concessions
    WHERE region_id = $1
      AND status = 'active'
      AND ST_Intersects(parcel, ST_SetSRID(ST_GeomFromGeoJSON($2::text), 0))
)::boolean AS overlaps
`

type ConcessionParcelOverlapsParams struct {
	RegionID      uuid.UUID
	ParcelGeojson string
}

// ConcessionParcelOverlaps indica si la parcela solicitada se solapa
// (ST_Intersects) con alguna concesión ACTIVA de la región (→ 409).
func (q *Queries) ConcessionParcelOverlaps(ctx context.Context, arg ConcessionParcelOverlapsParams) (bool, error) {
	row := q.db.QueryRow(ctx, concessionParcelOverlaps, arg.RegionID, arg.ParcelGeojson)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const getCashAccount = `-- name: GetCashAccount :one

SELECT id, balance FROM ledger.accounts
WHERE kind = 'cash' AND owner_account_id = $1
`

type GetCashAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// ═════════════════════════════════════════════════════════════════════════════
// Soporte de ledger del contexto world (COMPARTIDO con world/buildings).
//
// world consume el substrato de valor (ledger) EXACTAMENTE como lo hizo
// internal/contracts: queries sqlc propias del contexto contra las tablas
// ledger.* (la frontera de módulo es de código Go, no de esquema). Aquí solo se
// ASIENTA como SINK (canon/maintenance/wage) y se hacen traspasos cash→cash; las
// invariantes (no-negatividad, doble entrada diferida, inmutabilidad) las
// garantizan los triggers de 0004_ledger — nunca se recalculan saldos.
// ═════════════════════════════════════════════════════════════════════════════
// GetCashAccount devuelve la única caja de una corporación (unicidad parcial
// ux_accounts_cash); ErrNoRows si aún no tiene caja (→ fondos insuficientes).
func (q *Queries) GetCashAccount(ctx context.Context, ownerAccountID *uuid.UUID) (GetCashAccountRow, error) {
	row := q.db.QueryRow(ctx, getCashAccount, ownerAccountID)
	var i GetCashAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getConcession = `-- name: GetConcession :one
SELECT id, region_id, holder_account_id,
       ST_AsGeoJSON(parcel)::text AS parcel,
       canon_amount, period_sim_days, expires_at_sim, status, granted_at_sim
FROM world.land_concessions
WHERE id = $1
`

type GetConcessionRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Parcel          string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GrantedAtSim    int64
}

// GetConcession devuelve una concesión por id (la autorización por titular la
// aplica la capa de servicio).
func (q *Queries) GetConcession(ctx context.Context, id uuid.UUID) (GetConcessionRow, error) {
	row := q.db.QueryRow(ctx, getConcession, id)
	var i GetConcessionRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Parcel,
		&i.CanonAmount,
		&i.PeriodSimDays,
		&i.ExpiresAtSim,
		&i.Status,
		&i.GrantedAtSim,
	)
	return i, err
}

const getConcessionForUpdate = `-- name: GetConcessionForUpdate :one
SELECT id, region_id, holder_account_id,
       ST_AsGeoJSON(parcel)::text AS parcel,
       canon_amount, period_sim_days, expires_at_sim, status, granted_at_sim
FROM world.land_concessions
WHERE id = $1
FOR UPDATE
`

type GetConcessionForUpdateRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Parcel          string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GrantedAtSim    int64
}

// GetConcessionForUpdate bloquea la fila (SELECT FOR UPDATE) para renovación y
// traspaso: las validaciones de titular/estado y el cobro se deciden bajo lock.
func (q *Queries) GetConcessionForUpdate(ctx context.Context, id uuid.UUID) (GetConcessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getConcessionForUpdate, id)
	var i GetConcessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Parcel,
		&i.CanonAmount,
		&i.PeriodSimDays,
		&i.ExpiresAtSim,
		&i.Status,
		&i.GrantedAtSim,
	)
	return i, err
}

const getSinkAccount = `-- name: GetSinkAccount :one
SELECT id, balance FROM ledger.accounts
WHERE kind = 'sink' ORDER BY id LIMIT 1
`

type GetSinkAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// GetSinkAccount devuelve la cuenta sink del banco central (destino de canon,
// coste de construcción/mejora, salarios y tasa de traspaso — GDD 5.5).
func (q *Queries) GetSinkAccount(ctx context.Context) (GetSinkAccountRow, error) {
	row := q.db.QueryRow(ctx, getSinkAccount)
	var i GetSinkAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const insertConcession = `-- name: InsertConcession :one

INSERT INTO world.land_concessions (
    id, region_id, holder_account_id, parcel, canon_amount,
    period_sim_days, expires_at_sim, status, granted_at_sim)
VALUES (
    $1, $2, $3,
    ST_SetSRID(ST_GeomFromGeoJSON($4::text), 0),
    $5, $6,
    $7, 'active', $8)
RETURNING id, region_id, holder_account_id,
          ST_AsGeoJSON(parcel)::text AS parcel,
          canon_amount, period_sim_days, expires_at_sim, status, granted_at_sim
`

type InsertConcessionParams struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	ParcelGeojson   string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	GrantedAtSim    int64
}

type InsertConcessionRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Parcel          string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GrantedAtSim    int64
}

// ─── Concesiones: escritura ───────────────────────────────────────────────────
// InsertConcession crea la concesión activa (plazo de referencia 90 días). El
// canon ya se cobró al sink en la misma transacción. parcel entra como GeoJSON
// plano; sale proyectada.
func (q *Queries) InsertConcession(ctx context.Context, arg InsertConcessionParams) (InsertConcessionRow, error) {
	row := q.db.QueryRow(ctx, insertConcession,
		arg.ID,
		arg.RegionID,
		arg.HolderAccountID,
		arg.ParcelGeojson,
		arg.CanonAmount,
		arg.PeriodSimDays,
		arg.ExpiresAtSim,
		arg.GrantedAtSim,
	)
	var i InsertConcessionRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Parcel,
		&i.CanonAmount,
		&i.PeriodSimDays,
		&i.ExpiresAtSim,
		&i.Status,
		&i.GrantedAtSim,
	)
	return i, err
}

const insertConcessionTransfer = `-- name: InsertConcessionTransfer :one
INSERT INTO world.concession_transfers (
    id, concession_id, from_account_id, to_account_id, price, system_fee, occurred_at_sim)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7)
RETURNING id, concession_id, from_account_id, to_account_id, price, system_fee, occurred_at_sim
`

type InsertConcessionTransferParams struct {
	ID            uuid.UUID
	ConcessionID  uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Price         int64
	SystemFee     int64
	OccurredAtSim int64
}

type InsertConcessionTransferRow struct {
	ID            uuid.UUID
	ConcessionID  uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Price         int64
	SystemFee     int64
	OccurredAtSim int64
}

// InsertConcessionTransfer registra el traspaso ejecutado (mercado secundario,
// con la tasa del sistema).
func (q *Queries) InsertConcessionTransfer(ctx context.Context, arg InsertConcessionTransferParams) (InsertConcessionTransferRow, error) {
	row := q.db.QueryRow(ctx, insertConcessionTransfer,
		arg.ID,
		arg.ConcessionID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Price,
		arg.SystemFee,
		arg.OccurredAtSim,
	)
	var i InsertConcessionTransferRow
	err := row.Scan(
		&i.ID,
		&i.ConcessionID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Price,
		&i.SystemFee,
		&i.OccurredAtSim,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger.entries (id, transaction_id, account_id, amount)
VALUES ($1, $2, $3, $4)
`

type InsertLedgerEntryParams struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
}

// InsertLedgerEntry inserta una partida de doble entrada; los triggers aplican
// saldo, no-negatividad y (diferido) el balance por activo del asiento.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}

const insertLedgerTransaction = `-- name: InsertLedgerTransaction :exec
INSERT INTO ledger.transactions (id, kind, sim_time_at, reference_id, description)
VALUES ($1, $2, $3,
        $4, $5)
`

type InsertLedgerTransactionParams struct {
	ID          uuid.UUID
	Kind        LedgerTransactionKind
	SimTimeAt   int64
	ReferenceID *uuid.UUID
	Description *string
}

// InsertLedgerTransaction inserta la cabecera de un asiento (inmutable). El id
// (UUIDv7) lo genera la aplicación (ADR-018).
func (q *Queries) InsertLedgerTransaction(ctx context.Context, arg InsertLedgerTransactionParams) error {
	_, err := q.db.Exec(ctx, insertLedgerTransaction,
		arg.ID,
		arg.Kind,
		arg.SimTimeAt,
		arg.ReferenceID,
		arg.Description,
	)
	return err
}

const listConcessions = `-- name: ListConcessions :many


SELECT id, region_id, holder_account_id,
       ST_AsGeoJSON(parcel)::text AS parcel,
       canon_amount, period_sim_days, expires_at_sim, status, granted_at_sim
FROM world.land_concessions
WHERE holder_account_id = $1
  AND ($2::world.concession_status IS NULL OR status = $2::world.concession_status)
  AND ($3::uuid IS NULL OR region_id = $3::uuid)
  AND ($4::uuid IS NULL OR id > $4::uuid)
ORDER BY id
LIMIT $5
`

type ListConcessionsParams struct {
	HolderAccountID uuid.UUID
	Status          NullWorldConcessionStatus
	RegionID        *uuid.UUID
	AfterID         *uuid.UUID
	PageLimit       int32
}

type ListConcessionsRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Parcel          string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GrantedAtSim    int64
}

// =============================================================================
// Imperio Industrial — queries sqlc del subpaquete world/land (ADR-020).
// Suelo: concesiones renovables del sistema y su mercado secundario de
// traspasos (GDD 11.1). Es el lado de ESCRITURA del contexto world para el
// suelo: cada operación que mueve valor (canon, traspaso) corre en una
// transacción SERIALIZABLE con outbox.Emit en la misma tx.
//
// La frontera de módulo es de código Go, no de esquema: estas queries leen y
// escriben world.* (land_concessions, concession_transfers, regions) y asientan
// en ledger.* (canon/transfer como sink), igual que hizo internal/contracts.
//
// Geometrías (parcel/bounds): SRID 0 planar, metros de mundo (ADR-019). La
// ENTRADA llega como GeoJSON del contrato y se proyecta con
// ST_SetSRID(ST_GeomFromGeoJSON(...), 0) — ST_GeomFromGeoJSON asume 4326, así
// que se re-etiqueta a 0 sin transformar coordenadas. La SALIDA se proyecta con
// ST_AsGeoJSON(...)::text, que los handlers embeben en el schema GeoPolygon.
//
// La sección "Soporte de ledger" es COMPARTIDA con world/buildings (build_cost,
// upgrade_cost): la frontera entre subpaquetes es de código Go, no de fichero
// SQL — ambos comparten el paquete sqlcgen del contexto.
// =============================================================================
// ─── Concesiones: lectura ─────────────────────────────────────────────────────
// ListConcessions devuelve las concesiones de un titular (SOLO propias) con
// filtros opcionales por estado y región, y paginación keyset por id. parcel
// sale como GeoJSON plano (SRID 0).
func (q *Queries) ListConcessions(ctx context.Context, arg ListConcessionsParams) ([]ListConcessionsRow, error) {
	rows, err := q.db.Query(ctx, listConcessions,
		arg.HolderAccountID,
		arg.Status,
		arg.RegionID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConcessionsRow
	for rows.Next() {
		var i ListConcessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.HolderAccountID,
			&i.Parcel,
			&i.CanonAmount,
			&i.PeriodSimDays,
			&i.ExpiresAtSim,
			&i.Status,
			&i.GrantedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionParcelWithin = `-- name: RegionParcelWithin :one

SELECT ST_Within(ST_SetSRID(ST_GeomFromGeoJSON($1::text), 0), bounds)::boolean AS within,
       canon_base
FROM world.regions
WHERE id = $2
`

type RegionParcelWithinParams struct {
	ParcelGeojson string
	RegionID      uuid.UUID
}

type RegionParcelWithinRow struct {
	Within    bool
	CanonBase int64
}

// ─── Concesiones: emplazamiento ───────────────────────────────────────────────
// RegionParcelWithin comprueba, en una sola consulta, que la región existe
// (ErrNoRows si no) y que la parcela solicitada cae DENTRO de sus límites
// (ST_Within); devuelve además el canon_base regional, base del canon del
// periodo.
func (q *Queries) RegionParcelWithin(ctx context.Context, arg RegionParcelWithinParams) (RegionParcelWithinRow, error) {
	row := q.db.QueryRow(ctx, regionParcelWithin, arg.ParcelGeojson, arg.RegionID)
	var i RegionParcelWithinRow
	err := row.Scan(&i.Within, &i.CanonBase)
	return i, err
}

const renewConcession = `-- name: RenewConcession :one
UPDATE world.land_concessions
   SET expires_at_sim = expires_at_sim + $1::bigint,
       updated_at = now()
 WHERE id = $2
RETURNING id, region_id, holder_account_id,
          ST_AsGeoJSON(parcel)::text AS parcel,
          canon_amount, period_sim_days, expires_at_sim, status, granted_at_sim
`

type RenewConcessionParams struct {
	ExtendSimSeconds int64
	ID               uuid.UUID
}

type RenewConcessionRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Parcel          string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GrantedAtSim    int64
}

// RenewConcession extiende el vencimiento otro periodo (expires += delta en
// sim-time). El canon vigente ya se cobró al sink en la misma transacción.
func (q *Queries) RenewConcession(ctx context.Context, arg RenewConcessionParams) (RenewConcessionRow, error) {
	row := q.db.QueryRow(ctx, renewConcession, arg.ExtendSimSeconds, arg.ID)
	var i RenewConcessionRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Parcel,
		&i.CanonAmount,
		&i.PeriodSimDays,
		&i.ExpiresAtSim,
		&i.Status,
		&i.GrantedAtSim,
	)
	return i, err
}

const setConcessionHolder = `-- name: SetConcessionHolder :one
UPDATE world.land_concessions
   SET holder_account_id = $1, updated_at = now()
 WHERE id = $2
RETURNING id, region_id, holder_account_id,
          ST_AsGeoJSON(parcel)::text AS parcel,
          canon_amount, period_sim_days, expires_at_sim, status, granted_at_sim
`

type SetConcessionHolderParams struct {
	HolderAccountID uuid.UUID
	ID              uuid.UUID
}

type SetConcessionHolderRow struct {
	ID              uuid.UUID
	RegionID        uuid.UUID
	HolderAccountID uuid.UUID
	Parcel          string
	CanonAmount     int64
	PeriodSimDays   int32
	ExpiresAtSim    int64
	Status          WorldConcessionStatus
	GrantedAtSim    int64
}

// SetConcessionHolder cambia el titular de la concesión (traspaso). El pago
// comprador→vendedor y la tasa comprador→sink ya se asentaron en la misma tx.
func (q *Queries) SetConcessionHolder(ctx context.Context, arg SetConcessionHolderParams) (SetConcessionHolderRow, error) {
	row := q.db.QueryRow(ctx, setConcessionHolder, arg.HolderAccountID, arg.ID)
	var i SetConcessionHolderRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.HolderAccountID,
		&i.Parcel,
		&i.CanonAmount,
		&i.PeriodSimDays,
		&i.ExpiresAtSim,
		&i.Status,
		&i.GrantedAtSim,
	)
	return i, err
}
