// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type LedgerTransactionKind string

const (
	LedgerTransactionKindSeedCapital          LedgerTransactionKind = "seed_capital"
	LedgerTransactionKindBotCapitalization    LedgerTransactionKind = "bot_capitalization"
	LedgerTransactionKindBotRetirement        LedgerTransactionKind = "bot_retirement"
	LedgerTransactionKindPublicationLock      LedgerTransactionKind = "publication_lock"
	LedgerTransactionKindPublicationRelease   LedgerTransactionKind = "publication_release"
	LedgerTransactionKindAcceptanceLock       LedgerTransactionKind = "acceptance_lock"
	LedgerTransactionKindContractConfirmation LedgerTransactionKind = "contract_confirmation"
	LedgerTransactionKindDeliverySettlement   LedgerTransactionKind = "delivery_settlement"
	LedgerTransactionKindCustodyLoad          LedgerTransactionKind = "custody_load"
	LedgerTransactionKindCustodyRelease       LedgerTransactionKind = "custody_release"
	LedgerTransactionKindProductionOutput     LedgerTransactionKind = "production_output"
	LedgerTransactionKindConsumption          LedgerTransactionKind = "consumption"
	LedgerTransactionKindWage                 LedgerTransactionKind = "wage"
	LedgerTransactionKindMaintenance          LedgerTransactionKind = "maintenance"
	LedgerTransactionKindTax                  LedgerTransactionKind = "tax"
	LedgerTransactionKindCanon                LedgerTransactionKind = "canon"
	LedgerTransactionKindTransfer             LedgerTransactionKind = "transfer"
	LedgerTransactionKindAuction              LedgerTransactionKind = "auction"
	LedgerTransactionKindReconciliation       LedgerTransactionKind = "reconciliation"
)

func (e *LedgerTransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerTransactionKind(s)
	case string:
		*e = LedgerTransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerTransactionKind: %T", src)
	}
	return nil
}

type NullLedgerTransactionKind struct {
	LedgerTransactionKind LedgerTransactionKind
	Valid                 bool // Valid is true if LedgerTransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerTransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerTransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerTransactionKind), nil
}

type WorldBatchStatus string

const (
	WorldBatchStatusQueued          WorldBatchStatus = "queued"
	WorldBatchStatusRunning         WorldBatchStatus = "running"
	WorldBatchStatusPausedNoFuel    WorldBatchStatus = "paused_no_fuel"
	WorldBatchStatusPausedNoWorkers WorldBatchStatus = "paused_no_workers"
	WorldBatchStatusCompleted       WorldBatchStatus = "completed"
	WorldBatchStatusCancelled       WorldBatchStatus = "cancelled"
)

func (e *WorldBatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldBatchStatus(s)
	case string:
		*e = WorldBatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldBatchStatus: %T", src)
	}
	return nil
}

type NullWorldBatchStatus struct {
	WorldBatchStatus WorldBatchStatus
	Valid            bool // Valid is true if WorldBatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorldBatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldBatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldBatchStatus), nil
}

type WorldBiome string

const (
	WorldBiomePlains   WorldBiome = "plains"
	WorldBiomeForest   WorldBiome = "forest"
	WorldBiomeDesert   WorldBiome = "desert"
	WorldBiomeMountain WorldBiome = "mountain"
	WorldBiomeOcean    WorldBiome = "ocean"
	WorldBiomeCoast    WorldBiome = "coast"
)

func (e *WorldBiome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldBiome(s)
	case string:
		*e = WorldBiome(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldBiome: %T", src)
	}
	return nil
}

type NullWorldBiome struct {
	WorldBiome WorldBiome
	Valid      bool // Valid is true if WorldBiome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldBiome) Scan(value interface{}) error {
	if value == nil {
		ns.WorldBiome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldBiome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldBiome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldBiome), nil
}

type WorldBuildingStatus string

const (
	WorldBuildingStatusUnderConstruction WorldBuildingStatus = "under_construction"
	WorldBuildingStatusOperational       WorldBuildingStatus = "operational"
	WorldBuildingStatusDamaged           WorldBuildingStatus = "damaged"
	WorldBuildingStatusInMaintenance     WorldBuildingStatus = "in_maintenance"
	WorldBuildingStatusAbandoned         WorldBuildingStatus = "abandoned"
	WorldBuildingStatusSeized            WorldBuildingStatus = "seized"
)

func (e *WorldBuildingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldBuildingStatus(s)
	case string:
		*e = WorldBuildingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldBuildingStatus: %T", src)
	}
	return nil
}

type NullWorldBuildingStatus struct {
	WorldBuildingStatus WorldBuildingStatus
	Valid               bool // Valid is true if WorldBuildingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldBuildingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorldBuildingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldBuildingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldBuildingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldBuildingStatus), nil
}

type WorldConcessionStatus string

const (
	WorldConcessionStatusActive     WorldConcessionStatus = "active"
	WorldConcessionStatusDelinquent WorldConcessionStatus = "delinquent"
	WorldConcessionStatusGrace      WorldConcessionStatus = "grace"
	WorldConcessionStatusReverted   WorldConcessionStatus = "reverted"
)

func (e *WorldConcessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldConcessionStatus(s)
	case string:
		*e = WorldConcessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldConcessionStatus: %T", src)
	}
	return nil
}

type NullWorldConcessionStatus struct {
	WorldConcessionStatus WorldConcessionStatus
	Valid                 bool // Valid is true if WorldConcessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldConcessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorldConcessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldConcessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldConcessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldConcessionStatus), nil
}

type WorldIngredientRole string

const (
	WorldIngredientRoleInput  WorldIngredientRole = "input"
	WorldIngredientRoleOutput WorldIngredientRole = "output"
)

func (e *WorldIngredientRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldIngredientRole(s)
	case string:
		*e = WorldIngredientRole(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldIngredientRole: %T", src)
	}
	return nil
}

type NullWorldIngredientRole struct {
	WorldIngredientRole WorldIngredientRole
	Valid               bool // Valid is true if WorldIngredientRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldIngredientRole) Scan(value interface{}) error {
	if value == nil {
		ns.WorldIngredientRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldIngredientRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldIngredientRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldIngredientRole), nil
}

type WorldNodeKind string

const (
	WorldNodeKindMine               WorldNodeKind = "mine"
	WorldNodeKindFactory            WorldNodeKind = "factory"
	WorldNodeKindWarehouse          WorldNodeKind = "warehouse"
	WorldNodeKindPort               WorldNodeKind = "port"
	WorldNodeKindStation            WorldNodeKind = "station"
	WorldNodeKindDistributionCenter WorldNodeKind = "distribution_center"
	WorldNodeKindJunction           WorldNodeKind = "junction"
	WorldNodeKindCityGate           WorldNodeKind = "city_gate"
)

func (e *WorldNodeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldNodeKind(s)
	case string:
		*e = WorldNodeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldNodeKind: %T", src)
	}
	return nil
}

type NullWorldNodeKind struct {
	WorldNodeKind WorldNodeKind
	Valid         bool // Valid is true if WorldNodeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldNodeKind) Scan(value interface{}) error {
	if value == nil {
		ns.WorldNodeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldNodeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldNodeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldNodeKind), nil
}

type WorldProductClass string

const (
	WorldProductClassBasic  WorldProductClass = "basic"
	WorldProductClassLuxury WorldProductClass = "luxury"
)

func (e *WorldProductClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldProductClass(s)
	case string:
		*e = WorldProductClass(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldProductClass: %T", src)
	}
	return nil
}

type NullWorldProductClass struct {
	WorldProductClass WorldProductClass
	Valid             bool // Valid is true if WorldProductClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldProductClass) Scan(value interface{}) error {
	if value == nil {
		ns.WorldProductClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldProductClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldProductClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldProductClass), nil
}

type WorldBuildingInventory struct {
	BuildingID   uuid.UUID
	ProductID    uuid.UUID
	Quantity     int64
	UpdatedAtSim int64
}

type WorldRecipeIngredient struct {
	RecipeID  uuid.UUID
	ProductID uuid.UUID
	Role      WorldIngredientRole
	Quantity  int64
}
