// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: power.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getBuildingForPower = `-- name: GetBuildingForPower :one

SELECT b.id, b.owner_account_id, b.status, b.building_type_id,
       (ppt.building_type_id IS NOT NULL)::bool AS is_power_plant
FROM world.buildings b
LEFT JOIN world.power_plant_types ppt ON ppt.building_type_id = b.building_type_id
WHERE b.id = $1
`

type GetBuildingForPowerRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	Status         WorldBuildingStatus
	BuildingTypeID uuid.UUID
	IsPowerPlant   bool
}

// ═════════════════════════════════════════════════════════════════════════════
// (2) Ofertas de generación y pujas de consumo.
// ═════════════════════════════════════════════════════════════════════════════
// GetBuildingForPower devuelve lo necesario para autorizar y validar una
// oferta/puja: dueño, estado y si el tipo es una central (fila en
// power_plant_types). pgx.ErrNoRows si el edificio no existe.
func (q *Queries) GetBuildingForPower(ctx context.Context, id uuid.UUID) (GetBuildingForPowerRow, error) {
	row := q.db.QueryRow(ctx, getBuildingForPower, id)
	var i GetBuildingForPowerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.Status,
		&i.BuildingTypeID,
		&i.IsPowerPlant,
	)
	return i, err
}

const getPowerLine = `-- name: GetPowerLine :one
SELECT id, owner_account_id, region_id, ST_AsGeoJSON(path)::text AS path_geojson,
       length_m, status, condition_pct, maintenance_paid_until_sim, updated_at_sim
FROM world.power_lines
WHERE id = $1
`

type GetPowerLineRow struct {
	ID                      uuid.UUID
	OwnerAccountID          uuid.UUID
	RegionID                uuid.UUID
	PathGeojson             string
	LengthM                 int32
	Status                  WorldPowerLineStatus
	ConditionPct            int32
	MaintenancePaidUntilSim int64
	UpdatedAtSim            int64
}

// GetPowerLine devuelve una línea con su trazado como GeoJSON.
func (q *Queries) GetPowerLine(ctx context.Context, id uuid.UUID) (GetPowerLineRow, error) {
	row := q.db.QueryRow(ctx, getPowerLine, id)
	var i GetPowerLineRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.PathGeojson,
		&i.LengthM,
		&i.Status,
		&i.ConditionPct,
		&i.MaintenancePaidUntilSim,
		&i.UpdatedAtSim,
	)
	return i, err
}

const getRegionBiome = `-- name: GetRegionBiome :one

SELECT biome FROM world.regions WHERE id = $1
`

// ═════════════════════════════════════════════════════════════════════════════
// (4) Emplazamiento: bioma de la región (regla requires_biome, ADR-025 §5).
// ═════════════════════════════════════════════════════════════════════════════
// GetRegionBiome devuelve el bioma de una región (regla de emplazamiento
// requires_biome de las hidroeléctricas: "ríos/agua" se materializa hoy como
// bioma coast; los ríos del worldgen siguen pendientes).
func (q *Queries) GetRegionBiome(ctx context.Context, id uuid.UUID) (WorldBiome, error) {
	row := q.db.QueryRow(ctx, getRegionBiome, id)
	var biome WorldBiome
	err := row.Scan(&biome)
	return biome, err
}

const getRegionContainingLine = `-- name: GetRegionContainingLine :one


SELECT id, name
FROM world.regions
WHERE ST_Contains(bounds, ST_SetSRID(ST_GeomFromGeoJSON($1::text), 0))
LIMIT 1
`

type GetRegionContainingLineRow struct {
	ID   uuid.UUID
	Name string
}

// =============================================================================
// Queries sqlc — red eléctrica regional (GDD 5.8 / ADR-025, Fase 3).
// Subpaquete internal/world/power (handlers en el gateway) y el barrido de
// mantenimiento de líneas de internal/world/enforcement (proceso engine).
// Comparten el sqlcgen del contexto world (la frontera de módulo es de CÓDIGO
// Go, no de esquema). El soporte de ledger (GetCashAccount, GetSinkAccount,
// InsertLedgerTransaction, InsertLedgerEntry) viene de land.sql.
//
// El tick del mercado spot NO vive aquí: es del Economy Balancer (GDD 18.1),
// con sus propias queries en internal/balancer/queries/power.sql.
// =============================================================================
// ═════════════════════════════════════════════════════════════════════════════
// (1) Líneas de transmisión (alta, catálogo).
// ═════════════════════════════════════════════════════════════════════════════
// GetRegionContainingLine resuelve la región cuyos bounds contienen ÍNTEGRO el
// trazado (GeoJSON LineString, SRID 0). pgx.ErrNoRows si ninguna lo contiene:
// el trazado cruza regiones o cae fuera del mundo (las interconexiones
// interregionales son expansión futura, GDD 22).
func (q *Queries) GetRegionContainingLine(ctx context.Context, path string) (GetRegionContainingLineRow, error) {
	row := q.db.QueryRow(ctx, getRegionContainingLine, path)
	var i GetRegionContainingLineRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertPowerLine = `-- name: InsertPowerLine :exec
INSERT INTO world.power_lines
       (id, owner_account_id, region_id, path, length_m,
        status, condition_pct, maintenance_paid_until_sim, updated_at_sim)
VALUES ($1, $2, $3,
        ST_SetSRID(ST_GeomFromGeoJSON($4::text), 0), $5,
        'operational', 100, $6, $6)
`

type InsertPowerLineParams struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	Path           string
	LengthM        int32
	SimNow         int64
}

// InsertPowerLine da de alta la línea (operational, condición 100). El
// mantenimiento arranca liquidado hasta el alta (maintenance_paid_until_sim).
func (q *Queries) InsertPowerLine(ctx context.Context, arg InsertPowerLineParams) error {
	_, err := q.db.Exec(ctx, insertPowerLine,
		arg.ID,
		arg.OwnerAccountID,
		arg.RegionID,
		arg.Path,
		arg.LengthM,
		arg.SimNow,
	)
	return err
}

const lineLengthM = `-- name: LineLengthM :one
SELECT GREATEST(1, round(ST_Length(ST_SetSRID(ST_GeomFromGeoJSON($1::text), 0))))::int AS length_m
`

// LineLengthM mide el trazado en metros de mundo (redondeo, mínimo 1).
func (q *Queries) LineLengthM(ctx context.Context, path string) (int32, error) {
	row := q.db.QueryRow(ctx, lineLengthM, path)
	var length_m int32
	err := row.Scan(&length_m)
	return length_m, err
}

const listPowerDispatchesForBuilding = `-- name: ListPowerDispatchesForBuilding :many
SELECT region_id, tick_sim, building_id, owner_account_id, role,
       units, unit_price, amount
FROM world.power_dispatches
WHERE building_id = $1
  AND ($2::bigint IS NULL OR tick_sim < $2)
ORDER BY tick_sim DESC
LIMIT $3
`

type ListPowerDispatchesForBuildingParams struct {
	BuildingID    uuid.UUID
	BeforeTickSim *int64
	PageLimit     int32
}

// ListPowerDispatchesForBuilding devuelve el despacho/consumo de un edificio
// (la autorización por propiedad se resuelve antes con GetBuildingForPower).
func (q *Queries) ListPowerDispatchesForBuilding(ctx context.Context, arg ListPowerDispatchesForBuildingParams) ([]WorldPowerDispatch, error) {
	rows, err := q.db.Query(ctx, listPowerDispatchesForBuilding, arg.BuildingID, arg.BeforeTickSim, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldPowerDispatch
	for rows.Next() {
		var i WorldPowerDispatch
		if err := rows.Scan(
			&i.RegionID,
			&i.TickSim,
			&i.BuildingID,
			&i.OwnerAccountID,
			&i.Role,
			&i.Units,
			&i.UnitPrice,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerLines = `-- name: ListPowerLines :many
SELECT id, owner_account_id, region_id, ST_AsGeoJSON(path)::text AS path_geojson,
       length_m, status, condition_pct, maintenance_paid_until_sim, updated_at_sim
FROM world.power_lines
WHERE ($1::uuid IS NULL OR region_id = $1)
  AND ($2::uuid IS NULL OR id > $2)
ORDER BY id
LIMIT $3
`

type ListPowerLinesParams struct {
	RegionID  *uuid.UUID
	AfterID   *uuid.UUID
	PageLimit int32
}

type ListPowerLinesRow struct {
	ID                      uuid.UUID
	OwnerAccountID          uuid.UUID
	RegionID                uuid.UUID
	PathGeojson             string
	LengthM                 int32
	Status                  WorldPowerLineStatus
	ConditionPct            int32
	MaintenancePaidUntilSim int64
	UpdatedAtSim            int64
}

// ListPowerLines pagina el catálogo (visible para todos, como las terminales),
// con filtro opcional por región. Keyset por id (UUIDv7).
func (q *Queries) ListPowerLines(ctx context.Context, arg ListPowerLinesParams) ([]ListPowerLinesRow, error) {
	rows, err := q.db.Query(ctx, listPowerLines, arg.RegionID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPowerLinesRow
	for rows.Next() {
		var i ListPowerLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.RegionID,
			&i.PathGeojson,
			&i.LengthM,
			&i.Status,
			&i.ConditionPct,
			&i.MaintenancePaidUntilSim,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerLinesDueMaintenance = `-- name: ListPowerLinesDueMaintenance :many

SELECT id
FROM world.power_lines
WHERE status = 'operational'
  AND maintenance_paid_until_sim <= $1::bigint - 86400
ORDER BY id
LIMIT $2
`

type ListPowerLinesDueMaintenanceParams struct {
	SimNow    int64
	PageLimit int32
}

// ═════════════════════════════════════════════════════════════════════════════
// (5) Mantenimiento de líneas (barrido de world/enforcement, patrón 0011).
// ═════════════════════════════════════════════════════════════════════════════
// ListPowerLinesDueMaintenance lista líneas operativas con >= 1 día-sim de
// mantenimiento vencido (solo ids; el lock va por línea).
func (q *Queries) ListPowerLinesDueMaintenance(ctx context.Context, arg ListPowerLinesDueMaintenanceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPowerLinesDueMaintenance, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerSpotTicks = `-- name: ListPowerSpotTicks :many

SELECT region_id, tick_sim, interval_sim, closing_price,
       demand_units, supplied_units, curtailed_units, curtailed_buildings
FROM world.power_spot_ticks
WHERE region_id = $1
  AND ($2::bigint IS NULL OR tick_sim < $2)
ORDER BY tick_sim DESC
LIMIT $3
`

type ListPowerSpotTicksParams struct {
	RegionID      uuid.UUID
	BeforeTickSim *int64
	PageLimit     int32
}

type ListPowerSpotTicksRow struct {
	RegionID           uuid.UUID
	TickSim            int64
	IntervalSim        int64
	ClosingPrice       int64
	DemandUnits        int64
	SuppliedUnits      int64
	CurtailedUnits     int64
	CurtailedBuildings int32
}

// ═════════════════════════════════════════════════════════════════════════════
// (3) Lecturas del contrato: histórico del spot y "mi consumo".
// ═════════════════════════════════════════════════════════════════════════════
// ListPowerSpotTicks devuelve los últimos ticks de una región (precio de
// cierre, despacho y recorte), más recientes primero.
func (q *Queries) ListPowerSpotTicks(ctx context.Context, arg ListPowerSpotTicksParams) ([]ListPowerSpotTicksRow, error) {
	rows, err := q.db.Query(ctx, listPowerSpotTicks, arg.RegionID, arg.BeforeTickSim, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPowerSpotTicksRow
	for rows.Next() {
		var i ListPowerSpotTicksRow
		if err := rows.Scan(
			&i.RegionID,
			&i.TickSim,
			&i.IntervalSim,
			&i.ClosingPrice,
			&i.DemandUnits,
			&i.SuppliedUnits,
			&i.CurtailedUnits,
			&i.CurtailedBuildings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPowerLineForMaintenance = `-- name: LockPowerLineForMaintenance :one
SELECT id, owner_account_id, region_id, length_m, status, condition_pct,
       maintenance_paid_until_sim
FROM world.power_lines
WHERE id = $1
  AND status = 'operational'
  AND maintenance_paid_until_sim <= $2::bigint - 86400
FOR UPDATE SKIP LOCKED
`

type LockPowerLineForMaintenanceParams struct {
	ID     uuid.UUID
	SimNow int64
}

type LockPowerLineForMaintenanceRow struct {
	ID                      uuid.UUID
	OwnerAccountID          uuid.UUID
	RegionID                uuid.UUID
	LengthM                 int32
	Status                  WorldPowerLineStatus
	ConditionPct            int32
	MaintenancePaidUntilSim int64
}

// LockPowerLineForMaintenance re-bloquea una línea candidata (FOR UPDATE SKIP
// LOCKED: varias instancias barren en paralelo sin pisarse). pgx.ErrNoRows si
// otra instancia la tomó o ya no aplica.
func (q *Queries) LockPowerLineForMaintenance(ctx context.Context, arg LockPowerLineForMaintenanceParams) (LockPowerLineForMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, lockPowerLineForMaintenance, arg.ID, arg.SimNow)
	var i LockPowerLineForMaintenanceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.LengthM,
		&i.Status,
		&i.ConditionPct,
		&i.MaintenancePaidUntilSim,
	)
	return i, err
}

const updatePowerLineMaintenance = `-- name: UpdatePowerLineMaintenance :exec
UPDATE world.power_lines
   SET maintenance_paid_until_sim = $1,
       condition_pct = $2,
       status = $3::world.power_line_status,
       updated_at_sim = $4
 WHERE id = $5
`

type UpdatePowerLineMaintenanceParams struct {
	PaidUntilSim int64
	ConditionPct int32
	Status       WorldPowerLineStatus
	SimNow       int64
	ID           uuid.UUID
}

// UpdatePowerLineMaintenance persiste el resultado del barrido: marcador
// avanzado (cada día vencido se salda exactamente una vez), condición
// recuperada o degradada, y el estado (abandoned = deja de conducir, terminal).
func (q *Queries) UpdatePowerLineMaintenance(ctx context.Context, arg UpdatePowerLineMaintenanceParams) error {
	_, err := q.db.Exec(ctx, updatePowerLineMaintenance,
		arg.PaidUntilSim,
		arg.ConditionPct,
		arg.Status,
		arg.SimNow,
		arg.ID,
	)
	return err
}

const upsertPowerBid = `-- name: UpsertPowerBid :exec
INSERT INTO world.power_bids (building_id, unit_price, updated_at_sim)
VALUES ($1, $2, $3)
ON CONFLICT (building_id) DO UPDATE
   SET unit_price = EXCLUDED.unit_price, updated_at_sim = EXCLUDED.updated_at_sim
`

type UpsertPowerBidParams struct {
	BuildingID uuid.UUID
	UnitPrice  int64
	SimNow     int64
}

// UpsertPowerBid fija la puja máxima de un consumidor (prioridad inversa del
// recorte y techo personal; sin fila rige II_POWER_DEFAULT_BID_PRICE).
func (q *Queries) UpsertPowerBid(ctx context.Context, arg UpsertPowerBidParams) error {
	_, err := q.db.Exec(ctx, upsertPowerBid, arg.BuildingID, arg.UnitPrice, arg.SimNow)
	return err
}

const upsertPowerOffer = `-- name: UpsertPowerOffer :exec
INSERT INTO world.power_offers (building_id, unit_price, updated_at_sim)
VALUES ($1, $2, $3)
ON CONFLICT (building_id) DO UPDATE
   SET unit_price = EXCLUDED.unit_price, updated_at_sim = EXCLUDED.updated_at_sim
`

type UpsertPowerOfferParams struct {
	BuildingID uuid.UUID
	UnitPrice  int64
	SimNow     int64
}

// UpsertPowerOffer fija el precio de oferta de una central. Sin fila, la
// central no participa del spot (ofertar es decisión del jugador).
func (q *Queries) UpsertPowerOffer(ctx context.Context, arg UpsertPowerOfferParams) error {
	_, err := q.db.Exec(ctx, upsertPowerOffer, arg.BuildingID, arg.UnitPrice, arg.SimNow)
	return err
}
