// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: production.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addBuildingInventory = `-- name: AddBuildingInventory :exec
INSERT INTO world.building_inventories (building_id, product_id, quantity, updated_at_sim)
VALUES ($1, $2, $3, $4)
ON CONFLICT (building_id, product_id)
DO UPDATE SET quantity = world.building_inventories.quantity + $3,
              updated_at_sim = $4
`

type AddBuildingInventoryParams struct {
	BuildingID uuid.UUID
	ProductID  uuid.UUID
	Amount     int64
	SimNow     int64
}

// AddBuildingInventory suma una cantidad (>= 0) al inventario físico de un
// producto (alta por producción/extracción), creando la fila si no existía.
func (q *Queries) AddBuildingInventory(ctx context.Context, arg AddBuildingInventoryParams) error {
	_, err := q.db.Exec(ctx, addBuildingInventory,
		arg.BuildingID,
		arg.ProductID,
		arg.Amount,
		arg.SimNow,
	)
	return err
}

const advanceBatch = `-- name: AdvanceBatch :one
UPDATE world.production_batches
   SET batches_done = batches_done + 1,
       status = $1::world.batch_status,
       started_at_sim = $2,
       updated_at_sim = $3
 WHERE id = $4
RETURNING id, building_id, recipe_id, batches_queued, batches_done, status,
          queue_position, started_at_sim
`

type AdvanceBatchParams struct {
	Status       WorldBatchStatus
	StartedAtSim *int64
	SimNow       int64
	ID           uuid.UUID
}

type AdvanceBatchRow struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	BatchesDone   int32
	Status        WorldBatchStatus
	QueuePosition int32
	StartedAtSim  *int64
}

// AdvanceBatch cierra un batch del lote: incrementa batches_done y fija el
// estado y el reloj del siguiente (running con started_at_sim, o completed con
// NULL cuando batches_done alcanza batches_queued).
func (q *Queries) AdvanceBatch(ctx context.Context, arg AdvanceBatchParams) (AdvanceBatchRow, error) {
	row := q.db.QueryRow(ctx, advanceBatch,
		arg.Status,
		arg.StartedAtSim,
		arg.SimNow,
		arg.ID,
	)
	var i AdvanceBatchRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
	)
	return i, err
}

const completeConstruction = `-- name: CompleteConstruction :one
UPDATE world.buildings
   SET status = 'operational', updated_at_sim = $1
 WHERE id = $2
RETURNING id, owner_account_id, region_id, building_type_id
`

type CompleteConstructionParams struct {
	SimNow int64
	ID     uuid.UUID
}

type CompleteConstructionRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	BuildingTypeID uuid.UUID
}

// CompleteConstruction pasa el edificio a operational con la marca de sim-time
// de la finalización.
func (q *Queries) CompleteConstruction(ctx context.Context, arg CompleteConstructionParams) (CompleteConstructionRow, error) {
	row := q.db.QueryRow(ctx, completeConstruction, arg.SimNow, arg.ID)
	var i CompleteConstructionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.BuildingTypeID,
	)
	return i, err
}

const consumeBuildingInventory = `-- name: ConsumeBuildingInventory :exec
UPDATE world.building_inventories
   SET quantity = quantity - $1, updated_at_sim = $2
 WHERE building_id = $3 AND product_id = $4
`

type ConsumeBuildingInventoryParams struct {
	Amount     int64
	SimNow     int64
	BuildingID uuid.UUID
	ProductID  uuid.UUID
}

// ConsumeBuildingInventory descuenta una cantidad del inventario físico de un
// producto (consumo de insumos/combustible). La fila debe existir y cubrir la
// cantidad (comprobado antes); el CHECK quantity >= 0 respalda la invariante.
// No usa UPSERT: la contrapartida especulativa del INSERT evaluaría el CHECK
// sobre un valor negativo antes de resolver el conflicto.
func (q *Queries) ConsumeBuildingInventory(ctx context.Context, arg ConsumeBuildingInventoryParams) error {
	_, err := q.db.Exec(ctx, consumeBuildingInventory,
		arg.Amount,
		arg.SimNow,
		arg.BuildingID,
		arg.ProductID,
	)
	return err
}

const countActiveBatches = `-- name: CountActiveBatches :one
SELECT count(*)::bigint AS total
FROM world.production_batches
WHERE building_id = $1
  AND status IN ('running', 'paused_no_fuel', 'paused_no_workers', 'paused_no_power')
`

// CountActiveBatches cuenta los lotes en curso o pausados de un edificio (para
// decidir si el nuevo lote se promueve a running al encolar). Los TRES estados
// de pausa cuentan: un lote pausado sigue siendo el activo del edificio
// (invariante de un lote en curso por edificio — sin él, un lote encolado
// durante una pausa por suministro correría en paralelo al reanudarse esta).
func (q *Queries) CountActiveBatches(ctx context.Context, buildingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBatches, buildingID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createStockFreeAccount = `-- name: CreateStockFreeAccount :one
INSERT INTO ledger.accounts (id, kind, owner_account_id, product_id, warehouse_building_id)
VALUES ($1, 'stock_free', $2, $3, $4)
RETURNING id, balance
`

type CreateStockFreeAccountParams struct {
	ID                  uuid.UUID
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
}

type CreateStockFreeAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// CreateStockFreeAccount crea la cuenta stock_free de (dueño, producto, almacén)
// on-demand (la unicidad parcial ux_accounts_stock_free respalda la clave).
func (q *Queries) CreateStockFreeAccount(ctx context.Context, arg CreateStockFreeAccountParams) (CreateStockFreeAccountRow, error) {
	row := q.db.QueryRow(ctx, createStockFreeAccount,
		arg.ID,
		arg.OwnerAccountID,
		arg.ProductID,
		arg.WarehouseBuildingID,
	)
	var i CreateStockFreeAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const createWorldSourceAccount = `-- name: CreateWorldSourceAccount :one
INSERT INTO ledger.accounts (id, kind, owner_account_id, product_id)
VALUES ($1, 'world_source', $2, $3)
RETURNING id, balance
`

type CreateWorldSourceAccountParams struct {
	ID             uuid.UUID
	OwnerAccountID *uuid.UUID
	ProductID      *uuid.UUID
}

type CreateWorldSourceAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// CreateWorldSourceAccount crea la cuenta world_source de un producto (titular:
// banco central; NULL admitido como cuenta pura de sistema si aún no hay banco).
func (q *Queries) CreateWorldSourceAccount(ctx context.Context, arg CreateWorldSourceAccountParams) (CreateWorldSourceAccountRow, error) {
	row := q.db.QueryRow(ctx, createWorldSourceAccount, arg.ID, arg.OwnerAccountID, arg.ProductID)
	var i CreateWorldSourceAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const decrementDeposit = `-- name: DecrementDeposit :one
UPDATE world.resource_deposits
   SET remaining_amount = remaining_amount - $1,
       updated_at_sim = $2
 WHERE id = $3
RETURNING remaining_amount
`

type DecrementDepositParams struct {
	Amount int64
	SimNow int64
	ID     uuid.UUID
}

// DecrementDeposit descuenta lo extraído del yacimiento (recurso finito, GDD
// 10); el CHECK remaining_amount >= 0 respalda la no-negatividad.
func (q *Queries) DecrementDeposit(ctx context.Context, arg DecrementDepositParams) (int64, error) {
	row := q.db.QueryRow(ctx, decrementDeposit, arg.Amount, arg.SimNow, arg.ID)
	var remaining_amount int64
	err := row.Scan(&remaining_amount)
	return remaining_amount, err
}

const getBuildingInventoryQty = `-- name: GetBuildingInventoryQty :one

SELECT COALESCE(
    (SELECT quantity FROM world.building_inventories
      WHERE building_id = $1 AND product_id = $2),
    0)::bigint AS quantity
`

type GetBuildingInventoryQtyParams struct {
	BuildingID uuid.UUID
	ProductID  uuid.UUID
}

// ─── Inventario físico del edificio ───────────────────────────────────────────
// GetBuildingInventoryQty devuelve la cantidad física de un producto en un
// edificio (0 si no hay fila).
func (q *Queries) GetBuildingInventoryQty(ctx context.Context, arg GetBuildingInventoryQtyParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBuildingInventoryQty, arg.BuildingID, arg.ProductID)
	var quantity int64
	err := row.Scan(&quantity)
	return quantity, err
}

const getProductionBatchWithOwner = `-- name: GetProductionBatchWithOwner :one
SELECT b.id, b.building_id, b.recipe_id, b.batches_queued, b.batches_done,
       b.status, b.queue_position, b.started_at_sim,
       r.batch_sim_seconds, bld.level, bt.level_curve, bld.owner_account_id
FROM world.production_batches b
JOIN world.recipes r ON r.id = b.recipe_id
JOIN world.buildings bld ON bld.id = b.building_id
JOIN world.building_types bt ON bt.id = bld.building_type_id
WHERE b.id = $1
`

type GetProductionBatchWithOwnerRow struct {
	ID              uuid.UUID
	BuildingID      uuid.UUID
	RecipeID        uuid.UUID
	BatchesQueued   int32
	BatchesDone     int32
	Status          WorldBatchStatus
	QueuePosition   int32
	StartedAtSim    *int64
	BatchSimSeconds int64
	Level           int32
	LevelCurve      []byte
	OwnerAccountID  uuid.UUID
}

// GetProductionBatchWithOwner devuelve un lote con el dueño de su edificio (para
// la autorización por propiedad de DELETE sin buildingId en la ruta) y los datos
// para derivar progreso. pgx.ErrNoRows si no existe.
func (q *Queries) GetProductionBatchWithOwner(ctx context.Context, id uuid.UUID) (GetProductionBatchWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getProductionBatchWithOwner, id)
	var i GetProductionBatchWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
		&i.BatchSimSeconds,
		&i.Level,
		&i.LevelCurve,
		&i.OwnerAccountID,
	)
	return i, err
}

const getProductionRecipe = `-- name: GetProductionRecipe :one
SELECT id, building_type_id, code, batch_sim_seconds,
       fuel_product_id, fuel_per_batch, workers_required, min_city_level
FROM world.recipes
WHERE id = $1
`

type GetProductionRecipeRow struct {
	ID              uuid.UUID
	BuildingTypeID  uuid.UUID
	Code            string
	BatchSimSeconds int64
	FuelProductID   *uuid.UUID
	FuelPerBatch    int64
	WorkersRequired int32
	MinCityLevel    int32
}

// GetProductionRecipe devuelve la receta con TODOS los campos de producción
// (combustible y trabajadores), para validar el encolado y procesar el lote.
// pgx.ErrNoRows si no existe.
func (q *Queries) GetProductionRecipe(ctx context.Context, id uuid.UUID) (GetProductionRecipeRow, error) {
	row := q.db.QueryRow(ctx, getProductionRecipe, id)
	var i GetProductionRecipeRow
	err := row.Scan(
		&i.ID,
		&i.BuildingTypeID,
		&i.Code,
		&i.BatchSimSeconds,
		&i.FuelProductID,
		&i.FuelPerBatch,
		&i.WorkersRequired,
		&i.MinCityLevel,
	)
	return i, err
}

const getStockFreeAccount = `-- name: GetStockFreeAccount :one

SELECT id, balance FROM ledger.accounts
WHERE kind = 'stock_free'
  AND owner_account_id = $1
  AND product_id = $2
  AND warehouse_building_id = $3
`

type GetStockFreeAccountParams struct {
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
}

type GetStockFreeAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// ─── Soporte de ledger para stock (ADR-022) ───────────────────────────────────
// GetStockFreeAccount devuelve la cuenta stock_free de (dueño, producto,
// almacén); pgx.ErrNoRows si no existe.
func (q *Queries) GetStockFreeAccount(ctx context.Context, arg GetStockFreeAccountParams) (GetStockFreeAccountRow, error) {
	row := q.db.QueryRow(ctx, getStockFreeAccount, arg.OwnerAccountID, arg.ProductID, arg.WarehouseBuildingID)
	var i GetStockFreeAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getWorldSourceAccount = `-- name: GetWorldSourceAccount :one
SELECT id, balance FROM ledger.accounts
WHERE kind = 'world_source' AND product_id = $1
LIMIT 1
`

type GetWorldSourceAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// GetWorldSourceAccount devuelve la cuenta world_source (contrapartida física
// del banco central, ADR-022) de un producto; pgx.ErrNoRows si no existe.
func (q *Queries) GetWorldSourceAccount(ctx context.Context, productID *uuid.UUID) (GetWorldSourceAccountRow, error) {
	row := q.db.QueryRow(ctx, getWorldSourceAccount, productID)
	var i GetWorldSourceAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getWorldSourceOwner = `-- name: GetWorldSourceOwner :one
SELECT owner_account_id FROM ledger.accounts
WHERE kind = 'world_source' AND owner_account_id IS NOT NULL
LIMIT 1
`

// GetWorldSourceOwner devuelve el titular (banco central) de cualquier cuenta
// world_source existente, para crear las de productos nuevos con el mismo
// titular; pgx.ErrNoRows si aún no hay ninguna.
func (q *Queries) GetWorldSourceOwner(ctx context.Context) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getWorldSourceOwner)
	var owner_account_id *uuid.UUID
	err := row.Scan(&owner_account_id)
	return owner_account_id, err
}

const insertProductionBatch = `-- name: InsertProductionBatch :one
INSERT INTO world.production_batches (
    id, building_id, recipe_id, batches_queued, batches_done, status,
    queue_position, updated_at_sim)
VALUES (
    $1, $2, $3,
    $4, 0, 'queued', $5,
    $6)
RETURNING id, building_id, recipe_id, batches_queued, batches_done, status,
          queue_position, started_at_sim
`

type InsertProductionBatchParams struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	QueuePosition int32
	UpdatedAtSim  int64
}

type InsertProductionBatchRow struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	BatchesDone   int32
	Status        WorldBatchStatus
	QueuePosition int32
	StartedAtSim  *int64
}

// InsertProductionBatch crea un lote encolado (queued).
func (q *Queries) InsertProductionBatch(ctx context.Context, arg InsertProductionBatchParams) (InsertProductionBatchRow, error) {
	row := q.db.QueryRow(ctx, insertProductionBatch,
		arg.ID,
		arg.BuildingID,
		arg.RecipeID,
		arg.BatchesQueued,
		arg.QueuePosition,
		arg.UpdatedAtSim,
	)
	var i InsertProductionBatchRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
	)
	return i, err
}

const listActiveBatchIDs = `-- name: ListActiveBatchIDs :many

SELECT b.id
FROM world.production_batches b
JOIN world.buildings bld ON bld.id = b.building_id
WHERE b.status IN ('running', 'paused_no_fuel', 'paused_no_workers', 'paused_no_power')
  AND bld.status = 'operational'
  AND ($1::uuid IS NULL OR b.id > $1)
ORDER BY b.id
LIMIT $2
`

type ListActiveBatchIDsParams struct {
	AfterID   *uuid.UUID
	PageLimit int32
}

// ═════════════════════════════════════════════════════════════════════════════
// (3) Motor de producción: barrido analítico de lotes vencidos.
// ═════════════════════════════════════════════════════════════════════════════
// ListActiveBatchIDs lista los lotes running o pausados de edificios operativos
// (candidatos del barrido). El due-ness (progreso analítico con la eficiencia
// del nivel) se decide en Go tras bloquear cada lote. after_id es el cursor de
// CONTINUACIÓN entre barridos (v1.10): sin él, una población de lotes pausados
// estable >= page_limit al principio del orden por id (UUIDv7 ≈ antigüedad)
// ocuparía todas las pasadas y los lotes posteriores no se barrerían jamás; el
// worker avanza el cursor por pasadas y lo reinicia al agotar la lista.
func (q *Queries) ListActiveBatchIDs(ctx context.Context, arg ListActiveBatchIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveBatchIDs, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueConstructionIDs = `-- name: ListDueConstructionIDs :many


SELECT id
FROM world.buildings
WHERE status = 'under_construction'
  AND updated_at_sim + $1::bigint <= $2::bigint
ORDER BY id
LIMIT $3
`

type ListDueConstructionIDsParams struct {
	BuildSimSeconds int64
	SimNow          int64
	PageLimit       int32
}

// =============================================================================
// Imperio Industrial — queries sqlc del subpaquete world/production (ADR-020).
// Cola de producción (GDD 6), motor event-driven de progreso ANALÍTICO (GDD
// 1.1) y reconciliación física↔contable (ADR-004). Cierra el lazo
// construir→producir→vender: cada lote completado mueve a la vez el plano
// FÍSICO (world.building_inventories, world.resource_deposits, buildings.
// fuel_stock) y el CONTABLE (asientos production_output/consumption/wage sobre
// ledger.*), en UNA transacción SERIALIZABLE con outbox.Emit (GDD 15.3).
//
// La frontera de módulo es de código Go, no de esquema: estas queries leen
// world.* y asientan en ledger.* reutilizando el soporte de ledger COMPARTIDO
// de land.sql (GetCashAccount, GetSinkAccount, InsertLedgerTransaction,
// InsertLedgerEntry) y ListRecipeIngredients de catalog.sql — el paquete
// sqlcgen del contexto es único. Aquí solo se AÑADEN las queries propias de la
// producción, con nombres que no colisionan con los ya existentes.
//
// Geometrías: SRID 0 planar (ADR-019). La extracción usa el nodo del grafo del
// edificio (world.network_nodes, centroide del footprint) como origen físico y
// ST_DWithin para localizar el yacimiento dentro del radio de influencia.
// =============================================================================
// ═════════════════════════════════════════════════════════════════════════════
// (1) Barrido de CONSTRUCCIÓN: under_construction → operational tras un tiempo
//
//	fijo de construcción (II_BUILD_SIM_SECONDS) desde la marca updated_at_sim.
//
// ═════════════════════════════════════════════════════════════════════════════
// ListDueConstructionIDs lista los edificios en construcción cuyo tiempo fijo de
// construcción ya venció (updated_at_sim + build_sim_seconds <= simNow).
func (q *Queries) ListDueConstructionIDs(ctx context.Context, arg ListDueConstructionIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueConstructionIDs, arg.BuildSimSeconds, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionBatches = `-- name: ListProductionBatches :many

SELECT b.id, b.building_id, b.recipe_id, b.batches_queued, b.batches_done,
       b.status, b.queue_position, b.started_at_sim,
       r.batch_sim_seconds, bld.level, bt.level_curve
FROM world.production_batches b
JOIN world.recipes r ON r.id = b.recipe_id
JOIN world.buildings bld ON bld.id = b.building_id
JOIN world.building_types bt ON bt.id = bld.building_type_id
WHERE b.building_id = $1
  AND ($2::world.batch_status IS NULL OR b.status = $2::world.batch_status)
  AND ($3::uuid IS NULL OR b.id > $3::uuid)
ORDER BY b.id
LIMIT $4
`

type ListProductionBatchesParams struct {
	BuildingID uuid.UUID
	Status     NullWorldBatchStatus
	AfterID    *uuid.UUID
	PageLimit  int32
}

type ListProductionBatchesRow struct {
	ID              uuid.UUID
	BuildingID      uuid.UUID
	RecipeID        uuid.UUID
	BatchesQueued   int32
	BatchesDone     int32
	Status          WorldBatchStatus
	QueuePosition   int32
	StartedAtSim    *int64
	BatchSimSeconds int64
	Level           int32
	LevelCurve      []byte
}

// ═════════════════════════════════════════════════════════════════════════════
// (2) Cola de producción: handlers GET/POST/DELETE del contrato.
// ═════════════════════════════════════════════════════════════════════════════
// ListProductionBatches devuelve los lotes de un edificio con filtro opcional
// por estado y paginación keyset por id. Incluye batch_sim_seconds de la receta,
// el nivel del edificio y la level_curve del tipo para DERIVAR analíticamente
// progress_pct/eta_sim del lote en curso en la capa de servicio (no persisten).
func (q *Queries) ListProductionBatches(ctx context.Context, arg ListProductionBatchesParams) ([]ListProductionBatchesRow, error) {
	rows, err := q.db.Query(ctx, listProductionBatches,
		arg.BuildingID,
		arg.Status,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductionBatchesRow
	for rows.Next() {
		var i ListProductionBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.RecipeID,
			&i.BatchesQueued,
			&i.BatchesDone,
			&i.Status,
			&i.QueuePosition,
			&i.StartedAtSim,
			&i.BatchSimSeconds,
			&i.Level,
			&i.LevelCurve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockDiscrepancies = `-- name: ListStockDiscrepancies :many

WITH physical AS (
    SELECT building_id, product_id, SUM(qty)::bigint AS qty
    FROM (
        SELECT building_id, product_id, quantity AS qty
        FROM world.building_inventories
        UNION ALL
        -- Cargamentos de un CCRI de bienes (contract_id): atribuidos al almacén de
        -- origen vía la cuenta reservada del contrato.
        SELECT a.warehouse_building_id AS building_id, a.product_id, sh.quantity AS qty
        FROM world.shipments sh
        JOIN ledger.contracts c ON c.id = sh.contract_id
        JOIN ledger.accounts  a ON a.id = c.stock_reserve_account_id
        WHERE sh.status IN ('in_warehouse', 'in_transit', 'at_terminal')
          AND a.warehouse_building_id IS NOT NULL
        UNION ALL
        -- Cargamentos de un CCRI-Flete PURO (freight_contract_id sin contract_id):
        -- atribuidos al almacén de la cuenta de custodia (su origen). Los que
        -- componen con una venta ya se cuentan por la rama anterior (contract_id).
        SELECT a.warehouse_building_id AS building_id, a.product_id, sh.quantity AS qty
        FROM world.shipments sh
        JOIN ledger.freight_contracts fc ON fc.id = sh.freight_contract_id
        JOIN ledger.accounts a ON a.id = fc.custody_account_id
        WHERE sh.status IN ('in_warehouse', 'in_transit', 'at_terminal')
          AND sh.contract_id IS NULL
          AND a.warehouse_building_id IS NOT NULL
    ) parts
    GROUP BY building_id, product_id
),
ledger_stock AS (
    SELECT warehouse_building_id, product_id, SUM(balance) AS total
    FROM ledger.accounts
    WHERE kind IN ('stock_free', 'stock_reserved', 'custody') AND warehouse_building_id IS NOT NULL
    GROUP BY warehouse_building_id, product_id
)
SELECT COALESCE(p.building_id, l.warehouse_building_id) AS building_id,
       COALESCE(p.product_id, l.product_id) AS product_id,
       COALESCE(p.qty, 0)::bigint AS physical,
       COALESCE(l.total, 0)::bigint AS ledger
FROM physical p
FULL OUTER JOIN ledger_stock l
     ON l.warehouse_building_id = p.building_id AND l.product_id = p.product_id
WHERE COALESCE(p.qty, 0) <> COALESCE(l.total, 0)
LIMIT $1
`

type ListStockDiscrepanciesRow struct {
	BuildingID uuid.UUID
	ProductID  uuid.UUID
	Physical   int64
	Ledger     int64
}

// ═════════════════════════════════════════════════════════════════════════════
// (4) Reconciliación física↔contable (ADR-004): el stock físico de cada
//
//	(edificio, producto) debe igualar el stock COMPROMETIBLE contable de ese
//	almacén — la suma de saldos stock_free + stock_reserved. El stock físico
//	tiene DOS ubicaciones desde el Incremento 3 (logística física): el
//	inventario del edificio (world.building_inventories) MÁS los cargamentos
//	EN VUELO cuyo stock ya dejó el almacén (world.shipments): el
//	shipment_creator descuenta building_inventories al crear el cargamento
//	(in_warehouse), de modo que el stock reservado vive en el cargamento desde
//	su creación —no sólo tras el despacho—. Cada cargamento se re-atribuye al
//	almacén de ORIGEN (la cuenta stock_reserved del contrato conserva ahí su
//	warehouse_building_id hasta la liquidación), cerrando el balance:
//	físico(building_inventories) + físico(cargamentos in-vuelo) = free+reserved.
//	Se cuentan los cargamentos in_warehouse/in_transit/at_terminal (los
//	delivered ya están en building_inventories del destino; los
//	released_in_situ nunca salieron del building_inventories de origen). Se
//	EXCLUYE custody (flete, Fase 2). Resultado esperado en reposo: CERO filas.
//
// ═════════════════════════════════════════════════════════════════════════════
// ListStockDiscrepancies lista las divergencias físico↔contable en ambos
// sentidos (FULL OUTER JOIN): el físico agrega inventario de edificio + stock de
// cargamentos en vuelo por (almacén de origen, producto); el contable, el
// comprometible (stock_free + stock_reserved + custody). Desde el Incremento 8
// (CCRI-Flete) el stock en CUSTODIA cuenta EN AMBOS lados: en el contable como
// 'custody' (kind incluido abajo) y en el físico como el cargamento de flete
// (freight_contract_id) atribuido al almacén de la cuenta de custodia (que
// conserva su warehouse_building_id de origen). Así un flete en vuelo no rompe la
// reconciliación (queda cuadrado en el almacén de origen hasta la liquidación).
func (q *Queries) ListStockDiscrepancies(ctx context.Context, pageLimit int32) ([]ListStockDiscrepanciesRow, error) {
	rows, err := q.db.Query(ctx, listStockDiscrepancies, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockDiscrepanciesRow
	for rows.Next() {
		var i ListStockDiscrepanciesRow
		if err := rows.Scan(
			&i.BuildingID,
			&i.ProductID,
			&i.Physical,
			&i.Ledger,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBatchForCancel = `-- name: LockBatchForCancel :one
SELECT b.id, b.building_id, b.batches_queued, b.batches_done, b.status,
       b.queue_position, b.started_at_sim, bld.owner_account_id
FROM world.production_batches b
JOIN world.buildings bld ON bld.id = b.building_id
WHERE b.id = $1
FOR UPDATE OF b
`

type LockBatchForCancelRow struct {
	ID             uuid.UUID
	BuildingID     uuid.UUID
	BatchesQueued  int32
	BatchesDone    int32
	Status         WorldBatchStatus
	QueuePosition  int32
	StartedAtSim   *int64
	OwnerAccountID uuid.UUID
}

// LockBatchForCancel bloquea el lote y devuelve el dueño de su edificio para
// cancelar bajo lock (FOR UPDATE del lote). pgx.ErrNoRows si no existe.
func (q *Queries) LockBatchForCancel(ctx context.Context, id uuid.UUID) (LockBatchForCancelRow, error) {
	row := q.db.QueryRow(ctx, lockBatchForCancel, id)
	var i LockBatchForCancelRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
		&i.OwnerAccountID,
	)
	return i, err
}

const lockBatchForProcessing = `-- name: LockBatchForProcessing :one
SELECT b.id, b.building_id, b.recipe_id, b.batches_queued, b.batches_done,
       b.status, b.queue_position, b.started_at_sim,
       bld.owner_account_id, bld.region_id, bld.level, bld.fuel_stock,
       bld.status AS building_status, bld.powered_until_sim, bld.powered_rate,
       bt.base_storage, bt.level_curve, bt.code AS building_type_code, bt.placement_rules,
       r.batch_sim_seconds, r.fuel_product_id, r.fuel_per_batch, r.workers_required,
       r.power_per_hour
FROM world.production_batches b
JOIN world.buildings bld ON bld.id = b.building_id
JOIN world.building_types bt ON bt.id = bld.building_type_id
JOIN world.recipes r ON r.id = b.recipe_id
WHERE b.id = $1
FOR UPDATE OF b SKIP LOCKED
`

type LockBatchForProcessingRow struct {
	ID               uuid.UUID
	BuildingID       uuid.UUID
	RecipeID         uuid.UUID
	BatchesQueued    int32
	BatchesDone      int32
	Status           WorldBatchStatus
	QueuePosition    int32
	StartedAtSim     *int64
	OwnerAccountID   uuid.UUID
	RegionID         uuid.UUID
	Level            int32
	FuelStock        int64
	BuildingStatus   WorldBuildingStatus
	PoweredUntilSim  int64
	PoweredRate      int64
	BaseStorage      int64
	LevelCurve       []byte
	BuildingTypeCode string
	PlacementRules   []byte
	BatchSimSeconds  int64
	FuelProductID    *uuid.UUID
	FuelPerBatch     int64
	WorkersRequired  int32
	PowerPerHour     int64
}

// LockBatchForProcessing bloquea un lote (FOR UPDATE OF b SKIP LOCKED) y devuelve
// TODO lo que el motor necesita para completarlo: estado del lote, edificio
// (dueño, región, nivel, combustible, estado) y su tipo (almacén base,
// level_curve, code, placement_rules) y la receta (duración, combustible,
// trabajadores). pgx.ErrNoRows si otra instancia lo tomó o ya no aplica.
func (q *Queries) LockBatchForProcessing(ctx context.Context, id uuid.UUID) (LockBatchForProcessingRow, error) {
	row := q.db.QueryRow(ctx, lockBatchForProcessing, id)
	var i LockBatchForProcessingRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.Level,
		&i.FuelStock,
		&i.BuildingStatus,
		&i.PoweredUntilSim,
		&i.PoweredRate,
		&i.BaseStorage,
		&i.LevelCurve,
		&i.BuildingTypeCode,
		&i.PlacementRules,
		&i.BatchSimSeconds,
		&i.FuelProductID,
		&i.FuelPerBatch,
		&i.WorkersRequired,
		&i.PowerPerHour,
	)
	return i, err
}

const lockDueConstruction = `-- name: LockDueConstruction :one
SELECT id, owner_account_id, region_id, concession_id, building_type_id
FROM world.buildings
WHERE id = $1
  AND status = 'under_construction'
  AND updated_at_sim + $2::bigint <= $3::bigint
FOR UPDATE SKIP LOCKED
`

type LockDueConstructionParams struct {
	ID              uuid.UUID
	BuildSimSeconds int64
	SimNow          int64
}

type LockDueConstructionRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	RegionID       uuid.UUID
	ConcessionID   uuid.UUID
	BuildingTypeID uuid.UUID
}

// LockDueConstruction bloquea un edificio en construcción vencido (FOR UPDATE
// SKIP LOCKED): pgx.ErrNoRows si ya lo completó o lo tomó otra instancia.
func (q *Queries) LockDueConstruction(ctx context.Context, arg LockDueConstructionParams) (LockDueConstructionRow, error) {
	row := q.db.QueryRow(ctx, lockDueConstruction, arg.ID, arg.BuildSimSeconds, arg.SimNow)
	var i LockDueConstructionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerAccountID,
		&i.RegionID,
		&i.ConcessionID,
		&i.BuildingTypeID,
	)
	return i, err
}

const lockNearestDeposit = `-- name: LockNearestDeposit :one

SELECT d.id, d.remaining_amount
FROM world.resource_deposits d
JOIN world.network_nodes n ON n.building_id = $1
WHERE d.product_id = $2
  AND d.remaining_amount > 0
  AND ST_DWithin(d.location, n.location, $3::float8)
ORDER BY d.location <-> n.location
LIMIT 1
FOR UPDATE OF d SKIP LOCKED
`

type LockNearestDepositParams struct {
	BuildingID *uuid.UUID
	ProductID  uuid.UUID
	RadiusM    float64
}

type LockNearestDepositRow struct {
	ID              uuid.UUID
	RemainingAmount int64
}

// ─── Yacimientos (extracción) ─────────────────────────────────────────────────
// LockNearestDeposit bloquea el yacimiento del producto más cercano al nodo del
// edificio dentro del radio de influencia, con existencias (FOR UPDATE OF d SKIP
// LOCKED). pgx.ErrNoRows si no hay ninguno alcanzable con remaining > 0.
func (q *Queries) LockNearestDeposit(ctx context.Context, arg LockNearestDepositParams) (LockNearestDepositRow, error) {
	row := q.db.QueryRow(ctx, lockNearestDeposit, arg.BuildingID, arg.ProductID, arg.RadiusM)
	var i LockNearestDepositRow
	err := row.Scan(&i.ID, &i.RemainingAmount)
	return i, err
}

const lockNextQueuedHead = `-- name: LockNextQueuedHead :one
SELECT id, building_id, recipe_id, batches_queued, batches_done, status,
       queue_position, started_at_sim
FROM world.production_batches
WHERE building_id = $1
  AND status = 'queued'
ORDER BY queue_position, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type LockNextQueuedHeadRow struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	BatchesDone   int32
	Status        WorldBatchStatus
	QueuePosition int32
	StartedAtSim  *int64
}

// LockNextQueuedHead bloquea el lote queued a la cabeza de la cola de un
// edificio (menor queue_position) para promoverlo a running; FOR UPDATE SKIP
// LOCKED. pgx.ErrNoRows si no hay ninguno.
func (q *Queries) LockNextQueuedHead(ctx context.Context, buildingID uuid.UUID) (LockNextQueuedHeadRow, error) {
	row := q.db.QueryRow(ctx, lockNextQueuedHead, buildingID)
	var i LockNextQueuedHeadRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
	)
	return i, err
}

const nearestCityBaseSalary = `-- name: NearestCityBaseSalary :one

SELECT c.base_salary
FROM world.cities c
WHERE c.region_id = $1
ORDER BY c.location <-> (SELECT n.location FROM world.network_nodes n WHERE n.building_id = $2)
LIMIT 1
`

type NearestCityBaseSalaryParams struct {
	RegionID   uuid.UUID
	BuildingID *uuid.UUID
}

// ─── Salario (fórmula laboral, GDD 5.7) ───────────────────────────────────────
// NearestCityBaseSalary devuelve el salario base de la ciudad más cercana al
// nodo del edificio en su región. pgx.ErrNoRows si la región no tiene ciudades.
func (q *Queries) NearestCityBaseSalary(ctx context.Context, arg NearestCityBaseSalaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, nearestCityBaseSalary, arg.RegionID, arg.BuildingID)
	var base_salary int64
	err := row.Scan(&base_salary)
	return base_salary, err
}

const nextQueuePosition = `-- name: NextQueuePosition :one
SELECT COALESCE(MAX(queue_position) + 1, 0)::int AS position
FROM world.production_batches
WHERE building_id = $1
  AND status IN ('queued', 'running', 'paused_no_fuel', 'paused_no_workers', 'paused_no_power')
`

// NextQueuePosition devuelve la siguiente posición libre de la cola de un
// edificio (al final): MAX(queue_position)+1 sobre los lotes no terminales, o 0.
func (q *Queries) NextQueuePosition(ctx context.Context, buildingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextQueuePosition, buildingID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const pauseBatch = `-- name: PauseBatch :one
UPDATE world.production_batches
   SET status = $1::world.batch_status,
       started_at_sim = NULL,
       updated_at_sim = $2
 WHERE id = $3
RETURNING id, building_id, recipe_id, batches_queued, batches_done, status,
          queue_position, started_at_sim
`

type PauseBatchParams struct {
	Status WorldBatchStatus
	SimNow int64
	ID     uuid.UUID
}

type PauseBatchRow struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	BatchesDone   int32
	Status        WorldBatchStatus
	QueuePosition int32
	StartedAtSim  *int64
}

// PauseBatch pausa un lote por combustible o salarios (GDD 5.8/5.9): suelta el
// reloj (started_at_sim NULL) y no produce ni cobra.
func (q *Queries) PauseBatch(ctx context.Context, arg PauseBatchParams) (PauseBatchRow, error) {
	row := q.db.QueryRow(ctx, pauseBatch, arg.Status, arg.SimNow, arg.ID)
	var i PauseBatchRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
	)
	return i, err
}

const regionSaturation = `-- name: RegionSaturation :one
SELECT industrial_occupation::float8 AS saturation
FROM analytics.region_stats
WHERE region_id = $1
ORDER BY bucket_start_sim DESC
LIMIT 1
`

// RegionSaturation devuelve el factor de saturación industrial regional más
// reciente (analytics.region_stats.industrial_occupation) como float8.
// pgx.ErrNoRows si aún no hay estadística de la región (default 1.0 en Go).
func (q *Queries) RegionSaturation(ctx context.Context, regionID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, regionSaturation, regionID)
	var saturation float64
	err := row.Scan(&saturation)
	return saturation, err
}

const setBatchCancelled = `-- name: SetBatchCancelled :one
UPDATE world.production_batches
   SET status = 'cancelled', started_at_sim = NULL, updated_at_sim = $1
 WHERE id = $2
RETURNING id, building_id, recipe_id, batches_queued, batches_done, status,
          queue_position, started_at_sim
`

type SetBatchCancelledParams struct {
	SimNow int64
	ID     uuid.UUID
}

type SetBatchCancelledRow struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	BatchesDone   int32
	Status        WorldBatchStatus
	QueuePosition int32
	StartedAtSim  *int64
}

// SetBatchCancelled cancela lo NO producido: el lote pasa a cancelled y suelta
// el reloj; lo ya producido (batches_done) queda asentado.
func (q *Queries) SetBatchCancelled(ctx context.Context, arg SetBatchCancelledParams) (SetBatchCancelledRow, error) {
	row := q.db.QueryRow(ctx, setBatchCancelled, arg.SimNow, arg.ID)
	var i SetBatchCancelledRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
	)
	return i, err
}

const setBatchRunning = `-- name: SetBatchRunning :one
UPDATE world.production_batches
   SET status = 'running', started_at_sim = $1, updated_at_sim = $1
 WHERE id = $2
RETURNING id, building_id, recipe_id, batches_queued, batches_done, status,
          queue_position, started_at_sim
`

type SetBatchRunningParams struct {
	SimNow *int64
	ID     uuid.UUID
}

type SetBatchRunningRow struct {
	ID            uuid.UUID
	BuildingID    uuid.UUID
	RecipeID      uuid.UUID
	BatchesQueued int32
	BatchesDone   int32
	Status        WorldBatchStatus
	QueuePosition int32
	StartedAtSim  *int64
}

// SetBatchRunning promueve/reanuda un lote a running arrancando el reloj del
// lote en curso (started_at_sim = simNow).
func (q *Queries) SetBatchRunning(ctx context.Context, arg SetBatchRunningParams) (SetBatchRunningRow, error) {
	row := q.db.QueryRow(ctx, setBatchRunning, arg.SimNow, arg.ID)
	var i SetBatchRunningRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.RecipeID,
		&i.BatchesQueued,
		&i.BatchesDone,
		&i.Status,
		&i.QueuePosition,
		&i.StartedAtSim,
	)
	return i, err
}

const setBuildingFuelStock = `-- name: SetBuildingFuelStock :exec
UPDATE world.buildings
   SET fuel_stock = $1, updated_at_sim = $2
 WHERE id = $3
`

type SetBuildingFuelStockParams struct {
	FuelStock int64
	SimNow    int64
	ID        uuid.UUID
}

// SetBuildingFuelStock actualiza la columna espejo fuel_stock del edificio (GDD
// 5.8): refleja el inventario físico del producto combustible tras consumirlo.
func (q *Queries) SetBuildingFuelStock(ctx context.Context, arg SetBuildingFuelStockParams) error {
	_, err := q.db.Exec(ctx, setBuildingFuelStock, arg.FuelStock, arg.SimNow, arg.ID)
	return err
}

const sumBuildingInventory = `-- name: SumBuildingInventory :one
SELECT COALESCE(SUM(quantity), 0)::bigint AS total
FROM world.building_inventories
WHERE building_id = $1
`

// SumBuildingInventory devuelve el total físico almacenado en un edificio (todas
// las líneas de producto), base de la comprobación de capacidad de almacén.
func (q *Queries) SumBuildingInventory(ctx context.Context, buildingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumBuildingInventory, buildingID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
