// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const advanceVehicleToSegment = `-- name: AdvanceVehicleToSegment :exec
UPDATE world.vehicles
   SET on_segment_id = $1, route_leg_index = $2,
       segment_entered_sim = $3, advance_fn = $4,
       fuel = $5, wear_pct = $6,
       status = 'in_transit', at_node_id = NULL, updated_at_sim = $3
 WHERE id = $7
`

type AdvanceVehicleToSegmentParams struct {
	OnSegmentID   *uuid.UUID
	RouteLegIndex *int32
	SimNow        *int64
	AdvanceFn     []byte
	Fuel          int64
	WearPct       int32
	ID            uuid.UUID
}

// AdvanceVehicleToSegment mueve el vehículo al siguiente segmento (mismo leg o
// siguiente), reiniciando el reloj del segmento y guardando combustible/desgaste
// ya aplicados. Permanece in_transit.
func (q *Queries) AdvanceVehicleToSegment(ctx context.Context, arg AdvanceVehicleToSegmentParams) error {
	_, err := q.db.Exec(ctx, advanceVehicleToSegment,
		arg.OnSegmentID,
		arg.RouteLegIndex,
		arg.SimNow,
		arg.AdvanceFn,
		arg.Fuel,
		arg.WearPct,
		arg.ID,
	)
	return err
}

const arriveVehicle = `-- name: ArriveVehicle :exec
UPDATE world.vehicles
   SET status = 'idle', at_node_id = $1, on_segment_id = NULL,
       segment_entered_sim = NULL, advance_fn = NULL, route_leg_index = NULL,
       fuel = $2, wear_pct = $3, updated_at_sim = $4
 WHERE id = $5
`

type ArriveVehicleParams struct {
	AtNodeID *uuid.UUID
	Fuel     int64
	WearPct  int32
	SimNow   int64
	ID       uuid.UUID
}

// ArriveVehicle asienta la llegada al nodo destino final: idle en el nodo, sin
// segmento ni advance_fn, con el combustible/desgaste finales.
func (q *Queries) ArriveVehicle(ctx context.Context, arg ArriveVehicleParams) error {
	_, err := q.db.Exec(ctx, arriveVehicle,
		arg.AtNodeID,
		arg.Fuel,
		arg.WearPct,
		arg.SimNow,
		arg.ID,
	)
	return err
}

const breakVehicle = `-- name: BreakVehicle :exec
UPDATE world.vehicles
   SET status = 'broken', repair_until_sim = $1,
       fuel = $2, wear_pct = $3, updated_at_sim = $4
 WHERE id = $5
`

type BreakVehicleParams struct {
	RepairUntilSim *int64
	Fuel           int64
	WearPct        int32
	SimNow         int64
	ID             uuid.UUID
}

// BreakVehicle asienta una avería: broken sobre el MISMO segmento (la carga
// espera a bordo, GDD 7.3), con repair_until_sim y el combustible/desgaste ya
// aplicados. El barrido lo reanuda al vencer la reparación.
func (q *Queries) BreakVehicle(ctx context.Context, arg BreakVehicleParams) error {
	_, err := q.db.Exec(ctx, breakVehicle,
		arg.RepairUntilSim,
		arg.Fuel,
		arg.WearPct,
		arg.SimNow,
		arg.ID,
	)
	return err
}

const countInTransitVehicles = `-- name: CountInTransitVehicles :one
SELECT count(*)::bigint FROM world.vehicles WHERE status = 'in_transit'
`

// CountInTransitVehicles cuenta los vehículos en tránsito (gauge
// ii_vehicles_in_transit).
func (q *Queries) CountInTransitVehicles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInTransitVehicles)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deliverShipment = `-- name: DeliverShipment :exec
UPDATE world.shipments
   SET status = 'delivered', at_node_id = $1, vehicle_id = NULL,
       updated_at_sim = $2
 WHERE id = $3
`

type DeliverShipmentParams struct {
	AtNodeID *uuid.UUID
	SimNow   int64
	ID       uuid.UUID
}

// DeliverShipment marca un cargamento entregado en el nodo destino: delivered,
// reposa en el nodo, ya no viaja a bordo.
func (q *Queries) DeliverShipment(ctx context.Context, arg DeliverShipmentParams) error {
	_, err := q.db.Exec(ctx, deliverShipment, arg.AtNodeID, arg.SimNow, arg.ID)
	return err
}

const finishMaintenanceVehicle = `-- name: FinishMaintenanceVehicle :exec
UPDATE world.vehicles
   SET status = 'idle', repair_until_sim = NULL, updated_at_sim = $1
 WHERE id = $2
`

type FinishMaintenanceVehicleParams struct {
	SimNow int64
	ID     uuid.UUID
}

// FinishMaintenanceVehicle devuelve un vehículo in_maintenance a idle tras el
// servicio.
func (q *Queries) FinishMaintenanceVehicle(ctx context.Context, arg FinishMaintenanceVehicleParams) error {
	_, err := q.db.Exec(ctx, finishMaintenanceVehicle, arg.SimNow, arg.ID)
	return err
}

const getNextLegFirstSegment = `-- name: GetNextLegFirstSegment :one
SELECT rl.leg_index, s.id AS segment_id, s.length_m,
       s.congestion_ema::float8 AS congestion_ema, l.base_speed_kmh, l.to_node_id
FROM world.route_legs rl
JOIN world.network_links l ON l.id = rl.link_id
JOIN world.link_segments s ON s.link_id = l.id
WHERE rl.route_id = $1 AND rl.leg_index = $2
ORDER BY s.seq ASC
LIMIT 1
`

type GetNextLegFirstSegmentParams struct {
	RouteID      uuid.UUID
	NextLegIndex int32
}

type GetNextLegFirstSegmentRow struct {
	LegIndex      int32
	SegmentID     uuid.UUID
	LengthM       int32
	CongestionEma float64
	BaseSpeedKmh  int32
	ToNodeID      uuid.UUID
}

// GetNextLegFirstSegment devuelve el PRIMER segmento del leg en next_leg_index de
// una ruta (avance al siguiente enlace), con su nodo destino. pgx.ErrNoRows si no
// hay siguiente leg (el vehículo llegó al destino final).
func (q *Queries) GetNextLegFirstSegment(ctx context.Context, arg GetNextLegFirstSegmentParams) (GetNextLegFirstSegmentRow, error) {
	row := q.db.QueryRow(ctx, getNextLegFirstSegment, arg.RouteID, arg.NextLegIndex)
	var i GetNextLegFirstSegmentRow
	err := row.Scan(
		&i.LegIndex,
		&i.SegmentID,
		&i.LengthM,
		&i.CongestionEma,
		&i.BaseSpeedKmh,
		&i.ToNodeID,
	)
	return i, err
}

const getNextSegmentInLink = `-- name: GetNextSegmentInLink :one
SELECT s.id AS segment_id, s.length_m, s.congestion_ema::float8 AS congestion_ema, l.base_speed_kmh
FROM world.link_segments s
JOIN world.network_links l ON l.id = s.link_id
WHERE s.link_id = $1 AND s.seq > $2
ORDER BY s.seq ASC
LIMIT 1
`

type GetNextSegmentInLinkParams struct {
	LinkID   uuid.UUID
	AfterSeq int32
}

type GetNextSegmentInLinkRow struct {
	SegmentID     uuid.UUID
	LengthM       int32
	CongestionEma float64
	BaseSpeedKmh  int32
}

// GetNextSegmentInLink devuelve el siguiente segmento del MISMO enlace (seq
// mayor), para avanzar dentro de un leg multi-segmento. pgx.ErrNoRows si el
// segmento actual era el último del enlace (en Fase 1, 1 segmento por enlace).
func (q *Queries) GetNextSegmentInLink(ctx context.Context, arg GetNextSegmentInLinkParams) (GetNextSegmentInLinkRow, error) {
	row := q.db.QueryRow(ctx, getNextSegmentInLink, arg.LinkID, arg.AfterSeq)
	var i GetNextSegmentInLinkRow
	err := row.Scan(
		&i.SegmentID,
		&i.LengthM,
		&i.CongestionEma,
		&i.BaseSpeedKmh,
	)
	return i, err
}

const listDueRecoveryVehicleIDs = `-- name: ListDueRecoveryVehicleIDs :many

SELECT id, status FROM world.vehicles
WHERE status IN ('broken', 'in_maintenance')
  AND repair_until_sim IS NOT NULL AND repair_until_sim <= $1
ORDER BY repair_until_sim
LIMIT $2
`

type ListDueRecoveryVehicleIDsParams struct {
	SimNow    *int64
	PageLimit int32
}

type ListDueRecoveryVehicleIDsRow struct {
	ID     uuid.UUID
	Status WorldVehicleStatus
}

// ─── Reanudación de averías y mantenimiento ───────────────────────────────────
// ListDueRecoveryVehicleIDs lista los vehículos broken/in_maintenance cuyo tiempo
// de reparación/servicio venció (repair_until_sim <= simNow).
func (q *Queries) ListDueRecoveryVehicleIDs(ctx context.Context, arg ListDueRecoveryVehicleIDsParams) ([]ListDueRecoveryVehicleIDsRow, error) {
	rows, err := q.db.Query(ctx, listDueRecoveryVehicleIDs, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueRecoveryVehicleIDsRow
	for rows.Next() {
		var i ListDueRecoveryVehicleIDsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTransitVehicleIDs = `-- name: ListDueTransitVehicleIDs :many


SELECT id FROM world.vehicles
WHERE status = 'in_transit' AND on_segment_id IS NOT NULL AND advance_fn IS NOT NULL
  AND segment_entered_sim + world.segment_travel_seconds(advance_fn) <= $1
ORDER BY segment_entered_sim
LIMIT $2
`

type ListDueTransitVehicleIDsParams struct {
	SimNow    *int64
	PageLimit int32
}

// =============================================================================
// Imperio Industrial — queries sqlc del MOTOR DE TRÁNSITO (Incremento 3, Fase 1
// terrestre). El shard espacial (internal/world/fleet.TransitWorker) simula el
// movimiento físico: barrido de segmentos vencidos, combustible/desgaste, avería
// probabilística, avance segmento/leg, llegada y entrega, y el job de congestión
// (GDD 1.1/7.3). Event-driven: sólo los hitos escriben (coste proporcional a
// eventos, no a entidades). Cada vehículo se procesa en SU transacción
// SERIALIZABLE, bloqueado con FOR UPDATE SKIP LOCKED (varias instancias en
// paralelo sin pisarse). El tiempo de viaje sale de world.segment_travel_seconds.
// =============================================================================
// ─── Barrido de segmentos vencidos ────────────────────────────────────────────
// ListDueTransitVehicleIDs lista los vehículos in_transit cuyo segmento venció
// (segment_entered_sim + tiempo_de_viaje <= simNow), en orden de entrada.
func (q *Queries) ListDueTransitVehicleIDs(ctx context.Context, arg ListDueTransitVehicleIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueTransitVehicleIDs, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalTransshipQueue = `-- name: ListTerminalTransshipQueue :many
SELECT s.id, s.owner_account_id, s.quantity, s.updated_at_sim AS arrival_sim,
       (s.quantity * p.unit_volume)::bigint AS volume,
       COALESCE((
           SELECT MIN(ts.priority_tier) FROM world.terminal_slots ts
           WHERE ts.terminal_id = $1
             AND ts.holder_account_id = s.owner_account_id
             AND (ts.valid_until_sim IS NULL OR ts.valid_until_sim >= $2::bigint)
       ), 2147483647)::int AS slot_tier
FROM world.shipments s
JOIN world.products p ON p.id = s.product_id
WHERE s.at_node_id = $3 AND s.status = 'at_terminal'
  AND s.transship_ready_at_sim IS NULL
ORDER BY slot_tier ASC, s.updated_at_sim ASC, s.id ASC
`

type ListTerminalTransshipQueueParams struct {
	TerminalID uuid.UUID
	SimNow     int64
	NodeID     *uuid.UUID
}

type ListTerminalTransshipQueueRow struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	Quantity       int64
	ArrivalSim     int64
	Volume         int64
	SlotTier       int32
}

// ListTerminalTransshipQueue lista la COLA de una terminal: cargamentos at_terminal
// aún sin servir en su nodo, con el volumen del cargamento (quantity·unit_volume) y
// el MEJOR (menor) priority_tier VIGENTE del dueño en esa terminal (centinela alto
// si no posee slot). Ordena por prioridad (slot ascendente; sin slot al final) y,
// dentro de cada clase, FIFO por llegada (updated_at_sim, id): el orden de servicio.
func (q *Queries) ListTerminalTransshipQueue(ctx context.Context, arg ListTerminalTransshipQueueParams) ([]ListTerminalTransshipQueueRow, error) {
	rows, err := q.db.Query(ctx, listTerminalTransshipQueue, arg.TerminalID, arg.SimNow, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTerminalTransshipQueueRow
	for rows.Next() {
		var i ListTerminalTransshipQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.Quantity,
			&i.ArrivalSim,
			&i.Volume,
			&i.SlotTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalsWithPendingTransship = `-- name: ListTerminalsWithPendingTransship :many

SELECT DISTINCT t.id, t.node_id, t.owner_account_id, t.transshipment_per_hour
FROM world.terminals t
JOIN world.shipments s ON s.at_node_id = t.node_id
WHERE s.status = 'at_terminal' AND s.transship_ready_at_sim IS NULL
LIMIT $1
`

type ListTerminalsWithPendingTransshipRow struct {
	ID                   uuid.UUID
	NodeID               uuid.UUID
	OwnerAccountID       uuid.UUID
	TransshipmentPerHour int32
}

// ─── Cola de transbordo con prioridad de slots (GDD 7.3) ──────────────────────
// ListTerminalsWithPendingTransship lista las terminales con cargamentos ENCOLADOS
// (at_terminal, aún sin servir) esperando transbordo: candidatas del barrido de
// servicio de cola (sweepTransship). Acotado por page_limit.
func (q *Queries) ListTerminalsWithPendingTransship(ctx context.Context, pageLimit int32) ([]ListTerminalsWithPendingTransshipRow, error) {
	rows, err := q.db.Query(ctx, listTerminalsWithPendingTransship, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTerminalsWithPendingTransshipRow
	for rows.Next() {
		var i ListTerminalsWithPendingTransshipRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.OwnerAccountID,
			&i.TransshipmentPerHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleShipmentsForNode = `-- name: ListVehicleShipmentsForNode :many

SELECT id, owner_account_id, product_id, quantity, contract_id, freight_contract_id, destination_node_id, deadline_sim
FROM world.shipments
WHERE vehicle_id = $1 AND status = 'in_transit'
  AND destination_node_id = $2
FOR UPDATE
`

type ListVehicleShipmentsForNodeParams struct {
	VehicleID *uuid.UUID
	NodeID    *uuid.UUID
}

type ListVehicleShipmentsForNodeRow struct {
	ID                uuid.UUID
	OwnerAccountID    uuid.UUID
	ProductID         uuid.UUID
	Quantity          int64
	ContractID        *uuid.UUID
	FreightContractID *uuid.UUID
	DestinationNodeID *uuid.UUID
	DeadlineSim       *int64
}

// ─── Entrega al llegar al nodo destino ────────────────────────────────────────
// ListVehicleShipmentsForNode devuelve los cargamentos a bordo de un vehículo con
// destino ESE nodo (los demás siguen a bordo). FOR UPDATE dentro de la tx del
// vehículo.
func (q *Queries) ListVehicleShipmentsForNode(ctx context.Context, arg ListVehicleShipmentsForNodeParams) ([]ListVehicleShipmentsForNodeRow, error) {
	rows, err := q.db.Query(ctx, listVehicleShipmentsForNode, arg.VehicleID, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleShipmentsForNodeRow
	for rows.Next() {
		var i ListVehicleShipmentsForNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.ProductID,
			&i.Quantity,
			&i.ContractID,
			&i.FreightContractID,
			&i.DestinationNodeID,
			&i.DeadlineSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleShipmentsToTransship = `-- name: ListVehicleShipmentsToTransship :many

SELECT id, owner_account_id, product_id, quantity, contract_id, freight_contract_id, destination_node_id, deadline_sim
FROM world.shipments
WHERE vehicle_id = $1 AND status = 'in_transit'
  AND (destination_node_id IS NULL OR destination_node_id <> $2)
FOR UPDATE
`

type ListVehicleShipmentsToTransshipParams struct {
	VehicleID *uuid.UUID
	NodeID    *uuid.UUID
}

type ListVehicleShipmentsToTransshipRow struct {
	ID                uuid.UUID
	OwnerAccountID    uuid.UUID
	ProductID         uuid.UUID
	Quantity          int64
	ContractID        *uuid.UUID
	FreightContractID *uuid.UUID
	DestinationNodeID *uuid.UUID
	DeadlineSim       *int64
}

// ─── Transbordo en terminal intermodal (ruta multimodal por tramos) ───────────
// ListVehicleShipmentsToTransship devuelve los cargamentos a bordo de un vehículo
// cuyo destino NO es el nodo de llegada: candidatos a TRANSBORDO cuando el vehículo
// termina su tramo en una terminal intermodal (el cargamento cambia de modo, GDD
// 7.3). Complementa a ListVehicleShipmentsForNode (que entrega los de destino ese
// nodo). FOR UPDATE dentro de la tx del vehículo.
func (q *Queries) ListVehicleShipmentsToTransship(ctx context.Context, arg ListVehicleShipmentsToTransshipParams) ([]ListVehicleShipmentsToTransshipRow, error) {
	rows, err := q.db.Query(ctx, listVehicleShipmentsToTransship, arg.VehicleID, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleShipmentsToTransshipRow
	for rows.Next() {
		var i ListVehicleShipmentsToTransshipRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAccountID,
			&i.ProductID,
			&i.Quantity,
			&i.ContractID,
			&i.FreightContractID,
			&i.DestinationNodeID,
			&i.DeadlineSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecoveryVehicle = `-- name: LockRecoveryVehicle :one
SELECT id, status, repair_until_sim FROM world.vehicles
WHERE id = $1 AND status IN ('broken', 'in_maintenance')
FOR UPDATE SKIP LOCKED
`

type LockRecoveryVehicleRow struct {
	ID             uuid.UUID
	Status         WorldVehicleStatus
	RepairUntilSim *int64
}

// LockRecoveryVehicle bloquea un vehículo broken/in_maintenance (FOR UPDATE SKIP
// LOCKED) para reanudarlo. pgx.ErrNoRows si otra instancia lo tomó.
func (q *Queries) LockRecoveryVehicle(ctx context.Context, id uuid.UUID) (LockRecoveryVehicleRow, error) {
	row := q.db.QueryRow(ctx, lockRecoveryVehicle, id)
	var i LockRecoveryVehicleRow
	err := row.Scan(&i.ID, &i.Status, &i.RepairUntilSim)
	return i, err
}

const lockTerminalForServe = `-- name: LockTerminalForServe :one
SELECT id, node_id, owner_account_id, transshipment_per_hour, queue_length
FROM world.terminals
WHERE id = $1
FOR UPDATE
`

type LockTerminalForServeRow struct {
	ID                   uuid.UUID
	NodeID               uuid.UUID
	OwnerAccountID       uuid.UUID
	TransshipmentPerHour int32
	QueueLength          int32
}

// LockTerminalForServe bloquea una terminal (FOR UPDATE) para serializar el
// servicio de su cola entre instancias del motor. pgx.ErrNoRows si no existe.
func (q *Queries) LockTerminalForServe(ctx context.Context, id uuid.UUID) (LockTerminalForServeRow, error) {
	row := q.db.QueryRow(ctx, lockTerminalForServe, id)
	var i LockTerminalForServeRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OwnerAccountID,
		&i.TransshipmentPerHour,
		&i.QueueLength,
	)
	return i, err
}

const lockTransitVehicle = `-- name: LockTransitVehicle :one
SELECT v.id, v.vehicle_type_id, v.owner_account_id, v.status, v.wear_pct, v.fuel,
       v.route_id, v.route_leg_index, v.on_segment_id, v.segment_entered_sim, v.advance_fn,
       s.link_id, s.seq AS segment_seq, s.length_m AS segment_length_m,
       l.from_node_id, l.to_node_id, l.base_speed_kmh,
       vt.fuel_per_100km, vt.speed_kmh
FROM world.vehicles v
JOIN world.link_segments s ON s.id = v.on_segment_id
JOIN world.network_links l ON l.id = s.link_id
JOIN world.vehicle_types vt ON vt.id = v.vehicle_type_id
WHERE v.id = $1 AND v.status = 'in_transit'
FOR UPDATE OF v SKIP LOCKED
`

type LockTransitVehicleRow struct {
	ID                uuid.UUID
	VehicleTypeID     uuid.UUID
	OwnerAccountID    uuid.UUID
	Status            WorldVehicleStatus
	WearPct           int32
	Fuel              int64
	RouteID           *uuid.UUID
	RouteLegIndex     *int32
	OnSegmentID       *uuid.UUID
	SegmentEnteredSim *int64
	AdvanceFn         []byte
	LinkID            uuid.UUID
	SegmentSeq        int32
	SegmentLengthM    int32
	FromNodeID        uuid.UUID
	ToNodeID          uuid.UUID
	BaseSpeedKmh      int32
	FuelPer100km      int64
	SpeedKmh          int32
}

// LockTransitVehicle bloquea un vehículo in_transit (FOR UPDATE SKIP LOCKED) con
// el segmento, su enlace y el tipo de vehículo: todo lo necesario para consumir
// combustible, avanzar o llegar. pgx.ErrNoRows si otra instancia lo tomó.
func (q *Queries) LockTransitVehicle(ctx context.Context, id uuid.UUID) (LockTransitVehicleRow, error) {
	row := q.db.QueryRow(ctx, lockTransitVehicle, id)
	var i LockTransitVehicleRow
	err := row.Scan(
		&i.ID,
		&i.VehicleTypeID,
		&i.OwnerAccountID,
		&i.Status,
		&i.WearPct,
		&i.Fuel,
		&i.RouteID,
		&i.RouteLegIndex,
		&i.OnSegmentID,
		&i.SegmentEnteredSim,
		&i.AdvanceFn,
		&i.LinkID,
		&i.SegmentSeq,
		&i.SegmentLengthM,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.BaseSpeedKmh,
		&i.FuelPer100km,
		&i.SpeedKmh,
	)
	return i, err
}

const recomputeSegmentCongestion = `-- name: RecomputeSegmentCongestion :many

UPDATE world.link_segments s
   SET congestion_ema = GREATEST(1.0,
           0.3 * LEAST(3.0, GREATEST(1.0, cnt.n::float8 / NULLIF($1::float8, 0)))
           + 0.7 * s.congestion_ema),
       updated_at_sim = $2
  FROM (
      SELECT ls.id,
             (SELECT count(*) FROM world.vehicles v
               WHERE v.on_segment_id = ls.id AND v.status = 'in_transit') AS n
      FROM world.link_segments ls
  ) cnt
 WHERE cnt.id = s.id
RETURNING s.id, s.congestion_ema::float8 AS congestion_ema
`

type RecomputeSegmentCongestionParams struct {
	CapacityRef float64
	SimNow      int64
}

type RecomputeSegmentCongestionRow struct {
	ID            uuid.UUID
	CongestionEma float64
}

// ─── Congestión (job periódico) y métricas ────────────────────────────────────
// RecomputeSegmentCongestion recalcula la EMA de TODOS los segmentos en una sola
// sentencia: carga_normalizada = clamp(vehiculos_in_transit / capacity_ref, 1, 3)
// y congestion_ema = 0.3*carga_normalizada + 0.7*congestion_ema (suelo 1.0). Con
// 0 vehículos la EMA decae hacia el suelo fluido 1.0. Devuelve las filas para el
// gauge ii_segment_congestion.
func (q *Queries) RecomputeSegmentCongestion(ctx context.Context, arg RecomputeSegmentCongestionParams) ([]RecomputeSegmentCongestionRow, error) {
	rows, err := q.db.Query(ctx, recomputeSegmentCongestion, arg.CapacityRef, arg.SimNow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecomputeSegmentCongestionRow
	for rows.Next() {
		var i RecomputeSegmentCongestionRow
		if err := rows.Scan(&i.ID, &i.CongestionEma); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recountTerminalQueue = `-- name: RecountTerminalQueue :exec
UPDATE world.terminals t
   SET queue_length = (
           SELECT count(*) FROM world.shipments s
           WHERE s.at_node_id = t.node_id AND s.status = 'at_terminal'
             AND (s.transship_ready_at_sim IS NULL
                  OR s.transship_ready_at_sim > $1::bigint)
       ),
       updated_at_sim = $1
 WHERE t.id = $2
`

type RecountTerminalQueueParams struct {
	SimNow int64
	ID     uuid.UUID
}

// RecountTerminalQueue recalcula la longitud de cola de una terminal: cargamentos
// at_terminal en su nodo aún sin servir (encolados) o con servicio en curso
// (transship_ready_at_sim > sim_now). Publica también updated_at_sim.
func (q *Queries) RecountTerminalQueue(ctx context.Context, arg RecountTerminalQueueParams) error {
	_, err := q.db.Exec(ctx, recountTerminalQueue, arg.SimNow, arg.ID)
	return err
}

const resumeBrokenVehicle = `-- name: ResumeBrokenVehicle :exec
UPDATE world.vehicles
   SET status = 'in_transit', segment_entered_sim = $1,
       repair_until_sim = NULL, updated_at_sim = $1
 WHERE id = $2
`

type ResumeBrokenVehicleParams struct {
	SimNow *int64
	ID     uuid.UUID
}

// ResumeBrokenVehicle reanuda una avería: vuelve a in_transit y RE-ENTRA al mismo
// segmento con el reloj arrancado en simNow (advance_fn/on_segment intactos).
func (q *Queries) ResumeBrokenVehicle(ctx context.Context, arg ResumeBrokenVehicleParams) error {
	_, err := q.db.Exec(ctx, resumeBrokenVehicle, arg.SimNow, arg.ID)
	return err
}

const setShipmentTransshipReady = `-- name: SetShipmentTransshipReady :exec
UPDATE world.shipments
   SET transship_ready_at_sim = $1
 WHERE id = $2
`

type SetShipmentTransshipReadyParams struct {
	ReadyAtSim *int64
	ID         uuid.UUID
}

// SetShipmentTransshipReady marca un cargamento como SERVIDO por la cola: fija el
// instante de fin de transbordo (listo para el siguiente tramo). No toca
// updated_at_sim (conserva la llegada).
func (q *Queries) SetShipmentTransshipReady(ctx context.Context, arg SetShipmentTransshipReadyParams) error {
	_, err := q.db.Exec(ctx, setShipmentTransshipReady, arg.ReadyAtSim, arg.ID)
	return err
}

const strandVehicle = `-- name: StrandVehicle :exec
UPDATE world.vehicles
   SET status = 'idle', at_node_id = $1, on_segment_id = NULL,
       segment_entered_sim = NULL, advance_fn = NULL, updated_at_sim = $2
 WHERE id = $3
`

type StrandVehicleParams struct {
	AtNodeID *uuid.UUID
	SimNow   int64
	ID       uuid.UUID
}

// StrandVehicle detiene el vehículo por falta de combustible en el nodo previo
// (idle, sin segmento). Caso defensivo: el combustible se valida para toda la
// ruta al despachar (GDD 7.3/CONTEXT). El combustible no cambia (era insuficiente).
func (q *Queries) StrandVehicle(ctx context.Context, arg StrandVehicleParams) error {
	_, err := q.db.Exec(ctx, strandVehicle, arg.AtNodeID, arg.SimNow, arg.ID)
	return err
}

const terminalServerBusyUntil = `-- name: TerminalServerBusyUntil :one
SELECT COALESCE(MAX(transship_ready_at_sim), 0)::bigint AS busy_until
FROM world.shipments
WHERE at_node_id = $1 AND status = 'at_terminal'
  AND transship_ready_at_sim IS NOT NULL
  AND transship_ready_at_sim > $2::bigint
`

type TerminalServerBusyUntilParams struct {
	NodeID *uuid.UUID
	SimNow int64
}

// TerminalServerBusyUntil devuelve hasta cuándo está OCUPADO el servidor de la
// terminal: el mayor transship_ready_at_sim de los cargamentos ya servidos que aún
// no han partido y cuyo servicio NO ha terminado en sim_now (ready > sim_now). 0 si
// el servidor está libre. Base del encolado secuencial entre barridos.
func (q *Queries) TerminalServerBusyUntil(ctx context.Context, arg TerminalServerBusyUntilParams) (int64, error) {
	row := q.db.QueryRow(ctx, terminalServerBusyUntil, arg.NodeID, arg.SimNow)
	var busy_until int64
	err := row.Scan(&busy_until)
	return busy_until, err
}

const transshipShipment = `-- name: TransshipShipment :exec
UPDATE world.shipments
   SET status = 'at_terminal', at_node_id = $1, vehicle_id = NULL,
       transship_ready_at_sim = NULL, updated_at_sim = $2
 WHERE id = $3
`

type TransshipShipmentParams struct {
	AtNodeID *uuid.UUID
	SimNow   int64
	ID       uuid.UUID
}

// TransshipShipment ENCOLA un cargamento EN LA TERMINAL (at_terminal) a la espera de
// ser servido por la cola de transbordo: reposa en el nodo de la terminal, ya no
// viaja a bordo. updated_at_sim marca el momento de llegada a la terminal (clave
// FIFO de la cola). transship_ready_at_sim se pone a NULL: el cargamento entra en la
// cola SIN servir; el barrido de transbordo (sweepTransship) le asigna el instante
// de fin de servicio según su prioridad (slot) y su posición, y el siguiente
// despacho usa ese valor como puerta de tiempo.
func (q *Queries) TransshipShipment(ctx context.Context, arg TransshipShipmentParams) error {
	_, err := q.db.Exec(ctx, transshipShipment, arg.AtNodeID, arg.SimNow, arg.ID)
	return err
}
