// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balancer.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addCitySupplyIndex = `-- name: AddCitySupplyIndex :one
UPDATE world.cities
   SET supply_index = supply_index + $1::float8
 WHERE id = $2
RETURNING supply_index::float8 AS supply_index
`

type AddCitySupplyIndexParams struct {
	Delta float64
	ID    uuid.UUID
}

// AddCitySupplyIndex incrementa el índice de suministro histórico de una ciudad
// (lo llama el consumer al consumir una entrega, ponderado por variedad).
// Devuelve el índice resultante (float8). NO toca updated_at_sim: ese sello es
// el marcador del último RECÁLCULO (lo escribe solo UpdateCityGrowth), del que
// el DemandWorker deriva la ventana de decaimiento — el consumo no lo corrompe.
func (q *Queries) AddCitySupplyIndex(ctx context.Context, arg AddCitySupplyIndexParams) (float64, error) {
	row := q.db.QueryRow(ctx, addCitySupplyIndex, arg.Delta, arg.ID)
	var supply_index float64
	err := row.Scan(&supply_index)
	return supply_index, err
}

const addRecentSupply = `-- name: AddRecentSupply :one
UPDATE world.city_demand
   SET recent_supply = recent_supply + $1
 WHERE city_id = $2 AND product_id = $3
RETURNING recent_supply
`

type AddRecentSupplyParams struct {
	Qty       int64
	CityID    uuid.UUID
	ProductID uuid.UUID
}

// AddRecentSupply acumula la oferta entregada a una (ciudad, producto) desde el
// último recálculo (lo llama el consumer). Devuelve el acumulado RESULTANTE: el
// llamante deriva el previo (resultante − qty) para el bono de variedad (era 0 =
// primer suministro de la ventana = producto "nuevo"). Cero filas afectadas si
// no hay curva para ese producto (el consumer lo trata como sin variedad).
func (q *Queries) AddRecentSupply(ctx context.Context, arg AddRecentSupplyParams) (int64, error) {
	row := q.db.QueryRow(ctx, addRecentSupply, arg.Qty, arg.CityID, arg.ProductID)
	var recent_supply int64
	err := row.Scan(&recent_supply)
	return recent_supply, err
}

const bucketAbsorption = `-- name: BucketAbsorption :one
SELECT COALESCE(SUM(e.amount), 0)::bigint AS absorption_total
FROM ledger.entries e
JOIN ledger.accounts a     ON a.id = e.account_id
JOIN ledger.transactions t ON t.id = e.transaction_id
WHERE a.kind = 'sink'
  AND t.sim_time_at >= $1
  AND t.sim_time_at <  $2
`

type BucketAbsorptionParams struct {
	BucketStart int64
	BucketEnd   int64
}

// BucketAbsorption calcula la absorción (sinks) del bucket: dinero RETIRADO de
// circulación, medido como Σ de las partidas sobre las cuentas sink en asientos
// con sim_time_at en el bucket (el sink se abona en positivo al destruir valor).
// Coincide con los kinds sink (tax, canon, maintenance, sanciones de
// liquidación, bot_retirement) pero se mide sobre el movimiento monetario
// autoritativo (las cuentas sink), garantizando la coherencia macro.
func (q *Queries) BucketAbsorption(ctx context.Context, arg BucketAbsorptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bucketAbsorption, arg.BucketStart, arg.BucketEnd)
	var absorption_total int64
	err := row.Scan(&absorption_total)
	return absorption_total, err
}

const bucketEmission = `-- name: BucketEmission :one
SELECT COALESCE(-SUM(e.amount), 0)::bigint AS emission_total
FROM ledger.entries e
JOIN ledger.accounts a     ON a.id = e.account_id
JOIN ledger.transactions t ON t.id = e.transaction_id
WHERE a.kind = 'emission'
  AND t.sim_time_at >= $1
  AND t.sim_time_at <  $2
`

type BucketEmissionParams struct {
	BucketStart int64
	BucketEnd   int64
}

// BucketEmission calcula la emisión (faucet) del bucket: dinero NUEVO puesto en
// circulación, medido como −Σ de las partidas sobre la cuenta de emisión del
// banco central en asientos con sim_time_at en el bucket (la emisión se abona en
// negativo al crear dinero, así que −Σ es el neto emitido). Coincide con los
// kinds faucet (seed_capital, bot_capitalization, fondeo de ciudad) pero se mide
// sobre el movimiento monetario autoritativo (la cuenta emission), garantizando
// la coherencia emisión−absorción = Δmasa monetaria por doble entrada.
func (q *Queries) BucketEmission(ctx context.Context, arg BucketEmissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bucketEmission, arg.BucketStart, arg.BucketEnd)
	var emission_total int64
	err := row.Scan(&emission_total)
	return emission_total, err
}

const bucketGdp = `-- name: BucketGdp :one


SELECT COALESCE(SUM(quantity_delivered * unit_price), 0)::bigint AS gdp
FROM ledger.contracts
WHERE status = 'settled'
  AND settled_at_sim >= $1::bigint
  AND settled_at_sim <  $2::bigint
`

type BucketGdpParams struct {
	BucketStart int64
	BucketEnd   int64
}

// =============================================================================
// MACRO (Incremento 6b): job de analítica, fórmula laboral (GDD 5.7) y ajuste
// fiscal algorítmico (banco central algorítmico, GDD 5.5). Escribe los agregados
// de analytics.* (bucketizados por sim-time) y ajusta world.cities.base_salary y
// world.regions.tax_rate_bp/canon_base dentro de rangos. Todo lo que sigue son
// LECTURAS de ledger/world/auth y ESCRITURAS de analytics/world (nunca dinero:
// el macro observa y regula parámetros, no mueve valor del ledger).
// =============================================================================
// ─── Analítica macro: indicadores del bucket (analytics.economy_indicators) ───
// BucketGdp calcula el PIB simulado del bucket: valor de los contratos LIQUIDADOS
// (fill > 0) cuyo settled_at_sim cae en [bucket_start, bucket_end). Es el valor
// efectivamente entregado (quantity_delivered × unit_price), no el pactado.
func (q *Queries) BucketGdp(ctx context.Context, arg BucketGdpParams) (int64, error) {
	row := q.db.QueryRow(ctx, bucketGdp, arg.BucketStart, arg.BucketEnd)
	var gdp int64
	err := row.Scan(&gdp)
	return gdp, err
}

const consumeBuildingInventory = `-- name: ConsumeBuildingInventory :exec

UPDATE world.building_inventories
   SET quantity = quantity - $1, updated_at_sim = $2
 WHERE building_id = $3 AND product_id = $4
`

type ConsumeBuildingInventoryParams struct {
	Amount     int64
	SimNow     int64
	BuildingID uuid.UUID
	ProductID  uuid.UUID
}

// ─── Inventario físico del centro de distribución ─────────────────────────────
// ConsumeBuildingInventory descuenta stock físico consumido por la ciudad de su
// centro de distribución (mantiene físico↔contable en sincronía, ADR-004). La
// fila debe existir y cubrir la cantidad (la entrega la creó al llegar); el CHECK
// quantity >= 0 respalda la invariante.
func (q *Queries) ConsumeBuildingInventory(ctx context.Context, arg ConsumeBuildingInventoryParams) error {
	_, err := q.db.Exec(ctx, consumeBuildingInventory,
		arg.Amount,
		arg.SimNow,
		arg.BuildingID,
		arg.ProductID,
	)
	return err
}

const countActiveAccounts = `-- name: CountActiveAccounts :one
SELECT
    COALESCE(SUM(CASE WHEN kind = 'bot'   THEN 1 ELSE 0 END), 0)::int AS bot_count,
    COALESCE(SUM(CASE WHEN kind = 'human' THEN 1 ELSE 0 END), 0)::int AS human_count
FROM auth.accounts
WHERE status = 'active'
`

type CountActiveAccountsRow struct {
	BotCount   int32
	HumanCount int32
}

// CountActiveAccounts cuenta las cuentas activas por rol (bots y humanos) para
// los indicadores de población económica del bucket.
func (q *Queries) CountActiveAccounts(ctx context.Context) (CountActiveAccountsRow, error) {
	row := q.db.QueryRow(ctx, countActiveAccounts)
	var i CountActiveAccountsRow
	err := row.Scan(&i.BotCount, &i.HumanCount)
	return i, err
}

const countLiveCityBuys = `-- name: CountLiveCityBuys :one

SELECT count(*)
FROM ledger.publications
WHERE publisher_account_id = $1
  AND product_id = $2
  AND kind = 'buy'
  AND status IN ('draw_window', 'open', 'micro_window')
`

type CountLiveCityBuysParams struct {
	PublisherAccountID uuid.UUID
	ProductID          *uuid.UUID
}

// ─── Tablón: deduplicación de la buy viva por (ciudad, producto) ──────────────
// CountLiveCityBuys cuenta las publicaciones buy VIVAS del tablón (draw_window,
// open, micro_window) de una ciudad para un producto: mantener UNA sola solicitud
// de compra viva por (ciudad, producto) evita duplicar demanda en el tablón.
func (q *Queries) CountLiveCityBuys(ctx context.Context, arg CountLiveCityBuysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveCityBuys, arg.PublisherAccountID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCashAccount = `-- name: CreateCashAccount :one
INSERT INTO ledger.accounts (id, kind, owner_account_id)
VALUES ($1, 'cash', $2)
RETURNING id, balance
`

type CreateCashAccountParams struct {
	ID             uuid.UUID
	OwnerAccountID *uuid.UUID
}

type CreateCashAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// CreateCashAccount crea la caja de una cuenta on-demand (unicidad ux_accounts_cash).
func (q *Queries) CreateCashAccount(ctx context.Context, arg CreateCashAccountParams) (CreateCashAccountRow, error) {
	row := q.db.QueryRow(ctx, createCashAccount, arg.ID, arg.OwnerAccountID)
	var i CreateCashAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const createWorldSourceAccount = `-- name: CreateWorldSourceAccount :one
INSERT INTO ledger.accounts (id, kind, owner_account_id, product_id)
VALUES ($1, 'world_source', $2, $3)
RETURNING id, balance
`

type CreateWorldSourceAccountParams struct {
	ID             uuid.UUID
	OwnerAccountID *uuid.UUID
	ProductID      *uuid.UUID
}

type CreateWorldSourceAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// CreateWorldSourceAccount crea la cuenta world_source de un producto (titular:
// banco central; NULL admitido como cuenta pura de sistema si aún no hay banco).
func (q *Queries) CreateWorldSourceAccount(ctx context.Context, arg CreateWorldSourceAccountParams) (CreateWorldSourceAccountRow, error) {
	row := q.db.QueryRow(ctx, createWorldSourceAccount, arg.ID, arg.OwnerAccountID, arg.ProductID)
	var i CreateWorldSourceAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const finiteDepletionByProduct = `-- name: FiniteDepletionByProduct :many
SELECT p.code AS product_code,
       COALESCE(SUM(d.remaining_amount), 0)::bigint            AS remaining,
       COALESCE(SUM(d.initial_amount - d.remaining_amount), 0)::bigint AS extracted
FROM world.resource_deposits d
JOIN world.products p ON p.id = d.product_id
WHERE d.renewable = false
GROUP BY p.code
ORDER BY p.code
`

type FiniteDepletionByProductRow struct {
	ProductCode string
	Remaining   int64
	Extracted   int64
}

// FiniteDepletionByProduct desglosa el agotamiento de los yacimientos FINITOS
// (no renovables) por producto (código legible): stock restante y extraído
// (initial − remaining). Alimenta la proyección JSONB de agotamiento por recurso
// (analytics, GDD 10/20) y el ritmo global de agotamiento, que se deriva en Go
// como Σ extraído_producto / tiempo transcurrido desde el génesis
// (delta_remaining / tiempo).
func (q *Queries) FiniteDepletionByProduct(ctx context.Context) ([]FiniteDepletionByProductRow, error) {
	rows, err := q.db.Query(ctx, finiteDepletionByProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FiniteDepletionByProductRow
	for rows.Next() {
		var i FiniteDepletionByProductRow
		if err := rows.Scan(&i.ProductCode, &i.Remaining, &i.Extracted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashAccount = `-- name: GetCashAccount :one

SELECT id, balance FROM ledger.accounts
WHERE kind = 'cash' AND owner_account_id = $1
`

type GetCashAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// ─── Ledger: cuentas del faucet y del consumo ─────────────────────────────────
// GetCashAccount devuelve la caja de una cuenta (la de la ciudad); pgx.ErrNoRows
// si aún no existe.
func (q *Queries) GetCashAccount(ctx context.Context, ownerAccountID *uuid.UUID) (GetCashAccountRow, error) {
	row := q.db.QueryRow(ctx, getCashAccount, ownerAccountID)
	var i GetCashAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getCityDistributionNode = `-- name: GetCityDistributionNode :one
SELECT id FROM world.network_nodes
WHERE city_id = $1 AND kind = 'distribution_center'
ORDER BY id
LIMIT 1
`

// GetCityDistributionNode devuelve el nodo del centro de distribución de una
// ciudad (destino de sus buys: la entrega estándar deja ahí el stock_free de la
// ciudad). pgx.ErrNoRows si la ciudad no tiene centro de distribución sembrado.
func (q *Queries) GetCityDistributionNode(ctx context.Context, cityID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCityDistributionNode, cityID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getContractForConsume = `-- name: GetContractForConsume :one

SELECT buyer_account_id, product_id, destination_node_id, quantity_delivered, status
FROM ledger.contracts
WHERE id = $1
`

type GetContractForConsumeRow struct {
	BuyerAccountID    uuid.UUID
	ProductID         uuid.UUID
	DestinationNodeID uuid.UUID
	QuantityDelivered int64
	Status            LedgerContractStatus
}

// ─── Contratos: entrega urbana a consumir ─────────────────────────────────────
// GetContractForConsume devuelve los datos del contrato liquidado que el consumer
// necesita para consumir la entrega urbana: comprador, producto, nodo de destino,
// cantidad entregada y estado. pgx.ErrNoRows si no existe.
func (q *Queries) GetContractForConsume(ctx context.Context, id uuid.UUID) (GetContractForConsumeRow, error) {
	row := q.db.QueryRow(ctx, getContractForConsume, id)
	var i GetContractForConsumeRow
	err := row.Scan(
		&i.BuyerAccountID,
		&i.ProductID,
		&i.DestinationNodeID,
		&i.QuantityDelivered,
		&i.Status,
	)
	return i, err
}

const getEmissionAccount = `-- name: GetEmissionAccount :one
SELECT id, balance FROM ledger.accounts
WHERE kind = 'emission'
ORDER BY id
LIMIT 1
`

type GetEmissionAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// GetEmissionAccount devuelve la cuenta de emisión del banco central (única
// cuenta monetaria que puede quedar negativa: la contrapartida del faucet).
// pgx.ErrNoRows si el seed no la creó.
func (q *Queries) GetEmissionAccount(ctx context.Context) (GetEmissionAccountRow, error) {
	row := q.db.QueryRow(ctx, getEmissionAccount)
	var i GetEmissionAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getNodeBuilding = `-- name: GetNodeBuilding :one

SELECT building_id, city_id, region_id
FROM world.network_nodes
WHERE id = $1
`

type GetNodeBuildingRow struct {
	BuildingID *uuid.UUID
	CityID     *uuid.UUID
	RegionID   uuid.UUID
}

// ─── Nodos → edificio (centro de distribución de la ciudad) ───────────────────
// GetNodeBuilding devuelve el edificio y la ciudad ligados a un nodo del grafo
// (el destino de una buy de ciudad es su centro de distribución). pgx.ErrNoRows
// si el nodo no existe.
func (q *Queries) GetNodeBuilding(ctx context.Context, id uuid.UUID) (GetNodeBuildingRow, error) {
	row := q.db.QueryRow(ctx, getNodeBuilding, id)
	var i GetNodeBuildingRow
	err := row.Scan(&i.BuildingID, &i.CityID, &i.RegionID)
	return i, err
}

const getProduct = `-- name: GetProduct :one

SELECT base_price, price_floor, price_ceiling, class
FROM world.products
WHERE id = $1
`

type GetProductRow struct {
	BasePrice    int64
	PriceFloor   int64
	PriceCeiling int64
	Class        WorldProductClass
}

// ─── Productos (ancla de precio, GDD 5.1) ─────────────────────────────────────
// GetProduct devuelve el ancla de precio y la clase de elasticidad de un producto
// (base_price, price_floor, price_ceiling, class); pgx.ErrNoRows si no existe.
func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.BasePrice,
		&i.PriceFloor,
		&i.PriceCeiling,
		&i.Class,
	)
	return i, err
}

const getStockFreeAccount = `-- name: GetStockFreeAccount :one
SELECT id, balance FROM ledger.accounts
WHERE kind = 'stock_free'
  AND owner_account_id = $1
  AND product_id = $2
  AND warehouse_building_id = $3
`

type GetStockFreeAccountParams struct {
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
}

type GetStockFreeAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// GetStockFreeAccount devuelve la cuenta stock_free de (dueño, producto, almacén);
// pgx.ErrNoRows si no existe.
func (q *Queries) GetStockFreeAccount(ctx context.Context, arg GetStockFreeAccountParams) (GetStockFreeAccountRow, error) {
	row := q.db.QueryRow(ctx, getStockFreeAccount, arg.OwnerAccountID, arg.ProductID, arg.WarehouseBuildingID)
	var i GetStockFreeAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getWorldSourceAccount = `-- name: GetWorldSourceAccount :one
SELECT id, balance FROM ledger.accounts
WHERE kind = 'world_source' AND product_id = $1
LIMIT 1
`

type GetWorldSourceAccountRow struct {
	ID      uuid.UUID
	Balance int64
}

// GetWorldSourceAccount devuelve la cuenta world_source (contrapartida física del
// banco central, ADR-022) de un producto; pgx.ErrNoRows si no existe.
func (q *Queries) GetWorldSourceAccount(ctx context.Context, productID *uuid.UUID) (GetWorldSourceAccountRow, error) {
	row := q.db.QueryRow(ctx, getWorldSourceAccount, productID)
	var i GetWorldSourceAccountRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getWorldSourceOwner = `-- name: GetWorldSourceOwner :one
SELECT owner_account_id FROM ledger.accounts
WHERE kind = 'world_source' AND owner_account_id IS NOT NULL
LIMIT 1
`

// GetWorldSourceOwner devuelve el titular (banco central) de cualquier cuenta
// world_source existente, para crear las de productos nuevos con el mismo
// titular; pgx.ErrNoRows si aún no hay ninguna.
func (q *Queries) GetWorldSourceOwner(ctx context.Context) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getWorldSourceOwner)
	var owner_account_id *uuid.UUID
	err := row.Scan(&owner_account_id)
	return owner_account_id, err
}

const growCityDemandD0 = `-- name: GrowCityDemandD0 :exec
UPDATE world.city_demand
   SET d0_per_sim_day = (d0_per_sim_day * $1) / 10000
 WHERE city_id = $2
`

type GrowCityDemandD0Params struct {
	FactorBp int64
	CityID   uuid.UUID
}

// GrowCityDemandD0 escala la demanda base D0 de TODAS las filas de una ciudad al
// subir de nivel (p. ej. +20% con factor_bp=12000): d0 = d0 * factor_bp / 10000.
func (q *Queries) GrowCityDemandD0(ctx context.Context, arg GrowCityDemandD0Params) error {
	_, err := q.db.Exec(ctx, growCityDemandD0, arg.FactorBp, arg.CityID)
	return err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger.entries (id, transaction_id, account_id, amount)
VALUES ($1, $2, $3, $4)
`

type InsertLedgerEntryParams struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
}

// InsertLedgerEntry inserta una partida de doble entrada (los triggers de 0004
// aplican saldo, no-negatividad y balance por activo diferido).
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}

const insertLedgerTransaction = `-- name: InsertLedgerTransaction :exec
INSERT INTO ledger.transactions (id, kind, sim_time_at, reference_id, description)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLedgerTransactionParams struct {
	ID          uuid.UUID
	Kind        LedgerTransactionKind
	SimTimeAt   int64
	ReferenceID *uuid.UUID
	Description *string
}

// InsertLedgerTransaction inserta la cabecera de un asiento (los IDs UUIDv7 los
// genera la aplicación, ADR-018).
func (q *Queries) InsertLedgerTransaction(ctx context.Context, arg InsertLedgerTransactionParams) error {
	_, err := q.db.Exec(ctx, insertLedgerTransaction,
		arg.ID,
		arg.Kind,
		arg.SimTimeAt,
		arg.ReferenceID,
		arg.Description,
	)
	return err
}

const isCityAccount = `-- name: IsCityAccount :one

SELECT EXISTS (
    SELECT 1 FROM auth.accounts WHERE id = $1 AND kind = 'city'
)
`

// ─── auth: identidad de comprador ciudad ──────────────────────────────────────
// IsCityAccount indica si una cuenta es una ciudad (el consumer solo consume las
// entregas cuyo comprador es una ciudad).
func (q *Queries) IsCityAccount(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isCityAccount, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const latestRegionOccupation = `-- name: LatestRegionOccupation :many

SELECT DISTINCT ON (region_id)
       region_id, industrial_occupation::float8 AS industrial_occupation
FROM analytics.region_stats
ORDER BY region_id, bucket_start_sim DESC
`

type LatestRegionOccupationRow struct {
	RegionID             uuid.UUID
	IndustrialOccupation float64
}

// ─── Fórmula laboral (GDD 5.7): salario efectivo por ciudad ───────────────────
// LatestRegionOccupation devuelve la ocupación industrial MÁS RECIENTE por región
// (última foto de region_stats): la entrada de la fórmula laboral. El job de
// analítica la escribe antes en el mismo barrido, de modo que la fórmula laboral
// consume el factor de saturación recién calculado.
func (q *Queries) LatestRegionOccupation(ctx context.Context) ([]LatestRegionOccupationRow, error) {
	rows, err := q.db.Query(ctx, latestRegionOccupation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRegionOccupationRow
	for rows.Next() {
		var i LatestRegionOccupationRow
		if err := rows.Scan(&i.RegionID, &i.IndustrialOccupation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many


SELECT id, region_id, account_id, name, level, population,
       supply_index::float8 AS supply_index, base_salary, updated_at_sim
FROM world.cities
ORDER BY id
`

type ListCitiesRow struct {
	ID           uuid.UUID
	RegionID     uuid.UUID
	AccountID    uuid.UUID
	Name         string
	Level        int32
	Population   int64
	SupplyIndex  float64
	BaseSalary   int64
	UpdatedAtSim int64
}

// =============================================================================
// Imperio Industrial — queries sqlc del Economy Balancer Service (Incremento 6b,
// GDD 5.5/5.6/18.1, ADR-020). El Balancer es el agente decisor de las ciudades:
// recalcula sus curvas de demanda (world.city_demand), publica sus solicitudes
// de compra por la API estándar del Contract Service (sin canal privilegiado) y
// CONSUME lo entregado (city stock_free → world_source, ADR-022), cerrando el
// bucle de faucets/sinks.
//
// Frontera de servicio de CÓDIGO Go, no de esquema: estas queries leen/escriben
// world.cities/city_demand, leen world.products/network_nodes/building_inventories
// y asientan en ledger.* (cash/emission/world_source/stock_free) — el paquete Go
// nunca importa internal/contracts (salvo el PORT en el composition root).
//
// Dinero y stock son int64 de punto fijo. Los NUMERIC del dominio de oferta
// (supply_index, supply_ema, saturation_factor) se proyectan/leen como float8:
// son magnitudes continuas de la curva, no dinero.
// =============================================================================
// ─── Ciudades ────────────────────────────────────────────────────────────────
// ListCities devuelve todas las ciudades para el barrido del DemandWorker y las
// métricas macro. supply_index es NUMERIC → float8.
func (q *Queries) ListCities(ctx context.Context) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCitiesRow
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.AccountID,
			&i.Name,
			&i.Level,
			&i.Population,
			&i.SupplyIndex,
			&i.BaseSalary,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCityDemand = `-- name: ListCityDemand :many

SELECT product_id, d0_per_sim_day,
       supply_ema::float8 AS supply_ema,
       saturation_factor::float8 AS saturation_factor,
       current_price, unlocked_at_level, recent_supply, updated_at_sim
FROM world.city_demand
WHERE city_id = $1
ORDER BY product_id
`

type ListCityDemandRow struct {
	ProductID        uuid.UUID
	D0PerSimDay      int64
	SupplyEma        float64
	SaturationFactor float64
	CurrentPrice     int64
	UnlockedAtLevel  int32
	RecentSupply     int64
	UpdatedAtSim     int64
}

// ─── Curva de demanda ─────────────────────────────────────────────────────────
// ListCityDemand devuelve las filas de la curva de demanda de una ciudad para el
// recálculo (todas; el DemandWorker filtra las activas por unlocked_at_level).
// supply_ema y saturation_factor son NUMERIC → float8.
func (q *Queries) ListCityDemand(ctx context.Context, cityID uuid.UUID) ([]ListCityDemandRow, error) {
	rows, err := q.db.Query(ctx, listCityDemand, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCityDemandRow
	for rows.Next() {
		var i ListCityDemandRow
		if err := rows.Scan(
			&i.ProductID,
			&i.D0PerSimDay,
			&i.SupplyEma,
			&i.SaturationFactor,
			&i.CurrentPrice,
			&i.UnlockedAtLevel,
			&i.RecentSupply,
			&i.UpdatedAtSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many

SELECT id, tax_rate_bp, canon_base
FROM world.regions
ORDER BY id
`

type ListRegionsRow struct {
	ID        uuid.UUID
	TaxRateBp int32
	CanonBase int64
}

// ─── Analítica macro: estadísticas regionales (analytics.region_stats) ────────
// ListRegions devuelve las regiones con su fiscalidad vigente (para el ajuste
// fiscal) y es la lista maestra sobre la que el job itera region_stats.
func (q *Queries) ListRegions(ctx context.Context) ([]ListRegionsRow, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegionsRow
	for rows.Next() {
		var i ListRegionsRow
		if err := rows.Scan(&i.ID, &i.TaxRateBp, &i.CanonBase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCity = `-- name: LockCity :one
SELECT id, region_id, account_id, name, level, population,
       supply_index::float8 AS supply_index, base_salary, updated_at_sim
FROM world.cities
WHERE id = $1
FOR UPDATE
`

type LockCityRow struct {
	ID           uuid.UUID
	RegionID     uuid.UUID
	AccountID    uuid.UUID
	Name         string
	Level        int32
	Population   int64
	SupplyIndex  float64
	BaseSalary   int64
	UpdatedAtSim int64
}

// LockCity bloquea una ciudad (FOR UPDATE) para su recálculo en una transacción
// serializable; pgx.ErrNoRows si desapareció.
func (q *Queries) LockCity(ctx context.Context, id uuid.UUID) (LockCityRow, error) {
	row := q.db.QueryRow(ctx, lockCity, id)
	var i LockCityRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.AccountID,
		&i.Name,
		&i.Level,
		&i.Population,
		&i.SupplyIndex,
		&i.BaseSalary,
		&i.UpdatedAtSim,
	)
	return i, err
}

const moneySupply = `-- name: MoneySupply :one

SELECT COALESCE(SUM(balance), 0)::bigint AS total
FROM ledger.accounts
WHERE kind IN ('cash', 'escrow', 'guarantee')
`

// ─── Macro: masa monetaria (faucet vs. sinks, GDD 5.5) ────────────────────────
// MoneySupply devuelve la masa monetaria total (suma de cuentas cash + escrow +
// guarantee): el gauge macro del bucle faucet/sink que el Balancer observa.
//
// DECISIÓN VINCULANTE (coherencia macro): la masa monetaria es EXACTAMENTE
// cash+escrow+guarantee — el dinero en circulación (cash) más el bloqueado
// (escrow del comprador, guarantee del vendedor). Se EXCLUYE 'custody': por el
// esquema 0004 una cuenta custody lleva product_id NOT NULL, es decir contiene
// STOCK (la mercancía de un CCRI-Flete), no dinero — su lado monetario ya está
// contado como el escrow del flete. Sumar su saldo mezclaría unidades de stock
// con dinero y ROMPERÍA la invariante emisión−absorción = Δmasa monetaria: el
// activo "dinero" (product_id IS NULL) balancea a cero por asiento sobre
// cash+escrow+guarantee+sink+emission, de modo que
// Δ(cash+escrow+guarantee) = −Δ(sink) − Δ(emission) = emisión − absorción.
func (q *Queries) MoneySupply(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, moneySupply)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const recentEconomyIndicators = `-- name: RecentEconomyIndicators :many

SELECT bucket_start_sim, money_supply, simulated_gdp
FROM analytics.economy_indicators
ORDER BY bucket_start_sim DESC
LIMIT $1
`

type RecentEconomyIndicatorsRow struct {
	BucketStartSim int64
	MoneySupply    int64
	SimulatedGdp   int64
}

// ─── Ajuste fiscal algorítmico (banco central algorítmico, GDD 5.5) ───────────
// RecentEconomyIndicators devuelve los últimos indicadores macro (masa monetaria
// y PIB simulado) para medir la tendencia inflación/deflación del lazo fiscal.
func (q *Queries) RecentEconomyIndicators(ctx context.Context, rowLimit int32) ([]RecentEconomyIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, recentEconomyIndicators, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentEconomyIndicatorsRow
	for rows.Next() {
		var i RecentEconomyIndicatorsRow
		if err := rows.Scan(&i.BucketStartSim, &i.MoneySupply, &i.SimulatedGdp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionActiveBuildings = `-- name: RegionActiveBuildings :many
SELECT region_id, COUNT(*)::int AS active_buildings
FROM world.buildings
WHERE status = 'operational'
GROUP BY region_id
`

type RegionActiveBuildingsRow struct {
	RegionID        uuid.UUID
	ActiveBuildings int32
}

// RegionActiveBuildings cuenta los edificios OPERATIVOS por región (ocupación
// industrial: numerador del factor de saturación laboral, GDD 5.7).
func (q *Queries) RegionActiveBuildings(ctx context.Context) ([]RegionActiveBuildingsRow, error) {
	rows, err := q.db.Query(ctx, regionActiveBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegionActiveBuildingsRow
	for rows.Next() {
		var i RegionActiveBuildingsRow
		if err := rows.Scan(&i.RegionID, &i.ActiveBuildings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionSettledStats = `-- name: RegionSettledStats :many
SELECT n.region_id,
       COUNT(*)::int AS contracts_settled,
       COALESCE(SUM(c.quantity_delivered * c.unit_price), 0)::bigint AS trade_volume
FROM ledger.contracts c
JOIN world.network_nodes n ON n.id = c.destination_node_id
WHERE c.status = 'settled'
  AND c.settled_at_sim >= $1::bigint
  AND c.settled_at_sim <  $2::bigint
GROUP BY n.region_id
`

type RegionSettledStatsParams struct {
	BucketStart int64
	BucketEnd   int64
}

type RegionSettledStatsRow struct {
	RegionID         uuid.UUID
	ContractsSettled int32
	TradeVolume      int64
}

// RegionSettledStats agrega los contratos LIQUIDADOS del bucket por región,
// atribuidos por su NODO DE DESTINO (lado de consumo/entrega; atribución única
// que evita el doble conteo cuando origen y destino están en regiones distintas).
func (q *Queries) RegionSettledStats(ctx context.Context, arg RegionSettledStatsParams) ([]RegionSettledStatsRow, error) {
	rows, err := q.db.Query(ctx, regionSettledStats, arg.BucketStart, arg.BucketEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegionSettledStatsRow
	for rows.Next() {
		var i RegionSettledStatsRow
		if err := rows.Scan(&i.RegionID, &i.ContractsSettled, &i.TradeVolume); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCityBaseSalary = `-- name: UpdateCityBaseSalary :exec
UPDATE world.cities
   SET base_salary = $1
 WHERE id = $2
`

type UpdateCityBaseSalaryParams struct {
	BaseSalary int64
	ID         uuid.UUID
}

// UpdateCityBaseSalary escribe el salario EFECTIVO recalculado por el Balancer en
// world.cities.base_salary (DECISIÓN: base_salary almacenado ES el salario
// efectivo = salario_base(nivel) × factor_saturación(ocupación regional); el
// módulo de producción del 6a lo lee tal cual para el sink de salario, GDD 5.7).
func (q *Queries) UpdateCityBaseSalary(ctx context.Context, arg UpdateCityBaseSalaryParams) error {
	_, err := q.db.Exec(ctx, updateCityBaseSalary, arg.BaseSalary, arg.ID)
	return err
}

const updateCityDemandCurve = `-- name: UpdateCityDemandCurve :exec
UPDATE world.city_demand
   SET supply_ema = $1::float8,
       saturation_factor = $2::float8,
       current_price = $3,
       recent_supply = 0,
       updated_at_sim = $4
 WHERE city_id = $5 AND product_id = $6
`

type UpdateCityDemandCurveParams struct {
	SupplyEma        float64
	SaturationFactor float64
	CurrentPrice     int64
	UpdatedAtSim     int64
	CityID           uuid.UUID
	ProductID        uuid.UUID
}

// UpdateCityDemandCurve escribe el resultado del recálculo de una (ciudad,
// producto): supply_ema (con suelo > 0), saturation_factor (acotado), el precio
// efectivo (ya clampado en [price_floor, price_ceiling]) y el sello de recálculo;
// RESETEA recent_supply a 0 (la ventana de oferta reciente arranca de nuevo).
func (q *Queries) UpdateCityDemandCurve(ctx context.Context, arg UpdateCityDemandCurveParams) error {
	_, err := q.db.Exec(ctx, updateCityDemandCurve,
		arg.SupplyEma,
		arg.SaturationFactor,
		arg.CurrentPrice,
		arg.UpdatedAtSim,
		arg.CityID,
		arg.ProductID,
	)
	return err
}

const updateCityGrowth = `-- name: UpdateCityGrowth :exec
UPDATE world.cities
   SET level = $1,
       population = $2,
       supply_index = $3::float8,
       updated_at_sim = $4
 WHERE id = $5
`

type UpdateCityGrowthParams struct {
	Level        int32
	Population   int64
	SupplyIndex  float64
	UpdatedAtSim int64
	ID           uuid.UUID
}

// UpdateCityGrowth escribe el estado de crecimiento de una ciudad tras el
// recálculo/máquina de niveles: nivel, población, supply_index y updated_at_sim.
func (q *Queries) UpdateCityGrowth(ctx context.Context, arg UpdateCityGrowthParams) error {
	_, err := q.db.Exec(ctx, updateCityGrowth,
		arg.Level,
		arg.Population,
		arg.SupplyIndex,
		arg.UpdatedAtSim,
		arg.ID,
	)
	return err
}

const updateRegionFiscal = `-- name: UpdateRegionFiscal :exec
UPDATE world.regions
   SET tax_rate_bp = $1,
       canon_base  = $2,
       updated_at  = now()
 WHERE id = $3
`

type UpdateRegionFiscalParams struct {
	TaxRateBp int32
	CanonBase int64
	ID        uuid.UUID
}

// UpdateRegionFiscal escribe la fiscalidad ajustada de una región (tax_rate_bp y
// canon_base) dentro de sus rangos. Cambios pequeños y acotados: lazo suave.
func (q *Queries) UpdateRegionFiscal(ctx context.Context, arg UpdateRegionFiscalParams) error {
	_, err := q.db.Exec(ctx, updateRegionFiscal, arg.TaxRateBp, arg.CanonBase, arg.ID)
	return err
}

const upsertCitySnapshot = `-- name: UpsertCitySnapshot :exec

INSERT INTO analytics.city_snapshots (
    city_id, bucket_start_sim, level, population, supply_index)
VALUES (
    $1, $2, $3,
    $4, $5::float8)
ON CONFLICT (city_id, bucket_start_sim) DO UPDATE SET
    level        = EXCLUDED.level,
    population   = EXCLUDED.population,
    supply_index = EXCLUDED.supply_index
`

type UpsertCitySnapshotParams struct {
	CityID         uuid.UUID
	BucketStartSim int64
	Level          int32
	Population     int64
	SupplyIndex    float64
}

// ─── Analítica macro: fotos de ciudad (analytics.city_snapshots) ──────────────
// UpsertCitySnapshot asienta (o reescribe) la foto (ciudad, bucket): nivel,
// población y supply_index actuales de la ciudad.
func (q *Queries) UpsertCitySnapshot(ctx context.Context, arg UpsertCitySnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertCitySnapshot,
		arg.CityID,
		arg.BucketStartSim,
		arg.Level,
		arg.Population,
		arg.SupplyIndex,
	)
	return err
}

const upsertEconomyIndicators = `-- name: UpsertEconomyIndicators :exec
INSERT INTO analytics.economy_indicators (
    bucket_start_sim, money_supply, simulated_gdp, emission_total, absorption_total,
    active_bot_count, active_human_count, global_depletion_rate, depletion_projection)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8::float8, $9)
ON CONFLICT (bucket_start_sim) DO UPDATE SET
    money_supply          = EXCLUDED.money_supply,
    simulated_gdp         = EXCLUDED.simulated_gdp,
    emission_total        = EXCLUDED.emission_total,
    absorption_total      = EXCLUDED.absorption_total,
    active_bot_count      = EXCLUDED.active_bot_count,
    active_human_count    = EXCLUDED.active_human_count,
    global_depletion_rate = EXCLUDED.global_depletion_rate,
    depletion_projection  = EXCLUDED.depletion_projection
`

type UpsertEconomyIndicatorsParams struct {
	BucketStartSim      int64
	MoneySupply         int64
	SimulatedGdp        int64
	EmissionTotal       int64
	AbsorptionTotal     int64
	ActiveBotCount      int32
	ActiveHumanCount    int32
	GlobalDepletionRate float64
	DepletionProjection []byte
}

// UpsertEconomyIndicators asienta (o reescribe) la fila del bucket de
// analytics.economy_indicators. Idempotente: cada barrido dentro del bucket
// RECALCULA el bucket completo y sobrescribe (el bucle de analítica corre muchas
// veces por bucket; el resultado converge conforme se acumulan transacciones).
func (q *Queries) UpsertEconomyIndicators(ctx context.Context, arg UpsertEconomyIndicatorsParams) error {
	_, err := q.db.Exec(ctx, upsertEconomyIndicators,
		arg.BucketStartSim,
		arg.MoneySupply,
		arg.SimulatedGdp,
		arg.EmissionTotal,
		arg.AbsorptionTotal,
		arg.ActiveBotCount,
		arg.ActiveHumanCount,
		arg.GlobalDepletionRate,
		arg.DepletionProjection,
	)
	return err
}

const upsertRegionStats = `-- name: UpsertRegionStats :exec
INSERT INTO analytics.region_stats (
    region_id, bucket_start_sim, industrial_occupation, active_buildings,
    contracts_settled, trade_volume)
VALUES (
    $1, $2, $3::float8,
    $4, $5, $6)
ON CONFLICT (region_id, bucket_start_sim) DO UPDATE SET
    industrial_occupation = EXCLUDED.industrial_occupation,
    active_buildings      = EXCLUDED.active_buildings,
    contracts_settled     = EXCLUDED.contracts_settled,
    trade_volume          = EXCLUDED.trade_volume
`

type UpsertRegionStatsParams struct {
	RegionID             uuid.UUID
	BucketStartSim       int64
	IndustrialOccupation float64
	ActiveBuildings      int32
	ContractsSettled     int32
	TradeVolume          int64
}

// UpsertRegionStats asienta (o reescribe) la fila (región, bucket) de
// analytics.region_stats. industrial_occupation es el factor de saturación
// laboral normalizado que calcula el job (edificios activos / capacidad de
// referencia de la región, acotado).
func (q *Queries) UpsertRegionStats(ctx context.Context, arg UpsertRegionStatsParams) error {
	_, err := q.db.Exec(ctx, upsertRegionStats,
		arg.RegionID,
		arg.BucketStartSim,
		arg.IndustrialOccupation,
		arg.ActiveBuildings,
		arg.ContractsSettled,
		arg.TradeVolume,
	)
	return err
}
