// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
)

type LedgerContractStatus string

const (
	LedgerContractStatusActive  LedgerContractStatus = "active"
	LedgerContractStatusSettled LedgerContractStatus = "settled"
	LedgerContractStatusFailed  LedgerContractStatus = "failed"
)

func (e *LedgerContractStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerContractStatus(s)
	case string:
		*e = LedgerContractStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerContractStatus: %T", src)
	}
	return nil
}

type NullLedgerContractStatus struct {
	LedgerContractStatus LedgerContractStatus
	Valid                bool // Valid is true if LedgerContractStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerContractStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerContractStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerContractStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerContractStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerContractStatus), nil
}

type LedgerTransactionKind string

const (
	LedgerTransactionKindSeedCapital          LedgerTransactionKind = "seed_capital"
	LedgerTransactionKindBotCapitalization    LedgerTransactionKind = "bot_capitalization"
	LedgerTransactionKindBotRetirement        LedgerTransactionKind = "bot_retirement"
	LedgerTransactionKindPublicationLock      LedgerTransactionKind = "publication_lock"
	LedgerTransactionKindPublicationRelease   LedgerTransactionKind = "publication_release"
	LedgerTransactionKindAcceptanceLock       LedgerTransactionKind = "acceptance_lock"
	LedgerTransactionKindContractConfirmation LedgerTransactionKind = "contract_confirmation"
	LedgerTransactionKindDeliverySettlement   LedgerTransactionKind = "delivery_settlement"
	LedgerTransactionKindCustodyLoad          LedgerTransactionKind = "custody_load"
	LedgerTransactionKindCustodyRelease       LedgerTransactionKind = "custody_release"
	LedgerTransactionKindProductionOutput     LedgerTransactionKind = "production_output"
	LedgerTransactionKindConsumption          LedgerTransactionKind = "consumption"
	LedgerTransactionKindWage                 LedgerTransactionKind = "wage"
	LedgerTransactionKindMaintenance          LedgerTransactionKind = "maintenance"
	LedgerTransactionKindTax                  LedgerTransactionKind = "tax"
	LedgerTransactionKindCanon                LedgerTransactionKind = "canon"
	LedgerTransactionKindTransfer             LedgerTransactionKind = "transfer"
	LedgerTransactionKindAuction              LedgerTransactionKind = "auction"
	LedgerTransactionKindReconciliation       LedgerTransactionKind = "reconciliation"
	LedgerTransactionKindPowerSpot            LedgerTransactionKind = "power_spot"
)

func (e *LedgerTransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerTransactionKind(s)
	case string:
		*e = LedgerTransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerTransactionKind: %T", src)
	}
	return nil
}

type NullLedgerTransactionKind struct {
	LedgerTransactionKind LedgerTransactionKind
	Valid                 bool // Valid is true if LedgerTransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerTransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerTransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerTransactionKind), nil
}

type WorldBatchStatus string

const (
	WorldBatchStatusQueued          WorldBatchStatus = "queued"
	WorldBatchStatusRunning         WorldBatchStatus = "running"
	WorldBatchStatusPausedNoFuel    WorldBatchStatus = "paused_no_fuel"
	WorldBatchStatusPausedNoWorkers WorldBatchStatus = "paused_no_workers"
	WorldBatchStatusCompleted       WorldBatchStatus = "completed"
	WorldBatchStatusCancelled       WorldBatchStatus = "cancelled"
	WorldBatchStatusPausedNoPower   WorldBatchStatus = "paused_no_power"
)

func (e *WorldBatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldBatchStatus(s)
	case string:
		*e = WorldBatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldBatchStatus: %T", src)
	}
	return nil
}

type NullWorldBatchStatus struct {
	WorldBatchStatus WorldBatchStatus
	Valid            bool // Valid is true if WorldBatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorldBatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldBatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldBatchStatus), nil
}

type WorldPowerRole string

const (
	WorldPowerRoleGenerator WorldPowerRole = "generator"
	WorldPowerRoleConsumer  WorldPowerRole = "consumer"
)

func (e *WorldPowerRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldPowerRole(s)
	case string:
		*e = WorldPowerRole(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldPowerRole: %T", src)
	}
	return nil
}

type NullWorldPowerRole struct {
	WorldPowerRole WorldPowerRole
	Valid          bool // Valid is true if WorldPowerRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldPowerRole) Scan(value interface{}) error {
	if value == nil {
		ns.WorldPowerRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldPowerRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldPowerRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldPowerRole), nil
}

type WorldProductClass string

const (
	WorldProductClassBasic  WorldProductClass = "basic"
	WorldProductClassLuxury WorldProductClass = "luxury"
)

func (e *WorldProductClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldProductClass(s)
	case string:
		*e = WorldProductClass(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldProductClass: %T", src)
	}
	return nil
}

type NullWorldProductClass struct {
	WorldProductClass WorldProductClass
	Valid             bool // Valid is true if WorldProductClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldProductClass) Scan(value interface{}) error {
	if value == nil {
		ns.WorldProductClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldProductClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldProductClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldProductClass), nil
}
