// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: power.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const existsPowerSpotTick = `-- name: ExistsPowerSpotTick :one
SELECT EXISTS(
    SELECT 1 FROM world.power_spot_ticks
    WHERE region_id = $1 AND tick_sim = $2
)::bool AS present
`

type ExistsPowerSpotTickParams struct {
	RegionID uuid.UUID
	TickSim  int64
}

// ExistsPowerSpotTick es la guarda de idempotencia del tick (PK region+bucket).
func (q *Queries) ExistsPowerSpotTick(ctx context.Context, arg ExistsPowerSpotTickParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsPowerSpotTick, arg.RegionID, arg.TickSim)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const insertPowerDispatch = `-- name: InsertPowerDispatch :exec
INSERT INTO world.power_dispatches
       (region_id, tick_sim, building_id, owner_account_id, role, units, unit_price, amount)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertPowerDispatchParams struct {
	RegionID       uuid.UUID
	TickSim        int64
	BuildingID     uuid.UUID
	OwnerAccountID uuid.UUID
	Role           WorldPowerRole
	Units          int64
	UnitPrice      int64
	Amount         int64
}

// InsertPowerDispatch registra el despacho (generator) o consumo (consumer)
// de un edificio en el tick, al precio de cierre.
func (q *Queries) InsertPowerDispatch(ctx context.Context, arg InsertPowerDispatchParams) error {
	_, err := q.db.Exec(ctx, insertPowerDispatch,
		arg.RegionID,
		arg.TickSim,
		arg.BuildingID,
		arg.OwnerAccountID,
		arg.Role,
		arg.Units,
		arg.UnitPrice,
		arg.Amount,
	)
	return err
}

const insertPowerSpotTick = `-- name: InsertPowerSpotTick :exec

INSERT INTO world.power_spot_ticks
       (region_id, tick_sim, interval_sim, closing_price,
        demand_units, supplied_units, curtailed_units, curtailed_buildings)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertPowerSpotTickParams struct {
	RegionID           uuid.UUID
	TickSim            int64
	IntervalSim        int64
	ClosingPrice       int64
	DemandUnits        int64
	SuppliedUnits      int64
	CurtailedUnits     int64
	CurtailedBuildings int32
}

// ─── Resultado del tick (plano físico) ────────────────────────────────────────
// InsertPowerSpotTick registra el resultado agregado del tick. INSERT plano:
// bajo SERIALIZABLE, dos instancias sobre el mismo bucket abortan una a la
// otra (la guarda ExistsPowerSpotTick evita el caso común).
func (q *Queries) InsertPowerSpotTick(ctx context.Context, arg InsertPowerSpotTickParams) error {
	_, err := q.db.Exec(ctx, insertPowerSpotTick,
		arg.RegionID,
		arg.TickSim,
		arg.IntervalSim,
		arg.ClosingPrice,
		arg.DemandUnits,
		arg.SuppliedUnits,
		arg.CurtailedUnits,
		arg.CurtailedBuildings,
	)
	return err
}

const listPowerConsumers = `-- name: ListPowerConsumers :many

SELECT pb.id AS batch_id, pb.status AS batch_status,
       b.id AS building_id, b.owner_account_id, b.last_curtailed_at_sim,
       r.power_per_hour,
       COALESCE(bid.unit_price, 0) AS bid_price,
       COALESCE(cash.balance, 0) AS owner_cash
FROM world.production_batches pb
JOIN world.buildings b ON b.id = pb.building_id
JOIN world.recipes r ON r.id = pb.recipe_id
LEFT JOIN world.power_bids bid ON bid.building_id = b.id
LEFT JOIN ledger.accounts cash
       ON cash.kind = 'cash' AND cash.owner_account_id = b.owner_account_id
WHERE b.region_id = $1
  AND b.status = 'operational'
  AND pb.status IN ('running', 'paused_no_power')
  AND r.power_per_hour > 0
  AND EXISTS (SELECT 1 FROM world.power_lines pl
              WHERE pl.region_id = b.region_id AND pl.status = 'operational'
                AND ST_DWithin(pl.path, ST_Centroid(b.footprint), $2::float8))
ORDER BY b.id, pb.id
`

type ListPowerConsumersParams struct {
	RegionID       uuid.UUID
	ConnectRadiusM float64
}

type ListPowerConsumersRow struct {
	BatchID            uuid.UUID
	BatchStatus        WorldBatchStatus
	BuildingID         uuid.UUID
	OwnerAccountID     uuid.UUID
	LastCurtailedAtSim int64
	PowerPerHour       int64
	BidPrice           int64
	OwnerCash          int64
}

// ─── Participantes del tick ───────────────────────────────────────────────────
// ListPowerConsumers lista la demanda candidata de una región: lotes activos
// (running o paused_no_power) de recetas eléctricas en edificios operativos
// CONECTADOS (a <= radio de una línea operativa de su región, medido desde el
// centroide del footprint — el mismo ancla que su network_node). Trae la puja
// explícita (0 = sin fila: rige el default) y la caja del dueño para la
// exclusión por insolvencia (GDD 5.9: sin compra, sin deuda).
func (q *Queries) ListPowerConsumers(ctx context.Context, arg ListPowerConsumersParams) ([]ListPowerConsumersRow, error) {
	rows, err := q.db.Query(ctx, listPowerConsumers, arg.RegionID, arg.ConnectRadiusM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPowerConsumersRow
	for rows.Next() {
		var i ListPowerConsumersRow
		if err := rows.Scan(
			&i.BatchID,
			&i.BatchStatus,
			&i.BuildingID,
			&i.OwnerAccountID,
			&i.LastCurtailedAtSim,
			&i.PowerPerHour,
			&i.BidPrice,
			&i.OwnerCash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerGenerators = `-- name: ListPowerGenerators :many
SELECT b.id AS building_id, b.owner_account_id, b.level,
       bt.level_curve,
       ppt.capacity, ppt.fuel_product_id, ppt.fuel_per_unit,
       fp.code AS fuel_code,
       po.unit_price AS offer_price,
       COALESCE(bi.quantity, 0) AS fuel_physical,
       COALESCE(sf.balance, 0) AS fuel_ledger
FROM world.buildings b
JOIN world.power_plant_types ppt ON ppt.building_type_id = b.building_type_id
JOIN world.building_types bt ON bt.id = b.building_type_id
JOIN world.power_offers po ON po.building_id = b.id
LEFT JOIN world.products fp ON fp.id = ppt.fuel_product_id
LEFT JOIN world.building_inventories bi
       ON bi.building_id = b.id AND bi.product_id = ppt.fuel_product_id
LEFT JOIN ledger.accounts sf
       ON sf.kind = 'stock_free' AND sf.owner_account_id = b.owner_account_id
      AND sf.product_id = ppt.fuel_product_id AND sf.warehouse_building_id = b.id
WHERE b.region_id = $1
  AND b.status = 'operational'
  AND EXISTS (SELECT 1 FROM world.power_lines pl
              WHERE pl.region_id = b.region_id AND pl.status = 'operational'
                AND ST_DWithin(pl.path, ST_Centroid(b.footprint), $2::float8))
ORDER BY po.unit_price, b.id
`

type ListPowerGeneratorsParams struct {
	RegionID       uuid.UUID
	ConnectRadiusM float64
}

type ListPowerGeneratorsRow struct {
	BuildingID     uuid.UUID
	OwnerAccountID uuid.UUID
	Level          int32
	LevelCurve     []byte
	Capacity       int64
	FuelProductID  *uuid.UUID
	FuelPerUnit    int64
	FuelCode       *string
	OfferPrice     int64
	FuelPhysical   int64
	FuelLedger     int64
}

// ListPowerGenerators lista la oferta candidata: centrales operativas
// conectadas CON oferta publicada. Para las térmicas trae el combustible en
// los dos planos (físico e inventario contable stock_free): la capacidad
// ofertable se limita en Go por min(físico, contable)/fuel_per_unit — sin
// combustible no despachan (GDD 5.8).
func (q *Queries) ListPowerGenerators(ctx context.Context, arg ListPowerGeneratorsParams) ([]ListPowerGeneratorsRow, error) {
	rows, err := q.db.Query(ctx, listPowerGenerators, arg.RegionID, arg.ConnectRadiusM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPowerGeneratorsRow
	for rows.Next() {
		var i ListPowerGeneratorsRow
		if err := rows.Scan(
			&i.BuildingID,
			&i.OwnerAccountID,
			&i.Level,
			&i.LevelCurve,
			&i.Capacity,
			&i.FuelProductID,
			&i.FuelPerUnit,
			&i.FuelCode,
			&i.OfferPrice,
			&i.FuelPhysical,
			&i.FuelLedger,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerRegions = `-- name: ListPowerRegions :many


SELECT r.id AS region_id, r.name,
       COALESCE((SELECT MAX(t.tick_sim) FROM world.power_spot_ticks t
                 WHERE t.region_id = r.id), -1)::bigint AS last_tick_sim
FROM world.regions r
WHERE EXISTS (SELECT 1 FROM world.power_lines pl
              WHERE pl.region_id = r.id AND pl.status = 'operational')
ORDER BY r.id
`

type ListPowerRegionsRow struct {
	RegionID    uuid.UUID
	Name        string
	LastTickSim int64
}

// =============================================================================
// Queries sqlc — tick del mercado spot eléctrico (GDD 5.8/18.1, ADR-025).
// El tick es del Economy Balancer (PowerWorker, proceso engine): cada región
// con líneas operativas casa oferta (centrales con power_offers) y demanda
// (lotes activos de recetas eléctricas conectadas) por orden de mérito, con
// precio de cierre uniforme, recorte rotatorio por prioridad inversa de puja
// y pagos consumidores→generadores en UN asiento power_spot por tick.
//
// Frontera de servicio de CÓDIGO Go, no de esquema (SAD §7): estas queries
// leen/escriben world.* y ledger.* sin importar los paquetes world/contracts.
// El soporte de ledger (GetCashAccount, GetStockFreeAccount, world_source,
// InsertLedgerTransaction/Entry) vive en balancer.sql y se reutiliza.
// =============================================================================
// ─── Regiones con red ─────────────────────────────────────────────────────────
// ListPowerRegions lista las regiones con al menos una línea operativa (las
// únicas con pool eléctrico) y el sello del último tick liquidado (-1 si
// ninguno) para decidir el bucket vencido en Go. La subconsulta escalar de
// MAX(tick_sim) resuelve con un escaneo hacia atrás del PK (region_id,
// tick_sim): coste O(1) por región aunque el histórico de ticks crezca.
func (q *Queries) ListPowerRegions(ctx context.Context) ([]ListPowerRegionsRow, error) {
	rows, err := q.db.Query(ctx, listPowerRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPowerRegionsRow
	for rows.Next() {
		var i ListPowerRegionsRow
		if err := rows.Scan(&i.RegionID, &i.Name, &i.LastTickSim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBuildingCurtailed = `-- name: MarkBuildingCurtailed :exec
UPDATE world.buildings
   SET last_curtailed_at_sim = $1, updated_at_sim = $1
 WHERE id = $2
`

type MarkBuildingCurtailedParams struct {
	SimNow int64
	ID     uuid.UUID
}

// MarkBuildingCurtailed sella la rotación del recorte (GDD 5.8): el recortado
// más reciente será el último candidato del próximo recorte entre pujas
// iguales.
func (q *Queries) MarkBuildingCurtailed(ctx context.Context, arg MarkBuildingCurtailedParams) error {
	_, err := q.db.Exec(ctx, markBuildingCurtailed, arg.SimNow, arg.ID)
	return err
}

const pauseRunningBatchesNoPower = `-- name: PauseRunningBatchesNoPower :many
UPDATE world.production_batches
   SET status = 'paused_no_power', started_at_sim = NULL, updated_at_sim = $1
 WHERE building_id = $2 AND status = 'running'
RETURNING id
`

type PauseRunningBatchesNoPowerParams struct {
	SimNow     int64
	BuildingID uuid.UUID
}

// PauseRunningBatchesNoPower pausa los lotes en marcha de un edificio sin
// suministro (recorte/insolvencia/desconexión): suelta el reloj como toda
// pausa (el progreso del lote se pierde, GDD 5.9 — pausa, nunca deuda).
func (q *Queries) PauseRunningBatchesNoPower(ctx context.Context, arg PauseRunningBatchesNoPowerParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, pauseRunningBatchesNoPower, arg.SimNow, arg.BuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshPlantFuelMirror = `-- name: RefreshPlantFuelMirror :exec
UPDATE world.buildings
   SET fuel_stock = COALESCE((SELECT quantity FROM world.building_inventories
                              WHERE building_id = $1
                                AND product_id = $2), 0)
 WHERE id = $1
`

type RefreshPlantFuelMirrorParams struct {
	BuildingID uuid.UUID
	ProductID  uuid.UUID
}

// RefreshPlantFuelMirror refresca la columna espejo fuel_stock de una térmica
// tras quemar combustible (v1.3: espejo del inventario físico, visibilidad).
func (q *Queries) RefreshPlantFuelMirror(ctx context.Context, arg RefreshPlantFuelMirrorParams) error {
	_, err := q.db.Exec(ctx, refreshPlantFuelMirror, arg.BuildingID, arg.ProductID)
	return err
}

const resumeNoPowerBatches = `-- name: ResumeNoPowerBatches :many
UPDATE world.production_batches
   SET status = 'running', started_at_sim = $1, updated_at_sim = $1
 WHERE building_id = $2 AND status = 'paused_no_power'
RETURNING id
`

type ResumeNoPowerBatchesParams struct {
	SimNow     *int64
	BuildingID uuid.UUID
}

// ResumeNoPowerBatches reanuda los lotes pausados por suministro de un
// edificio servido, rearrancando el reloj del lote.
func (q *Queries) ResumeNoPowerBatches(ctx context.Context, arg ResumeNoPowerBatchesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, resumeNoPowerBatches, arg.SimNow, arg.BuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBuildingPowered = `-- name: SetBuildingPowered :exec

UPDATE world.buildings
   SET powered_until_sim = $1,
       powered_rate = $2,
       updated_at_sim = $3
 WHERE id = $4
`

type SetBuildingPoweredParams struct {
	PoweredUntilSim int64
	PoweredRate     int64
	SimNow          int64
	ID              uuid.UUID
}

// ─── Efectos sobre el mundo ───────────────────────────────────────────────────
// SetBuildingPowered fija la cobertura de suministro de un edificio: al servir,
// until = tick + intervalo × 1.5 (la gracia absorbe el desfase wall-clock) y
// rate = power_per_hour FACTURADO; al NO servir (recorte/insolvencia), el tick
// la CIERRA (until = tick, rate = 0) — sin ese cierre, la gracia residual del
// tick anterior dejaría producir con energía no comprada.
func (q *Queries) SetBuildingPowered(ctx context.Context, arg SetBuildingPoweredParams) error {
	_, err := q.db.Exec(ctx, setBuildingPowered,
		arg.PoweredUntilSim,
		arg.PoweredRate,
		arg.SimNow,
		arg.ID,
	)
	return err
}
