// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contracts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBoardPublications = `-- name: CountBoardPublications :one
SELECT count(*) FROM ledger.publications
WHERE channel = 'board' AND status IN ('draw_window', 'open', 'micro_window')
`

// CountBoardPublications cuenta las publicaciones visibles del tablón
// (gauge ii_board_open_publications).
func (q *Queries) CountBoardPublications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBoardPublications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLedgerAccount = `-- name: CreateLedgerAccount :one

INSERT INTO ledger.accounts (id, kind, owner_account_id, product_id, warehouse_building_id, reference_id)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, kind, owner_account_id, product_id, warehouse_building_id, reference_id, balance, created_at, updated_at
`

type CreateLedgerAccountParams struct {
	ID                  uuid.UUID
	Kind                LedgerAccountKind
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
	ReferenceID         *uuid.UUID
}

// ─── Soporte de ledger (cuentas espejo y asientos de bloqueo/liberación) ─────
// CreateLedgerAccount crea una cuenta del ledger (espejo de publicación o
// aceptación vía reference_id). El id (UUIDv7) lo genera la aplicación
// (ADR-018); la forma la validan los constraints de 0004/0008.
func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.ID,
		arg.Kind,
		arg.OwnerAccountID,
		arg.ProductID,
		arg.WarehouseBuildingID,
		arg.ReferenceID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dBNow = `-- name: DBNow :one
SELECT now()::timestamptz AS db_now
`

// DBNow devuelve el now() de la BD: las comparaciones de ventanas wall-clock
// (cooldown anti-parpadeo) usan siempre el reloj de la base, nunca el de la
// aplicación.
func (q *Queries) DBNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, dBNow)
	var db_now time.Time
	err := row.Scan(&db_now)
	return db_now, err
}

const getAcceptance = `-- name: GetAcceptance :one
SELECT id, publication_id, acceptor_account_id, quantity, quantity_served, status, draw_order, stock_reserve_account_id, guarantee_account_id, escrow_account_id, accepted_at, resolved_at FROM ledger.publication_acceptances WHERE id = $1
`

// GetAcceptance devuelve una aceptación por id (autorización por propiedad en
// la capa de servicio: solo el aceptante).
func (q *Queries) GetAcceptance(ctx context.Context, id uuid.UUID) (LedgerPublicationAcceptance, error) {
	row := q.db.QueryRow(ctx, getAcceptance, id)
	var i LedgerPublicationAcceptance
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.AcceptorAccountID,
		&i.Quantity,
		&i.QuantityServed,
		&i.Status,
		&i.DrawOrder,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.AcceptedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getCashAccount = `-- name: GetCashAccount :one
SELECT id, kind, owner_account_id, product_id, warehouse_building_id, reference_id, balance, created_at, updated_at FROM ledger.accounts
WHERE kind = 'cash' AND owner_account_id = $1
`

// GetCashAccount devuelve la única caja de una corporación (unicidad parcial
// ux_accounts_cash).
func (q *Queries) GetCashAccount(ctx context.Context, ownerAccountID *uuid.UUID) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getCashAccount, ownerAccountID)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContract = `-- name: GetContract :one
SELECT id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at FROM ledger.contracts WHERE id = $1
`

// GetContract devuelve un contrato por id (la autorización por partes la aplica
// la capa de servicio).
func (q *Queries) GetContract(ctx context.Context, id uuid.UUID) (LedgerContract, error) {
	row := q.db.QueryRow(ctx, getContract, id)
	var i LedgerContract
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.Channel,
		&i.BuyerAccountID,
		&i.SellerAccountID,
		&i.ProductID,
		&i.QuantityAgreed,
		&i.QuantityDelivered,
		&i.UnitPrice,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.FillBp,
		&i.StockReserveAccountID,
		&i.SellerGuaranteeAccountID,
		&i.EscrowAccountID,
		&i.ConfirmedAtSim,
		&i.SettledAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractForAcceptance = `-- name: GetContractForAcceptance :one
SELECT id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at FROM ledger.contracts
WHERE publication_id = $1
  AND (buyer_account_id = $2
       OR seller_account_id = $2)
ORDER BY confirmed_at_sim, id
LIMIT 1
`

type GetContractForAcceptanceParams struct {
	PublicationID     *uuid.UUID
	AcceptorAccountID uuid.UUID
}

// GetContractForAcceptance resuelve el contrato resultante de una aceptación
// servida. El esquema NO liga la aceptación al contrato con una FK: el vínculo
// es publication_id + el aceptante como comprador (venta) o vendedor (compra).
func (q *Queries) GetContractForAcceptance(ctx context.Context, arg GetContractForAcceptanceParams) (LedgerContract, error) {
	row := q.db.QueryRow(ctx, getContractForAcceptance, arg.PublicationID, arg.AcceptorAccountID)
	var i LedgerContract
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.Channel,
		&i.BuyerAccountID,
		&i.SellerAccountID,
		&i.ProductID,
		&i.QuantityAgreed,
		&i.QuantityDelivered,
		&i.UnitPrice,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.FillBp,
		&i.StockReserveAccountID,
		&i.SellerGuaranteeAccountID,
		&i.EscrowAccountID,
		&i.ConfirmedAtSim,
		&i.SettledAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractForUpdate = `-- name: GetContractForUpdate :one
SELECT id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at FROM ledger.contracts WHERE id = $1 FOR UPDATE
`

// GetContractForUpdate bloquea el contrato (SELECT FOR UPDATE) para el
// consumidor de entregas: fija el estado (active/settled/failed) y el
// quantity_delivered bajo el lock antes de acumular la entrega y liquidar,
// serializándose con el barrido de vencimiento (que lo bloquea con SKIP LOCKED).
func (q *Queries) GetContractForUpdate(ctx context.Context, id uuid.UUID) (LedgerContract, error) {
	row := q.db.QueryRow(ctx, getContractForUpdate, id)
	var i LedgerContract
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.Channel,
		&i.BuyerAccountID,
		&i.SellerAccountID,
		&i.ProductID,
		&i.QuantityAgreed,
		&i.QuantityDelivered,
		&i.UnitPrice,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.FillBp,
		&i.StockReserveAccountID,
		&i.SellerGuaranteeAccountID,
		&i.EscrowAccountID,
		&i.ConfirmedAtSim,
		&i.SettledAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT id, kind, owner_account_id, product_id, warehouse_building_id, reference_id, balance, created_at, updated_at FROM ledger.accounts WHERE id = $1
`

// GetLedgerAccount lee una cuenta del ledger (saldos de cuentas espejo dentro
// de la transacción que los libera).
func (q *Queries) GetLedgerAccount(ctx context.Context, id uuid.UUID) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeBuilding = `-- name: GetNodeBuilding :one
SELECT n.id, n.region_id, n.building_id, b.owner_account_id AS building_owner_account_id
FROM world.network_nodes n
LEFT JOIN world.buildings b ON b.id = n.building_id
WHERE n.id = $1
`

type GetNodeBuildingRow struct {
	ID                     uuid.UUID
	RegionID               uuid.UUID
	BuildingID             *uuid.UUID
	BuildingOwnerAccountID *uuid.UUID
}

// GetNodeBuilding devuelve un nodo del grafo logístico con el edificio que lo
// respalda (si lo hay) y su titular: la regla del CCRI exige que el origen de
// una venta y el destino de una compra sean nodos con almacén.
func (q *Queries) GetNodeBuilding(ctx context.Context, id uuid.UUID) (GetNodeBuildingRow, error) {
	row := q.db.QueryRow(ctx, getNodeBuilding, id)
	var i GetNodeBuildingRow
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.BuildingID,
		&i.BuildingOwnerAccountID,
	)
	return i, err
}

const getNodeByBuilding = `-- name: GetNodeByBuilding :one
SELECT id, region_id FROM world.network_nodes
WHERE building_id = $1
ORDER BY id
LIMIT 1
`

type GetNodeByBuildingRow struct {
	ID       uuid.UUID
	RegionID uuid.UUID
}

// GetNodeByBuilding devuelve el nodo del grafo logístico respaldado por un
// edificio: reconstruye el nodo de origen de un contrato de compra a partir del
// almacén que el aceptante-vendedor aportó (la aceptación solo persiste el
// edificio, vía la cuenta espejo de stock, no el nodo).
func (q *Queries) GetNodeByBuilding(ctx context.Context, buildingID *uuid.UUID) (GetNodeByBuildingRow, error) {
	row := q.db.QueryRow(ctx, getNodeByBuilding, buildingID)
	var i GetNodeByBuildingRow
	err := row.Scan(&i.ID, &i.RegionID)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at FROM ledger.publications WHERE id = $1
`

// GetPublication devuelve una publicación por id (la autorización de canal
// privado la aplica la capa de servicio).
func (q *Queries) GetPublication(ctx context.Context, id uuid.UUID) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, getPublication, id)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicationForUpdate = `-- name: GetPublicationForUpdate :one
SELECT id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at FROM ledger.publications WHERE id = $1 FOR UPDATE
`

// GetPublicationForUpdate bloquea la fila de la publicación para las
// operaciones que la mutan (cancelación, aceptación): las validaciones de
// estado/cantidad y la transición de ventana se deciden bajo el lock.
func (q *Queries) GetPublicationForUpdate(ctx context.Context, id uuid.UUID) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, getPublicationForUpdate, id)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSinkAccount = `-- name: GetSinkAccount :one

SELECT id, kind, owner_account_id, product_id, warehouse_building_id, reference_id, balance, created_at, updated_at FROM ledger.accounts WHERE kind = 'sink' ORDER BY id LIMIT 1
`

// ─── Cuentas de liquidación (sink del banco central, stock libre on-demand) ──
// GetSinkAccount devuelve la cuenta sink del banco central (destino de la parte
// sancionadora de la garantía en un fallo de entrega).
func (q *Queries) GetSinkAccount(ctx context.Context) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getSinkAccount)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockFreeAccount = `-- name: GetStockFreeAccount :one
SELECT id, kind, owner_account_id, product_id, warehouse_building_id, reference_id, balance, created_at, updated_at FROM ledger.accounts
WHERE kind = 'stock_free'
  AND owner_account_id = $1
  AND product_id = $2
  AND warehouse_building_id = $3
`

type GetStockFreeAccountParams struct {
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
}

// GetStockFreeAccount devuelve la cuenta de stock libre de (dueño, producto,
// almacén) — unicidad parcial ux_accounts_stock_free.
func (q *Queries) GetStockFreeAccount(ctx context.Context, arg GetStockFreeAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getStockFreeAccount, arg.OwnerAccountID, arg.ProductID, arg.WarehouseBuildingID)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAcceptance = `-- name: InsertAcceptance :one

INSERT INTO ledger.publication_acceptances (
    id, publication_id, acceptor_account_id, quantity,
    stock_reserve_account_id, guarantee_account_id, escrow_account_id)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7)
RETURNING id, publication_id, acceptor_account_id, quantity, quantity_served, status, draw_order, stock_reserve_account_id, guarantee_account_id, escrow_account_id, accepted_at, resolved_at
`

type InsertAcceptanceParams struct {
	ID                    uuid.UUID
	PublicationID         uuid.UUID
	AcceptorAccountID     uuid.UUID
	Quantity              int64
	StockReserveAccountID *uuid.UUID
	GuaranteeAccountID    *uuid.UUID
	EscrowAccountID       *uuid.UUID
}

// ─── Aceptaciones ────────────────────────────────────────────────────────────
// InsertAcceptance registra una aceptación pending_draw con sus cuentas
// espejo (reference_id = id de la aceptación), ya fondeadas en la misma
// transacción por el asiento acceptance_lock.
func (q *Queries) InsertAcceptance(ctx context.Context, arg InsertAcceptanceParams) (LedgerPublicationAcceptance, error) {
	row := q.db.QueryRow(ctx, insertAcceptance,
		arg.ID,
		arg.PublicationID,
		arg.AcceptorAccountID,
		arg.Quantity,
		arg.StockReserveAccountID,
		arg.GuaranteeAccountID,
		arg.EscrowAccountID,
	)
	var i LedgerPublicationAcceptance
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.AcceptorAccountID,
		&i.Quantity,
		&i.QuantityServed,
		&i.Status,
		&i.DrawOrder,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.AcceptedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertContract = `-- name: InsertContract :one

INSERT INTO ledger.contracts (
    id, publication_id, channel, buyer_account_id, seller_account_id,
    product_id, quantity_agreed, unit_price, origin_node_id, destination_node_id,
    deadline_sim, stock_reserve_account_id, seller_guarantee_account_id,
    escrow_account_id, confirmed_at_sim)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10,
    $11, $12,
    $13, $14,
    $15)
RETURNING id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at
`

type InsertContractParams struct {
	ID                       uuid.UUID
	PublicationID            *uuid.UUID
	Channel                  LedgerContractChannel
	BuyerAccountID           uuid.UUID
	SellerAccountID          uuid.UUID
	ProductID                uuid.UUID
	QuantityAgreed           int64
	UnitPrice                int64
	OriginNodeID             uuid.UUID
	DestinationNodeID        uuid.UUID
	DeadlineSim              int64
	StockReserveAccountID    uuid.UUID
	SellerGuaranteeAccountID uuid.UUID
	EscrowAccountID          uuid.UUID
	ConfirmedAtSim           int64
}

// ─── Contratos: creación, entrega y consulta ─────────────────────────────────
// InsertContract crea el contrato en estado active con las cuentas espejo de su
// bloqueo triple (creadas antes, en la misma transacción). El bloqueo triple lo
// asienta a continuación ledger.confirm_contract.
func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) (LedgerContract, error) {
	row := q.db.QueryRow(ctx, insertContract,
		arg.ID,
		arg.PublicationID,
		arg.Channel,
		arg.BuyerAccountID,
		arg.SellerAccountID,
		arg.ProductID,
		arg.QuantityAgreed,
		arg.UnitPrice,
		arg.OriginNodeID,
		arg.DestinationNodeID,
		arg.DeadlineSim,
		arg.StockReserveAccountID,
		arg.SellerGuaranteeAccountID,
		arg.EscrowAccountID,
		arg.ConfirmedAtSim,
	)
	var i LedgerContract
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.Channel,
		&i.BuyerAccountID,
		&i.SellerAccountID,
		&i.ProductID,
		&i.QuantityAgreed,
		&i.QuantityDelivered,
		&i.UnitPrice,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.FillBp,
		&i.StockReserveAccountID,
		&i.SellerGuaranteeAccountID,
		&i.EscrowAccountID,
		&i.ConfirmedAtSim,
		&i.SettledAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContractDelivery = `-- name: InsertContractDelivery :one
INSERT INTO ledger.contract_deliveries (
    id, contract_id, shipment_id, quantity, delivered_at_sim, on_time)
VALUES (
    $1, $2, $3,
    $4, $5, $6)
RETURNING id, contract_id, shipment_id, quantity, delivered_at_sim, on_time, created_at
`

type InsertContractDeliveryParams struct {
	ID             uuid.UUID
	ContractID     uuid.UUID
	ShipmentID     uuid.UUID
	Quantity       int64
	DeliveredAtSim int64
	OnTime         bool
}

// InsertContractDelivery registra una entrega parcial confirmada de un
// contrato (verificación de entrega acumulativa, GDD 5.3 paso 5).
func (q *Queries) InsertContractDelivery(ctx context.Context, arg InsertContractDeliveryParams) (LedgerContractDelivery, error) {
	row := q.db.QueryRow(ctx, insertContractDelivery,
		arg.ID,
		arg.ContractID,
		arg.ShipmentID,
		arg.Quantity,
		arg.DeliveredAtSim,
		arg.OnTime,
	)
	var i LedgerContractDelivery
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ShipmentID,
		&i.Quantity,
		&i.DeliveredAtSim,
		&i.OnTime,
		&i.CreatedAt,
	)
	return i, err
}

const insertContractDeliveryIfNew = `-- name: InsertContractDeliveryIfNew :one
INSERT INTO ledger.contract_deliveries (
    id, contract_id, shipment_id, quantity, delivered_at_sim, on_time)
VALUES (
    $1, $2, $3,
    $4, $5, $6)
ON CONFLICT (shipment_id) DO NOTHING
RETURNING id, contract_id, shipment_id, quantity, delivered_at_sim, on_time, created_at
`

type InsertContractDeliveryIfNewParams struct {
	ID             uuid.UUID
	ContractID     uuid.UUID
	ShipmentID     uuid.UUID
	Quantity       int64
	DeliveredAtSim int64
	OnTime         bool
}

// InsertContractDeliveryIfNew registra la entrega de un cargamento de forma
// IDEMPOTENTE: un cargamento (world.shipments) llega físicamente a su destino
// una sola vez, luego su entrega se cuenta una sola vez. Si ya existe una
// entrega para ese shipment_id (índice único ux_contract_deliveries_shipment,
// 0010), no inserta nada y no devuelve fila (pgx.ErrNoRows): reprocesar el mismo
// shipment.arrived no duplica la partida ni la cantidad entregada.
func (q *Queries) InsertContractDeliveryIfNew(ctx context.Context, arg InsertContractDeliveryIfNewParams) (LedgerContractDelivery, error) {
	row := q.db.QueryRow(ctx, insertContractDeliveryIfNew,
		arg.ID,
		arg.ContractID,
		arg.ShipmentID,
		arg.Quantity,
		arg.DeliveredAtSim,
		arg.OnTime,
	)
	var i LedgerContractDelivery
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ShipmentID,
		&i.Quantity,
		&i.DeliveredAtSim,
		&i.OnTime,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger.entries (id, transaction_id, account_id, amount)
VALUES ($1, $2, $3, $4)
`

type InsertLedgerEntryParams struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
}

// InsertLedgerEntry inserta una partida de doble entrada; los triggers aplican
// saldo, no-negatividad y (diferido) el balance por activo del asiento.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}

const insertLedgerTransaction = `-- name: InsertLedgerTransaction :exec
INSERT INTO ledger.transactions (id, kind, sim_time_at, reference_id, description)
VALUES ($1, $2, $3,
        $4, $5)
`

type InsertLedgerTransactionParams struct {
	ID          uuid.UUID
	Kind        LedgerTransactionKind
	SimTimeAt   int64
	ReferenceID *uuid.UUID
	Description *string
}

// InsertLedgerTransaction inserta la cabecera de un asiento (inmutable).
func (q *Queries) InsertLedgerTransaction(ctx context.Context, arg InsertLedgerTransactionParams) error {
	_, err := q.db.Exec(ctx, insertLedgerTransaction,
		arg.ID,
		arg.Kind,
		arg.SimTimeAt,
		arg.ReferenceID,
		arg.Description,
	)
	return err
}

const insertPublication = `-- name: InsertPublication :one


INSERT INTO ledger.publications (
    id, kind, publisher_account_id, channel, counterparty_account_id,
    product_id, quantity_total, quantity_remaining, unit_price, min_lot,
    origin_node_id, destination_node_id, delivery_sim_seconds, status,
    window_closes_at, cancel_cooldown_until,
    stock_reserve_account_id, guarantee_account_id, escrow_account_id,
    published_at_sim)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $7,
    $8, $9,
    $10, $11,
    $12, 'draw_window',
    now() + $13::bigint * interval '1 second',
    now() + $14::bigint * interval '1 second',
    $15, $16,
    $17, $18)
RETURNING id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at
`

type InsertPublicationParams struct {
	ID                    uuid.UUID
	Kind                  LedgerPublicationKind
	PublisherAccountID    uuid.UUID
	Channel               LedgerContractChannel
	CounterpartyAccountID *uuid.UUID
	ProductID             *uuid.UUID
	QuantityTotal         int64
	UnitPrice             int64
	MinLot                int64
	OriginNodeID          *uuid.UUID
	DestinationNodeID     *uuid.UUID
	DeliverySimSeconds    int64
	DrawWindowSeconds     int64
	CancelCooldownSeconds int64
	StockReserveAccountID *uuid.UUID
	GuaranteeAccountID    *uuid.UUID
	EscrowAccountID       *uuid.UUID
	PublishedAtSim        int64
}

// =============================================================================
// Imperio Industrial — queries sqlc del módulo contracts (ADR-020).
// Ciclo de publicación y aceptación del CCRI (GDD 5.3/5.3.1). Las invariantes
// de dinero/stock las garantizan los triggers de 0004_ledger (saldo por
// cuenta, doble entrada diferida, no-negatividad, inmutabilidad): aquí nunca
// se recalculan saldos. Las ventanas wall-clock (sorteo, micro-ventana,
// cooldown) se calculan SIEMPRE con now() de la BD, nunca con el reloj de la
// aplicación.
//
// La frontera de módulo es de código Go, no de esquema: estas queries asientan
// en ledger.* (publicaciones, aceptaciones, cuentas espejo y partidas de los
// bloqueos) y leen world.* (validación de productos y nodos).
// =============================================================================
// ─── Publicaciones ───────────────────────────────────────────────────────────
// InsertPublication crea la publicación con su ventana de sorteo y su cooldown
// anti-parpadeo calculados con now() de la BD. Las cuentas espejo de la
// garantía propia (creadas antes, en la misma transacción) llegan por id; los
// CHECK de 0004 exigen las que corresponden al kind.
func (q *Queries) InsertPublication(ctx context.Context, arg InsertPublicationParams) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, insertPublication,
		arg.ID,
		arg.Kind,
		arg.PublisherAccountID,
		arg.Channel,
		arg.CounterpartyAccountID,
		arg.ProductID,
		arg.QuantityTotal,
		arg.UnitPrice,
		arg.MinLot,
		arg.OriginNodeID,
		arg.DestinationNodeID,
		arg.DeliverySimSeconds,
		arg.DrawWindowSeconds,
		arg.CancelCooldownSeconds,
		arg.StockReserveAccountID,
		arg.GuaranteeAccountID,
		arg.EscrowAccountID,
		arg.PublishedAtSim,
	)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShipment = `-- name: InsertShipment :one
INSERT INTO world.shipments (
    id, owner_account_id, product_id, quantity, contract_id, at_node_id,
    status, updated_at_sim)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8)
RETURNING id
`

type InsertShipmentParams struct {
	ID             uuid.UUID
	OwnerAccountID uuid.UUID
	ProductID      uuid.UUID
	Quantity       int64
	ContractID     *uuid.UUID
	AtNodeID       *uuid.UUID
	Status         WorldShipmentStatus
	UpdatedAtSim   int64
}

// InsertShipment crea el cargamento físico de una entrega. En la retirada in
// situ (origen = destino) el cargamento nace ya 'released_in_situ' en el nodo
// de destino: la mercancía nunca se movió, cambia de dueño en el sitio.
func (q *Queries) InsertShipment(ctx context.Context, arg InsertShipmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertShipment,
		arg.ID,
		arg.OwnerAccountID,
		arg.ProductID,
		arg.Quantity,
		arg.ContractID,
		arg.AtNodeID,
		arg.Status,
		arg.UpdatedAtSim,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listBoardPublications = `-- name: ListBoardPublications :many
SELECT p.id, p.kind, p.publisher_account_id, p.channel, p.counterparty_account_id, p.product_id, p.quantity_total, p.quantity_remaining, p.unit_price, p.min_lot, p.origin_node_id, p.destination_node_id, p.delivery_sim_seconds, p.status, p.window_closes_at, p.cancel_cooldown_until, p.stock_reserve_account_id, p.guarantee_account_id, p.escrow_account_id, p.published_at_sim, p.created_at, p.updated_at
FROM ledger.publications p
WHERE p.channel = 'board'
  AND p.status IN ('draw_window', 'open', 'micro_window')
  AND ($1::ledger.publication_kind IS NULL OR p.kind = $1::ledger.publication_kind)
  AND ($2::uuid IS NULL OR p.product_id = $2::uuid)
  AND ($3::uuid IS NULL OR EXISTS (
        SELECT 1 FROM world.network_nodes n
        WHERE n.id = p.origin_node_id AND n.region_id = $3::uuid))
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM world.network_nodes n
        WHERE n.id = p.destination_node_id AND n.region_id = $4::uuid))
  AND ($5::bigint IS NULL OR p.unit_price >= $5::bigint)
  AND ($6::bigint IS NULL OR p.unit_price <= $6::bigint)
  AND ($7::bigint IS NULL OR p.quantity_remaining >= $7::bigint)
  AND ($8::bigint IS NULL OR p.delivery_sim_seconds <= $8::bigint)
  AND ($9::uuid IS NULL OR CASE $10::text
        WHEN 'unit_price_desc'   THEN (p.unit_price, p.id)           < ($11::bigint, $9::uuid)
        WHEN 'published_at_desc' THEN (p.published_at_sim, p.id)     < ($11::bigint, $9::uuid)
        WHEN 'deadline_asc'      THEN (p.delivery_sim_seconds, p.id) > ($11::bigint, $9::uuid)
        ELSE                          (p.unit_price, p.id)           > ($11::bigint, $9::uuid)
      END)
ORDER BY
  CASE WHEN $10::text = 'unit_price_desc'   THEN p.unit_price END DESC,
  CASE WHEN $10::text = 'published_at_desc' THEN p.published_at_sim END DESC,
  CASE WHEN $10::text = 'deadline_asc'      THEN p.delivery_sim_seconds END,
  CASE WHEN $10::text NOT IN ('unit_price_desc', 'published_at_desc', 'deadline_asc') THEN p.unit_price END,
  CASE WHEN $10::text IN ('unit_price_desc', 'published_at_desc') THEN p.id END DESC,
  p.id
LIMIT $12
`

type ListBoardPublicationsParams struct {
	Kind                  NullLedgerPublicationKind
	ProductID             *uuid.UUID
	OriginRegionID        *uuid.UUID
	DestinationRegionID   *uuid.UUID
	MinUnitPrice          *int64
	MaxUnitPrice          *int64
	MinQuantityRemaining  *int64
	MaxDeliverySimSeconds *int64
	AfterID               *uuid.UUID
	Sort                  string
	AfterKey              *int64
	PageLimit             int32
}

// ListBoardPublications consulta el tablón global (solo canal board y estados
// visibles) con los filtros del contrato, orden seleccionable y paginación
// keyset por (clave de orden, id). El discriminador sort activa una única
// rama de ORDER BY/predicado keyset por consulta; las ramas inactivas evalúan
// NULL de forma uniforme y no alteran el orden. after_key/after_id es la
// última fila de la página anterior (NULL en la primera).
func (q *Queries) ListBoardPublications(ctx context.Context, arg ListBoardPublicationsParams) ([]LedgerPublication, error) {
	rows, err := q.db.Query(ctx, listBoardPublications,
		arg.Kind,
		arg.ProductID,
		arg.OriginRegionID,
		arg.DestinationRegionID,
		arg.MinUnitPrice,
		arg.MaxUnitPrice,
		arg.MinQuantityRemaining,
		arg.MaxDeliverySimSeconds,
		arg.AfterID,
		arg.Sort,
		arg.AfterKey,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerPublication
	for rows.Next() {
		var i LedgerPublication
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.PublisherAccountID,
			&i.Channel,
			&i.CounterpartyAccountID,
			&i.ProductID,
			&i.QuantityTotal,
			&i.QuantityRemaining,
			&i.UnitPrice,
			&i.MinLot,
			&i.OriginNodeID,
			&i.DestinationNodeID,
			&i.DeliverySimSeconds,
			&i.Status,
			&i.WindowClosesAt,
			&i.CancelCooldownUntil,
			&i.StockReserveAccountID,
			&i.GuaranteeAccountID,
			&i.EscrowAccountID,
			&i.PublishedAtSim,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractDeliveries = `-- name: ListContractDeliveries :many
SELECT id, contract_id, shipment_id, quantity, delivered_at_sim, on_time, created_at FROM ledger.contract_deliveries
WHERE contract_id = $1
ORDER BY delivered_at_sim, id
`

// ListContractDeliveries devuelve las entregas confirmadas de un contrato, de
// la más antigua a la más reciente.
func (q *Queries) ListContractDeliveries(ctx context.Context, contractID uuid.UUID) ([]LedgerContractDelivery, error) {
	rows, err := q.db.Query(ctx, listContractDeliveries, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerContractDelivery
	for rows.Next() {
		var i LedgerContractDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ShipmentID,
			&i.Quantity,
			&i.DeliveredAtSim,
			&i.OnTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContracts = `-- name: ListContracts :many
SELECT id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at FROM ledger.contracts
WHERE (buyer_account_id = $1 OR seller_account_id = $1)
  AND ($2::text IS NULL
       OR ($2::text = 'buyer' AND buyer_account_id = $1)
       OR ($2::text = 'seller' AND seller_account_id = $1))
  AND ($3::text IS NULL OR status::text = $3::text)
  AND ($4::uuid IS NULL OR product_id = $4::uuid)
  AND ($5::uuid IS NULL OR id < $5::uuid)
ORDER BY id DESC
LIMIT $6
`

type ListContractsParams struct {
	AccountID uuid.UUID
	Role      *string
	Status    *string
	ProductID *uuid.UUID
	AfterID   *uuid.UUID
	PageLimit int32
}

// ListContracts lista los contratos en los que account_id es comprador o
// vendedor, con filtros de rol/estado/producto y paginación keyset (id DESC:
// los UUIDv7 preservan el orden de creación, primero los más recientes).
func (q *Queries) ListContracts(ctx context.Context, arg ListContractsParams) ([]LedgerContract, error) {
	rows, err := q.db.Query(ctx, listContracts,
		arg.AccountID,
		arg.Role,
		arg.Status,
		arg.ProductID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerContract
	for rows.Next() {
		var i LedgerContract
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.Channel,
			&i.BuyerAccountID,
			&i.SellerAccountID,
			&i.ProductID,
			&i.QuantityAgreed,
			&i.QuantityDelivered,
			&i.UnitPrice,
			&i.OriginNodeID,
			&i.DestinationNodeID,
			&i.DeadlineSim,
			&i.Status,
			&i.FillBp,
			&i.StockReserveAccountID,
			&i.SellerGuaranteeAccountID,
			&i.EscrowAccountID,
			&i.ConfirmedAtSim,
			&i.SettledAtSim,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueContractIDs = `-- name: ListDueContractIDs :many

SELECT id FROM ledger.contracts
WHERE status = 'active' AND deadline_sim <= $1::bigint
ORDER BY deadline_sim
LIMIT $2
`

type ListDueContractIDsParams struct {
	SimNow    int64
	PageLimit int32
}

// ─── (c) Liquidación de contratos por vencimiento de plazo ────────────────────
// ListDueContractIDs lista los contratos activos cuyo plazo de entrega venció
// (deadline_sim <= sim-time actual).
func (q *Queries) ListDueContractIDs(ctx context.Context, arg ListDueContractIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueContractIDs, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDrawPublicationIDs = `-- name: ListDueDrawPublicationIDs :many


SELECT id FROM ledger.publications
WHERE status IN ('draw_window', 'micro_window') AND window_closes_at <= now()
ORDER BY window_closes_at
LIMIT $1
`

// ═════════════════════════════════════════════════════════════════════════════
// Parte B: barridos periódicos (resolución de sorteo, expiración de TTL,
// liquidación por vencimiento) y lecturas de contratos/entregas. Cada barrido
// localiza sus candidatos con una query ligera (sin lock) y procesa cada
// publicación/contrato en SU PROPIA transacción SERIALIZABLE bloqueándolo con
// FOR UPDATE SKIP LOCKED (la fila re-verifica su condición bajo el lock: otra
// instancia del worker pudo resolverla ya).
// ═════════════════════════════════════════════════════════════════════════════
// ─── (a) Resolución de sorteo (ADR-011) ──────────────────────────────────────
// ListDueDrawPublicationIDs lista las publicaciones cuya ventana de sorteo o
// micro-ventana ya venció (window_closes_at <= now() de la BD), pendientes de
// resolver. Solo IDs: el worker bloquea cada una en su propia transacción.
func (q *Queries) ListDueDrawPublicationIDs(ctx context.Context, pageLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueDrawPublicationIDs, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPublicationIDs = `-- name: ListExpiredPublicationIDs :many

SELECT id FROM ledger.publications
WHERE status = 'open'
  AND published_at_sim + $1::bigint <= $2::bigint
ORDER BY published_at_sim
LIMIT $3
`

type ListExpiredPublicationIDsParams struct {
	TtlSimSeconds int64
	SimNow        int64
	PageLimit     int32
}

// ─── (b) Expiración de publicaciones abiertas por TTL ─────────────────────────
// ListExpiredPublicationIDs lista las publicaciones abiertas (open) cuyo TTL de
// sim-time venció (published_at_sim + ttl <= sim-time actual).
func (q *Queries) ListExpiredPublicationIDs(ctx context.Context, arg ListExpiredPublicationIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredPublicationIDs, arg.TtlSimSeconds, arg.SimNow, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAcceptancesForUpdate = `-- name: ListPendingAcceptancesForUpdate :many
SELECT id, publication_id, acceptor_account_id, quantity, quantity_served, status, draw_order, stock_reserve_account_id, guarantee_account_id, escrow_account_id, accepted_at, resolved_at FROM ledger.publication_acceptances
WHERE publication_id = $1 AND status = 'pending_draw'
ORDER BY accepted_at, id
FOR UPDATE
`

// ListPendingAcceptancesForUpdate bloquea y devuelve las aceptaciones
// pendientes de sorteo de una publicación, en orden estable de llegada (la
// cancelación libera sus garantías y les asigna draw_order por ese orden).
func (q *Queries) ListPendingAcceptancesForUpdate(ctx context.Context, publicationID uuid.UUID) ([]LedgerPublicationAcceptance, error) {
	rows, err := q.db.Query(ctx, listPendingAcceptancesForUpdate, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerPublicationAcceptance
	for rows.Next() {
		var i LedgerPublicationAcceptance
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.AcceptorAccountID,
			&i.Quantity,
			&i.QuantityServed,
			&i.Status,
			&i.DrawOrder,
			&i.StockReserveAccountID,
			&i.GuaranteeAccountID,
			&i.EscrowAccountID,
			&i.AcceptedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueContract = `-- name: LockDueContract :one
SELECT id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at FROM ledger.contracts
WHERE id = $1 AND status = 'active' AND deadline_sim <= $2::bigint
FOR UPDATE SKIP LOCKED
`

type LockDueContractParams struct {
	ID     uuid.UUID
	SimNow int64
}

// LockDueContract bloquea un contrato activo vencido (re-verifica bajo el lock;
// SKIP LOCKED salta los tomados por otra instancia). settle_contract_prorata
// vuelve a bloquear la fila (FOR UPDATE) y re-verifica que sigue activo.
func (q *Queries) LockDueContract(ctx context.Context, arg LockDueContractParams) (LedgerContract, error) {
	row := q.db.QueryRow(ctx, lockDueContract, arg.ID, arg.SimNow)
	var i LedgerContract
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.Channel,
		&i.BuyerAccountID,
		&i.SellerAccountID,
		&i.ProductID,
		&i.QuantityAgreed,
		&i.QuantityDelivered,
		&i.UnitPrice,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.FillBp,
		&i.StockReserveAccountID,
		&i.SellerGuaranteeAccountID,
		&i.EscrowAccountID,
		&i.ConfirmedAtSim,
		&i.SettledAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockDueDrawPublication = `-- name: LockDueDrawPublication :one
SELECT id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at FROM ledger.publications
WHERE id = $1
  AND status IN ('draw_window', 'micro_window')
  AND window_closes_at <= now()
FOR UPDATE SKIP LOCKED
`

// LockDueDrawPublication bloquea una publicación con la ventana vencida
// (re-verifica estado y vencimiento bajo el lock; FOR UPDATE SKIP LOCKED salta
// las ya tomadas por otra instancia). Sin fila ⇒ ya resuelta o en curso.
func (q *Queries) LockDueDrawPublication(ctx context.Context, id uuid.UUID) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, lockDueDrawPublication, id)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockExpiredPublication = `-- name: LockExpiredPublication :one
SELECT id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at FROM ledger.publications
WHERE id = $1
  AND status = 'open'
  AND published_at_sim + $2::bigint <= $3::bigint
FOR UPDATE SKIP LOCKED
`

type LockExpiredPublicationParams struct {
	ID            uuid.UUID
	TtlSimSeconds int64
	SimNow        int64
}

// LockExpiredPublication bloquea una publicación abierta vencida por TTL
// (re-verifica bajo el lock; SKIP LOCKED salta las tomadas por otra instancia).
func (q *Queries) LockExpiredPublication(ctx context.Context, arg LockExpiredPublicationParams) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, lockExpiredPublication, arg.ID, arg.TtlSimSeconds, arg.SimNow)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const productExists = `-- name: ProductExists :one

SELECT EXISTS (SELECT 1 FROM world.products WHERE id = $1)::boolean AS present
`

// ─── Validaciones de mundo ───────────────────────────────────────────────────
// ProductExists comprueba la existencia de un producto del catálogo.
func (q *Queries) ProductExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, id)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const releaseAcceptance = `-- name: ReleaseAcceptance :one
UPDATE ledger.publication_acceptances
   SET status = 'released', resolved_at = now(), draw_order = $1
 WHERE id = $2
RETURNING id, publication_id, acceptor_account_id, quantity, quantity_served, status, draw_order, stock_reserve_account_id, guarantee_account_id, escrow_account_id, accepted_at, resolved_at
`

type ReleaseAcceptanceParams struct {
	DrawOrder *int32
	ID        uuid.UUID
}

// ReleaseAcceptance resuelve una aceptación como no servida. draw_order es
// obligatorio al salir de pending_draw (CHECK de 0004); en una liberación por
// cancelación se asigna por orden de llegada.
func (q *Queries) ReleaseAcceptance(ctx context.Context, arg ReleaseAcceptanceParams) (LedgerPublicationAcceptance, error) {
	row := q.db.QueryRow(ctx, releaseAcceptance, arg.DrawOrder, arg.ID)
	var i LedgerPublicationAcceptance
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.AcceptorAccountID,
		&i.Quantity,
		&i.QuantityServed,
		&i.Status,
		&i.DrawOrder,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.AcceptedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const serveAcceptance = `-- name: ServeAcceptance :one
UPDATE ledger.publication_acceptances
   SET status = 'served', quantity_served = $1,
       draw_order = $2, resolved_at = now()
 WHERE id = $3
RETURNING id, publication_id, acceptor_account_id, quantity, quantity_served, status, draw_order, stock_reserve_account_id, guarantee_account_id, escrow_account_id, accepted_at, resolved_at
`

type ServeAcceptanceParams struct {
	QuantityServed int64
	DrawOrder      *int32
	ID             uuid.UUID
}

// ServeAcceptance resuelve una aceptación como servida (total o parcialmente)
// en el orden sorteado, con la cantidad servida y su draw_order.
func (q *Queries) ServeAcceptance(ctx context.Context, arg ServeAcceptanceParams) (LedgerPublicationAcceptance, error) {
	row := q.db.QueryRow(ctx, serveAcceptance, arg.QuantityServed, arg.DrawOrder, arg.ID)
	var i LedgerPublicationAcceptance
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.AcceptorAccountID,
		&i.Quantity,
		&i.QuantityServed,
		&i.Status,
		&i.DrawOrder,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.AcceptedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const setContractQuantityDelivered = `-- name: SetContractQuantityDelivered :one
UPDATE ledger.contracts
   SET quantity_delivered = $1, updated_at = now()
 WHERE id = $2
RETURNING id, publication_id, channel, buyer_account_id, seller_account_id, product_id, quantity_agreed, quantity_delivered, unit_price, origin_node_id, destination_node_id, deadline_sim, status, fill_bp, stock_reserve_account_id, seller_guarantee_account_id, escrow_account_id, confirmed_at_sim, settled_at_sim, created_at, updated_at
`

type SetContractQuantityDeliveredParams struct {
	QuantityDelivered int64
	ID                uuid.UUID
}

// SetContractQuantityDelivered acumula la cantidad entregada a tiempo de un
// contrato (la lee settle_contract_prorata para el reparto pro-rata).
func (q *Queries) SetContractQuantityDelivered(ctx context.Context, arg SetContractQuantityDeliveredParams) (LedgerContract, error) {
	row := q.db.QueryRow(ctx, setContractQuantityDelivered, arg.QuantityDelivered, arg.ID)
	var i LedgerContract
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.Channel,
		&i.BuyerAccountID,
		&i.SellerAccountID,
		&i.ProductID,
		&i.QuantityAgreed,
		&i.QuantityDelivered,
		&i.UnitPrice,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeadlineSim,
		&i.Status,
		&i.FillBp,
		&i.StockReserveAccountID,
		&i.SellerGuaranteeAccountID,
		&i.EscrowAccountID,
		&i.ConfirmedAtSim,
		&i.SettledAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPublicationCancelled = `-- name: SetPublicationCancelled :one
UPDATE ledger.publications
   SET status = 'cancelled', updated_at = now()
 WHERE id = $1
RETURNING id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at
`

// SetPublicationCancelled marca la publicación como cancelada (la liberación
// contable de garantías se asienta aparte, en la misma transacción).
func (q *Queries) SetPublicationCancelled(ctx context.Context, id uuid.UUID) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, setPublicationCancelled, id)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPublicationDrawResult = `-- name: SetPublicationDrawResult :one
UPDATE ledger.publications
   SET quantity_remaining = $1,
       status = $2,
       window_closes_at = NULL,
       updated_at = now()
 WHERE id = $3
RETURNING id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at
`

type SetPublicationDrawResultParams struct {
	QuantityRemaining int64
	Status            LedgerPublicationStatus
	ID                uuid.UUID
}

// SetPublicationDrawResult fija la cantidad restante y el estado tras el
// sorteo: 'exhausted' si se agotó, 'open' si resta cantidad (madura, sin
// ventana). window_closes_at se limpia en ambos casos.
func (q *Queries) SetPublicationDrawResult(ctx context.Context, arg SetPublicationDrawResultParams) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, setPublicationDrawResult, arg.QuantityRemaining, arg.Status, arg.ID)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPublicationExpired = `-- name: SetPublicationExpired :one
UPDATE ledger.publications
   SET status = 'expired', updated_at = now()
 WHERE id = $1
RETURNING id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at
`

// SetPublicationExpired marca la publicación como expirada (la liberación de la
// garantía restante se asienta aparte, en la misma transacción).
func (q *Queries) SetPublicationExpired(ctx context.Context, id uuid.UUID) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, setPublicationExpired, id)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPublicationMicroWindow = `-- name: SetPublicationMicroWindow :one
UPDATE ledger.publications
   SET status = 'micro_window',
       window_closes_at = now() + $1::bigint * interval '1 second',
       updated_at = now()
 WHERE id = $2
RETURNING id, kind, publisher_account_id, channel, counterparty_account_id, product_id, quantity_total, quantity_remaining, unit_price, min_lot, origin_node_id, destination_node_id, delivery_sim_seconds, status, window_closes_at, cancel_cooldown_until, stock_reserve_account_id, guarantee_account_id, escrow_account_id, published_at_sim, created_at, updated_at
`

type SetPublicationMicroWindowParams struct {
	MicroWindowSeconds int64
	ID                 uuid.UUID
}

// SetPublicationMicroWindow abre la micro-ventana sobre una publicación
// madura (open): primera aceptación posterior a su ventana inicial (ADR-011).
func (q *Queries) SetPublicationMicroWindow(ctx context.Context, arg SetPublicationMicroWindowParams) (LedgerPublication, error) {
	row := q.db.QueryRow(ctx, setPublicationMicroWindow, arg.MicroWindowSeconds, arg.ID)
	var i LedgerPublication
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PublisherAccountID,
		&i.Channel,
		&i.CounterpartyAccountID,
		&i.ProductID,
		&i.QuantityTotal,
		&i.QuantityRemaining,
		&i.UnitPrice,
		&i.MinLot,
		&i.OriginNodeID,
		&i.DestinationNodeID,
		&i.DeliverySimSeconds,
		&i.Status,
		&i.WindowClosesAt,
		&i.CancelCooldownUntil,
		&i.StockReserveAccountID,
		&i.GuaranteeAccountID,
		&i.EscrowAccountID,
		&i.PublishedAtSim,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
