// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type LedgerAcceptanceStatus string

const (
	LedgerAcceptanceStatusPendingDraw LedgerAcceptanceStatus = "pending_draw"
	LedgerAcceptanceStatusServed      LedgerAcceptanceStatus = "served"
	LedgerAcceptanceStatusReleased    LedgerAcceptanceStatus = "released"
)

func (e *LedgerAcceptanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerAcceptanceStatus(s)
	case string:
		*e = LedgerAcceptanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerAcceptanceStatus: %T", src)
	}
	return nil
}

type NullLedgerAcceptanceStatus struct {
	LedgerAcceptanceStatus LedgerAcceptanceStatus
	Valid                  bool // Valid is true if LedgerAcceptanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerAcceptanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerAcceptanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerAcceptanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerAcceptanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerAcceptanceStatus), nil
}

type LedgerAccountKind string

const (
	LedgerAccountKindCash          LedgerAccountKind = "cash"
	LedgerAccountKindEscrow        LedgerAccountKind = "escrow"
	LedgerAccountKindGuarantee     LedgerAccountKind = "guarantee"
	LedgerAccountKindStockFree     LedgerAccountKind = "stock_free"
	LedgerAccountKindStockReserved LedgerAccountKind = "stock_reserved"
	LedgerAccountKindCustody       LedgerAccountKind = "custody"
	LedgerAccountKindSink          LedgerAccountKind = "sink"
	LedgerAccountKindEmission      LedgerAccountKind = "emission"
	LedgerAccountKindWorldSource   LedgerAccountKind = "world_source"
)

func (e *LedgerAccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerAccountKind(s)
	case string:
		*e = LedgerAccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerAccountKind: %T", src)
	}
	return nil
}

type NullLedgerAccountKind struct {
	LedgerAccountKind LedgerAccountKind
	Valid             bool // Valid is true if LedgerAccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerAccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerAccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerAccountKind), nil
}

type LedgerContractChannel string

const (
	LedgerContractChannelBoard   LedgerContractChannel = "board"
	LedgerContractChannelPrivate LedgerContractChannel = "private"
)

func (e *LedgerContractChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerContractChannel(s)
	case string:
		*e = LedgerContractChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerContractChannel: %T", src)
	}
	return nil
}

type NullLedgerContractChannel struct {
	LedgerContractChannel LedgerContractChannel
	Valid                 bool // Valid is true if LedgerContractChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerContractChannel) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerContractChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerContractChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerContractChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerContractChannel), nil
}

type LedgerContractStatus string

const (
	LedgerContractStatusActive  LedgerContractStatus = "active"
	LedgerContractStatusSettled LedgerContractStatus = "settled"
	LedgerContractStatusFailed  LedgerContractStatus = "failed"
)

func (e *LedgerContractStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerContractStatus(s)
	case string:
		*e = LedgerContractStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerContractStatus: %T", src)
	}
	return nil
}

type NullLedgerContractStatus struct {
	LedgerContractStatus LedgerContractStatus
	Valid                bool // Valid is true if LedgerContractStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerContractStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerContractStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerContractStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerContractStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerContractStatus), nil
}

type LedgerPublicationKind string

const (
	LedgerPublicationKindSell    LedgerPublicationKind = "sell"
	LedgerPublicationKindBuy     LedgerPublicationKind = "buy"
	LedgerPublicationKindFreight LedgerPublicationKind = "freight"
)

func (e *LedgerPublicationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerPublicationKind(s)
	case string:
		*e = LedgerPublicationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerPublicationKind: %T", src)
	}
	return nil
}

type NullLedgerPublicationKind struct {
	LedgerPublicationKind LedgerPublicationKind
	Valid                 bool // Valid is true if LedgerPublicationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerPublicationKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerPublicationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerPublicationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerPublicationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerPublicationKind), nil
}

type LedgerPublicationStatus string

const (
	LedgerPublicationStatusDrawWindow  LedgerPublicationStatus = "draw_window"
	LedgerPublicationStatusOpen        LedgerPublicationStatus = "open"
	LedgerPublicationStatusMicroWindow LedgerPublicationStatus = "micro_window"
	LedgerPublicationStatusExhausted   LedgerPublicationStatus = "exhausted"
	LedgerPublicationStatusCancelled   LedgerPublicationStatus = "cancelled"
	LedgerPublicationStatusExpired     LedgerPublicationStatus = "expired"
)

func (e *LedgerPublicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerPublicationStatus(s)
	case string:
		*e = LedgerPublicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerPublicationStatus: %T", src)
	}
	return nil
}

type NullLedgerPublicationStatus struct {
	LedgerPublicationStatus LedgerPublicationStatus
	Valid                   bool // Valid is true if LedgerPublicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerPublicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerPublicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerPublicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerPublicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerPublicationStatus), nil
}

type LedgerTransactionKind string

const (
	LedgerTransactionKindSeedCapital          LedgerTransactionKind = "seed_capital"
	LedgerTransactionKindBotCapitalization    LedgerTransactionKind = "bot_capitalization"
	LedgerTransactionKindBotRetirement        LedgerTransactionKind = "bot_retirement"
	LedgerTransactionKindPublicationLock      LedgerTransactionKind = "publication_lock"
	LedgerTransactionKindPublicationRelease   LedgerTransactionKind = "publication_release"
	LedgerTransactionKindAcceptanceLock       LedgerTransactionKind = "acceptance_lock"
	LedgerTransactionKindContractConfirmation LedgerTransactionKind = "contract_confirmation"
	LedgerTransactionKindDeliverySettlement   LedgerTransactionKind = "delivery_settlement"
	LedgerTransactionKindCustodyLoad          LedgerTransactionKind = "custody_load"
	LedgerTransactionKindCustodyRelease       LedgerTransactionKind = "custody_release"
	LedgerTransactionKindProductionOutput     LedgerTransactionKind = "production_output"
	LedgerTransactionKindConsumption          LedgerTransactionKind = "consumption"
	LedgerTransactionKindWage                 LedgerTransactionKind = "wage"
	LedgerTransactionKindMaintenance          LedgerTransactionKind = "maintenance"
	LedgerTransactionKindTax                  LedgerTransactionKind = "tax"
	LedgerTransactionKindCanon                LedgerTransactionKind = "canon"
	LedgerTransactionKindTransfer             LedgerTransactionKind = "transfer"
	LedgerTransactionKindAuction              LedgerTransactionKind = "auction"
	LedgerTransactionKindReconciliation       LedgerTransactionKind = "reconciliation"
)

func (e *LedgerTransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerTransactionKind(s)
	case string:
		*e = LedgerTransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerTransactionKind: %T", src)
	}
	return nil
}

type NullLedgerTransactionKind struct {
	LedgerTransactionKind LedgerTransactionKind
	Valid                 bool // Valid is true if LedgerTransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerTransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerTransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerTransactionKind), nil
}

type WorldShipmentStatus string

const (
	WorldShipmentStatusInWarehouse    WorldShipmentStatus = "in_warehouse"
	WorldShipmentStatusInTransit      WorldShipmentStatus = "in_transit"
	WorldShipmentStatusAtTerminal     WorldShipmentStatus = "at_terminal"
	WorldShipmentStatusDelivered      WorldShipmentStatus = "delivered"
	WorldShipmentStatusReleasedInSitu WorldShipmentStatus = "released_in_situ"
)

func (e *WorldShipmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorldShipmentStatus(s)
	case string:
		*e = WorldShipmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorldShipmentStatus: %T", src)
	}
	return nil
}

type NullWorldShipmentStatus struct {
	WorldShipmentStatus WorldShipmentStatus
	Valid               bool // Valid is true if WorldShipmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorldShipmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorldShipmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorldShipmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorldShipmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorldShipmentStatus), nil
}

type LedgerAccount struct {
	ID                  uuid.UUID
	Kind                LedgerAccountKind
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
	ReferenceID         *uuid.UUID
	Balance             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type LedgerContract struct {
	ID                       uuid.UUID
	PublicationID            *uuid.UUID
	Channel                  LedgerContractChannel
	BuyerAccountID           uuid.UUID
	SellerAccountID          uuid.UUID
	ProductID                uuid.UUID
	QuantityAgreed           int64
	QuantityDelivered        int64
	UnitPrice                int64
	OriginNodeID             uuid.UUID
	DestinationNodeID        uuid.UUID
	DeadlineSim              int64
	Status                   LedgerContractStatus
	FillBp                   *int32
	StockReserveAccountID    uuid.UUID
	SellerGuaranteeAccountID uuid.UUID
	EscrowAccountID          uuid.UUID
	ConfirmedAtSim           int64
	SettledAtSim             *int64
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type LedgerContractDelivery struct {
	ID             uuid.UUID
	ContractID     uuid.UUID
	ShipmentID     uuid.UUID
	Quantity       int64
	DeliveredAtSim int64
	OnTime         bool
	CreatedAt      time.Time
}

type LedgerFreightContract struct {
	ID                        uuid.UUID
	PublicationID             *uuid.UUID
	Channel                   LedgerContractChannel
	ShipperAccountID          uuid.UUID
	CarrierAccountID          uuid.UUID
	OriginNodeID              uuid.UUID
	DestinationNodeID         uuid.UUID
	FreightPrice              int64
	DeclaredValue             int64
	DeadlineSim               int64
	Status                    LedgerContractStatus
	FillBp                    *int32
	EscrowAccountID           uuid.UUID
	CarrierGuaranteeAccountID uuid.UUID
	CustodyAccountID          uuid.UUID
	ConfirmedAtSim            int64
	SettledAtSim              *int64
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type LedgerPublication struct {
	ID                    uuid.UUID
	Kind                  LedgerPublicationKind
	PublisherAccountID    uuid.UUID
	Channel               LedgerContractChannel
	CounterpartyAccountID *uuid.UUID
	ProductID             *uuid.UUID
	QuantityTotal         int64
	QuantityRemaining     int64
	UnitPrice             int64
	MinLot                int64
	OriginNodeID          *uuid.UUID
	DestinationNodeID     *uuid.UUID
	DeliverySimSeconds    int64
	Status                LedgerPublicationStatus
	WindowClosesAt        *time.Time
	CancelCooldownUntil   *time.Time
	StockReserveAccountID *uuid.UUID
	GuaranteeAccountID    *uuid.UUID
	EscrowAccountID       *uuid.UUID
	PublishedAtSim        int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	// CCRI-Flete: valor declarado de la carga, base de la garantía del transportista (NULL salvo kind=freight).
	DeclaredValue *int64
}

type LedgerPublicationAcceptance struct {
	ID                    uuid.UUID
	PublicationID         uuid.UUID
	AcceptorAccountID     uuid.UUID
	Quantity              int64
	QuantityServed        int64
	Status                LedgerAcceptanceStatus
	DrawOrder             *int32
	StockReserveAccountID *uuid.UUID
	GuaranteeAccountID    *uuid.UUID
	EscrowAccountID       *uuid.UUID
	AcceptedAt            time.Time
	ResolvedAt            *time.Time
}
