// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listOhlcCandles = `-- name: ListOhlcCandles :many
SELECT product_id, region_id, bucket_start_sim, bucket_sim_secs,
       open_price, high_price, low_price, close_price, volume, contract_count
FROM analytics.market_ohlc
WHERE product_id = $1
  AND ($2::uuid IS NULL OR region_id = $2::uuid)
  AND ($3::bigint IS NULL OR bucket_start_sim >= $3::bigint)
  AND ($4::bigint IS NULL OR bucket_start_sim <= $4::bigint)
ORDER BY bucket_start_sim, region_id
LIMIT $5
`

type ListOhlcCandlesParams struct {
	ProductID uuid.UUID
	RegionID  *uuid.UUID
	FromSim   *int64
	ToSim     *int64
	PageLimit int32
}

type ListOhlcCandlesRow struct {
	ProductID      uuid.UUID
	RegionID       uuid.UUID
	BucketStartSim int64
	BucketSimSecs  int64
	OpenPrice      int64
	HighPrice      int64
	LowPrice       int64
	ClosePrice     int64
	Volume         int64
	ContractCount  int32
}

// ListOhlcCandles devuelve la serie OHLC de un producto (contrato
// GET /market/ohlc), con filtros opcionales por región y rango de sim-time
// sobre bucket_start_sim, en orden cronológico. Cada vela expone su propio
// bucket_sim_secs (la granularidad realmente almacenada): el lado de lectura
// NO re-agrega a otro tamaño de bucket.
func (q *Queries) ListOhlcCandles(ctx context.Context, arg ListOhlcCandlesParams) ([]ListOhlcCandlesRow, error) {
	rows, err := q.db.Query(ctx, listOhlcCandles,
		arg.ProductID,
		arg.RegionID,
		arg.FromSim,
		arg.ToSim,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOhlcCandlesRow
	for rows.Next() {
		var i ListOhlcCandlesRow
		if err := rows.Scan(
			&i.ProductID,
			&i.RegionID,
			&i.BucketStartSim,
			&i.BucketSimSecs,
			&i.OpenPrice,
			&i.HighPrice,
			&i.LowPrice,
			&i.ClosePrice,
			&i.Volume,
			&i.ContractCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOhlcCandle = `-- name: UpsertOhlcCandle :exec

INSERT INTO analytics.market_ohlc (
    product_id, region_id, bucket_start_sim, bucket_sim_secs,
    open_price, high_price, low_price, close_price, volume, contract_count)
VALUES (
    $1, $2, $3, $4,
    $5, $5, $5, $5,
    $6, 1)
ON CONFLICT (product_id, region_id, bucket_start_sim) DO UPDATE SET
    high_price     = GREATEST(analytics.market_ohlc.high_price, EXCLUDED.high_price),
    low_price      = LEAST(analytics.market_ohlc.low_price, EXCLUDED.low_price),
    close_price    = EXCLUDED.close_price,
    volume         = analytics.market_ohlc.volume + EXCLUDED.volume,
    contract_count = analytics.market_ohlc.contract_count + 1
`

type UpsertOhlcCandleParams struct {
	ProductID         uuid.UUID
	RegionID          uuid.UUID
	BucketStartSim    int64
	BucketSimSecs     int64
	UnitPrice         int64
	QuantityDelivered int64
}

// =============================================================================
// Imperio Industrial — queries sqlc del módulo market (ADR-020).
// Velas OHLC del historial de precios (GDD 5.2), construidas EXCLUSIVAMENTE a
// partir de contratos liquidados (analytics.market_ohlc, 0005_analytics). El
// agregador hace UPSERT dentro de la transacción del consumidor del outbox; el
// lado de lectura sirve la serie tal cual está almacenada, sin re-agregar.
// =============================================================================
// UpsertOhlcCandle asienta una entrega liquidada en la vela de su bucket
// (product_id, region_id, bucket_start_sim). La primera entrega del bucket abre
// la vela (open=high=low=close=unit_price, volume=delivered, count=1); las
// siguientes extienden high/low, fijan close al último precio procesado y
// acumulan volumen y contratos. El orden de proceso lo garantiza el consumidor
// (por seq): close queda con el unit_price del último evento del lote.
func (q *Queries) UpsertOhlcCandle(ctx context.Context, arg UpsertOhlcCandleParams) error {
	_, err := q.db.Exec(ctx, upsertOhlcCandle,
		arg.ProductID,
		arg.RegionID,
		arg.BucketStartSim,
		arg.BucketSimSecs,
		arg.UnitPrice,
		arg.QuantityDelivered,
	)
	return err
}
