// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger.accounts (id, kind, owner_account_id, product_id, warehouse_building_id, reference_id)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, kind, owner_account_id, product_id, warehouse_building_id,
          reference_id, balance, created_at, updated_at
`

type CreateLedgerAccountParams struct {
	ID                  uuid.UUID
	Kind                LedgerAccountKind
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
	ReferenceID         *uuid.UUID
}

// CreateLedgerAccount crea una cuenta del ledger. El id (UUIDv7) lo genera la
// aplicación (ADR-018); los constraints ck_accounts_asset y las unicidades
// parciales (ux_accounts_cash, ux_accounts_stock_free) validan la forma.
func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.ID,
		arg.Kind,
		arg.OwnerAccountID,
		arg.ProductID,
		arg.WarehouseBuildingID,
		arg.ReferenceID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, kind, owner_account_id, product_id, warehouse_building_id,
       reference_id, balance, created_at, updated_at
FROM ledger.accounts
WHERE id = $1
`

// GetAccount devuelve una cuenta del ledger por id (autorización por
// propiedad en la capa de servicio).
func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCashAccountByOwner = `-- name: GetCashAccountByOwner :one
SELECT id, kind, owner_account_id, product_id, warehouse_building_id,
       reference_id, balance, created_at, updated_at
FROM ledger.accounts
WHERE kind = 'cash' AND owner_account_id = $1
`

// GetCashAccountByOwner devuelve la única cuenta de caja de una corporación
// (unicidad parcial ux_accounts_cash).
func (q *Queries) GetCashAccountByOwner(ctx context.Context, ownerAccountID *uuid.UUID) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getCashAccountByOwner, ownerAccountID)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerAccountID,
		&i.ProductID,
		&i.WarehouseBuildingID,
		&i.ReferenceID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO ledger.entries (id, transaction_id, account_id, amount)
VALUES ($1, $2, $3, $4)
`

type InsertEntryParams struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
}

// InsertEntry inserta una partida de doble entrada. Los triggers aplican el
// saldo, la no-negatividad y (diferido, en el COMMIT) el balance del asiento.
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO ledger.transactions (id, kind, sim_time_at, reference_id, description)
VALUES ($1, $2, $3,
        $4, $5)
`

type InsertTransactionParams struct {
	ID          uuid.UUID
	Kind        LedgerTransactionKind
	SimTimeAt   int64
	ReferenceID *uuid.UUID
	Description *string
}

// InsertTransaction inserta la cabecera de un asiento. Inmutable una vez
// asentada (trigger trg_transactions_immutable).
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.Kind,
		arg.SimTimeAt,
		arg.ReferenceID,
		arg.Description,
	)
	return err
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many

SELECT id, kind, owner_account_id, product_id, warehouse_building_id,
       reference_id, balance, created_at, updated_at
FROM ledger.accounts
WHERE owner_account_id = $1
  AND ($2::ledger.account_kind IS NULL OR kind = $2::ledger.account_kind)
  AND ($3::uuid IS NULL OR product_id = $3::uuid)
  AND ($4::uuid IS NULL OR id > $4::uuid)
ORDER BY id
LIMIT $5
`

type ListAccountsByOwnerParams struct {
	OwnerAccountID *uuid.UUID
	Kind           NullLedgerAccountKind
	ProductID      *uuid.UUID
	AfterID        *uuid.UUID
	PageLimit      int32
}

// =============================================================================
// Imperio Industrial — queries sqlc del módulo ledger (ADR-020).
// Solo lecturas del núcleo contable y primitivas de asiento; las invariantes
// (balance por cuenta, doble entrada, no-negatividad, inmutabilidad) las
// garantizan los triggers de 0004_ledger — aquí nunca se recalculan saldos.
// =============================================================================
// ListAccountsByOwner lista las cuentas del ledger de una corporación con
// filtros opcionales por tipo y producto. Paginación keyset ascendente por id
// (UUIDv7 ≈ orden temporal de creación): after_id es el último id de la
// página anterior; NULL en la primera página.
func (q *Queries) ListAccountsByOwner(ctx context.Context, arg ListAccountsByOwnerParams) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listAccountsByOwner,
		arg.OwnerAccountID,
		arg.Kind,
		arg.ProductID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerAccount
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerAccountID,
			&i.ProductID,
			&i.WarehouseBuildingID,
			&i.ReferenceID,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT e.id, e.transaction_id, e.account_id, e.amount, e.created_at,
       t.kind AS transaction_kind, t.reference_id, t.description, t.sim_time_at
FROM ledger.entries e
JOIN ledger.transactions t ON t.id = e.transaction_id
WHERE e.account_id = $1
  AND ($2::bigint IS NULL OR t.sim_time_at >= $2::bigint)
  AND ($3::bigint IS NULL OR t.sim_time_at <= $3::bigint)
  AND ($4::timestamptz IS NULL
       OR (e.created_at, e.id) < ($4::timestamptz, $5::uuid))
ORDER BY e.created_at DESC, e.id DESC
LIMIT $6
`

type ListEntriesByAccountParams struct {
	AccountID       uuid.UUID
	FromSim         *int64
	ToSim           *int64
	BeforeCreatedAt *time.Time
	BeforeID        *uuid.UUID
	PageLimit       int32
}

type ListEntriesByAccountRow struct {
	ID              uuid.UUID
	TransactionID   uuid.UUID
	AccountID       uuid.UUID
	Amount          int64
	CreatedAt       time.Time
	TransactionKind LedgerTransactionKind
	ReferenceID     *uuid.UUID
	Description     *string
	SimTimeAt       int64
}

// ListEntriesByAccount devuelve el extracto de una cuenta, de más reciente a
// más antigua, con la cabecera del asiento (kind/reference/description/
// sim_time_at, schema LedgerEntry del contrato). Rango opcional de sim-time
// y paginación keyset por (created_at, id) DESC: before_* es la última
// partida de la página anterior; NULL en la primera página.
func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]ListEntriesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount,
		arg.AccountID,
		arg.FromSim,
		arg.ToSim,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByAccountRow
	for rows.Next() {
		var i ListEntriesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
			&i.TransactionKind,
			&i.ReferenceID,
			&i.Description,
			&i.SimTimeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
