// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type LedgerAccountKind string

const (
	LedgerAccountKindCash          LedgerAccountKind = "cash"
	LedgerAccountKindEscrow        LedgerAccountKind = "escrow"
	LedgerAccountKindGuarantee     LedgerAccountKind = "guarantee"
	LedgerAccountKindStockFree     LedgerAccountKind = "stock_free"
	LedgerAccountKindStockReserved LedgerAccountKind = "stock_reserved"
	LedgerAccountKindCustody       LedgerAccountKind = "custody"
	LedgerAccountKindSink          LedgerAccountKind = "sink"
	LedgerAccountKindEmission      LedgerAccountKind = "emission"
)

func (e *LedgerAccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerAccountKind(s)
	case string:
		*e = LedgerAccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerAccountKind: %T", src)
	}
	return nil
}

type NullLedgerAccountKind struct {
	LedgerAccountKind LedgerAccountKind
	Valid             bool // Valid is true if LedgerAccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerAccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerAccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerAccountKind), nil
}

type LedgerTransactionKind string

const (
	LedgerTransactionKindSeedCapital          LedgerTransactionKind = "seed_capital"
	LedgerTransactionKindBotCapitalization    LedgerTransactionKind = "bot_capitalization"
	LedgerTransactionKindBotRetirement        LedgerTransactionKind = "bot_retirement"
	LedgerTransactionKindPublicationLock      LedgerTransactionKind = "publication_lock"
	LedgerTransactionKindPublicationRelease   LedgerTransactionKind = "publication_release"
	LedgerTransactionKindAcceptanceLock       LedgerTransactionKind = "acceptance_lock"
	LedgerTransactionKindContractConfirmation LedgerTransactionKind = "contract_confirmation"
	LedgerTransactionKindDeliverySettlement   LedgerTransactionKind = "delivery_settlement"
	LedgerTransactionKindCustodyLoad          LedgerTransactionKind = "custody_load"
	LedgerTransactionKindCustodyRelease       LedgerTransactionKind = "custody_release"
	LedgerTransactionKindProductionOutput     LedgerTransactionKind = "production_output"
	LedgerTransactionKindConsumption          LedgerTransactionKind = "consumption"
	LedgerTransactionKindWage                 LedgerTransactionKind = "wage"
	LedgerTransactionKindMaintenance          LedgerTransactionKind = "maintenance"
	LedgerTransactionKindTax                  LedgerTransactionKind = "tax"
	LedgerTransactionKindCanon                LedgerTransactionKind = "canon"
	LedgerTransactionKindTransfer             LedgerTransactionKind = "transfer"
	LedgerTransactionKindAuction              LedgerTransactionKind = "auction"
	LedgerTransactionKindReconciliation       LedgerTransactionKind = "reconciliation"
)

func (e *LedgerTransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerTransactionKind(s)
	case string:
		*e = LedgerTransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerTransactionKind: %T", src)
	}
	return nil
}

type NullLedgerTransactionKind struct {
	LedgerTransactionKind LedgerTransactionKind
	Valid                 bool // Valid is true if LedgerTransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerTransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerTransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerTransactionKind), nil
}

type LedgerAccount struct {
	ID                  uuid.UUID
	Kind                LedgerAccountKind
	OwnerAccountID      *uuid.UUID
	ProductID           *uuid.UUID
	WarehouseBuildingID *uuid.UUID
	ReferenceID         *uuid.UUID
	Balance             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
